// SPDX-License-Identifier: Apache-2.0

import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'
import { runGoogleAdkTypeScriptDecisionLedgerProof } from '../examples/google-adk-typescript/google-adk-typescript-decision-ledger-proof.js'
import {
  buildDecisionLedgerEntry,
  GOOGLE_ADK_DECISION_LEDGER_SCHEMA,
} from '../src/google-adk-typescript-decision-ledger.js'
import type { GoogleAdkDecisionLedgerEntry } from '../src/google-adk-typescript-decision-ledger.js'

type FixtureCorpus = {
  schema: 'atrib.google-adk.decision-ledger.fixtures.v1'
  event_type: string
  entries: Record<string, GoogleAdkDecisionLedgerEntry>
}

describe('Google ADK TypeScript decision ledger proof', () => {
  it('signs ADK authority decisions before tool execution', async () => {
    const result = await runGoogleAdkTypeScriptDecisionLedgerProof()

    expect(result.ok).toBe(true)
    expect(result.strategy).toBe('atrib-google-adk-typescript-decision-ledger-proof-v1')
    expect(result.adk).toMatchObject({
      package: '@google/adk',
      version: '1.2.0',
      runner: 'InMemoryRunner',
      plugin: 'BasePlugin',
      tool: 'FunctionTool',
    })
    expect(result.contract.event_type).toBe(
      'https://google-adk-decision-ledger.example/v1',
    )
    expect(result.contract.decision_states).toEqual([
      'allowed',
      'refused',
      'confirmation_required',
      'confirmation_resolved',
      'stale_or_mismatched',
      'policy_error',
    ])

    expect(result.live_adk.allowed).toMatchObject({
      decision_state: 'allowed',
      tool_body_executed: true,
      function_call_events: 1,
      function_response_events: 1,
    })
    expect(result.live_adk.allowed.decision_record_hash).toMatch(/^sha256:[0-9a-f]{64}$/)
    expect(result.live_adk.allowed.outcome_record_hash).toMatch(/^sha256:[0-9a-f]{64}$/)

    expect(result.live_adk.refused).toMatchObject({
      decision_state: 'refused',
      outcome_record_hash: null,
      tool_body_executed: false,
      function_call_events: 1,
      function_response_events: 1,
    })
    expect(result.live_adk.refused.decision_record_hash).toMatch(/^sha256:[0-9a-f]{64}$/)

    expect(result.live_adk.policy_error).toMatchObject({
      decision_state: 'policy_error',
      outcome_record_hash: null,
      tool_body_executed: false,
      function_call_events: 1,
      function_response_events: 1,
    })
    expect(result.live_adk.policy_error.decision_record_hash).toMatch(
      /^sha256:[0-9a-f]{64}$/,
    )

    expect(result.proof).toMatchObject({
      allowed_execution_informed_by_decision: true,
      refused_tool_body_executed: false,
      policy_error_tool_body_executed: false,
      stale_mismatch_detected: true,
    })
    expect(result.confirmation).toMatchObject({
      fail_closed: true,
      binding_reasons: ['args_mismatch', 'confirmation_binding_mismatch'],
    })
    expect(result.confirmation.required.decision_state).toBe('confirmation_required')
    expect(result.confirmation.resolved.decision_state).toBe('confirmation_resolved')
    expect(result.confirmation.stale_or_mismatched.decision_state).toBe(
      'stale_or_mismatched',
    )
    expect(result.privacy).toEqual({
      public_records_hash_only: true,
      local_sidecars_keep_payloads: true,
      public_records_omit_private_phrase: true,
      public_records_omit_raw_principal: true,
    })
    expect(result.caveats.join(' ')).toContain('ToolConfirmation')
  }, 30000)

  it('keeps decision-ledger fixtures generated by the public builder', async () => {
    const fixtures = JSON.parse(
      await readFile(
        new URL(
          '../examples/google-adk-typescript/fixtures/decision-ledger-fixtures.json',
          import.meta.url,
        ),
        'utf8',
      ),
    ) as FixtureCorpus

    expect(fixtures.schema).toBe('atrib.google-adk.decision-ledger.fixtures.v1')
    expect(Object.keys(fixtures.entries)).toEqual([
      'allowed',
      'refused',
      'confirmation_required',
      'confirmation_resolved',
      'stale_or_mismatched',
      'policy_error',
    ])

    for (const entry of Object.values(fixtures.entries)) {
      expect(entry.schema).toBe(GOOGLE_ADK_DECISION_LEDGER_SCHEMA)
      expect(entry.decision_id).toMatch(/^sha256:[0-9a-f]{64}$/)
      expect(entry.canonical_args_digest).toMatch(/^sha256:[0-9a-f]{64}$/)
      expect(entry.authority.principal_hash).toMatch(/^sha256:[0-9a-f]{64}$/)
      expect(JSON.stringify(entry)).not.toContain('fixture@example.test')

      expect(
        buildDecisionLedgerEntry({
          decision_state: entry.decision_state,
          invocation_id: entry.invocation_id,
          session_id: entry.session_id,
          step: entry.step,
          tool_call_id: entry.tool_call_id,
          tool_name: entry.tool_name,
          canonical_args_digest: entry.canonical_args_digest,
          authority: entry.authority,
          policy: entry.policy,
          confirmation: entry.confirmation,
          model_rationale: entry.model_rationale.text,
          timestamp: entry.timestamp,
          parent_record_hashes: entry.parent_record_hashes,
          ...(entry.result_digest ? { result_digest: entry.result_digest } : {}),
        }),
      ).toEqual(entry)
    }
  })
})
