// SPDX-License-Identifier: Apache-2.0

/**
 * Generate spec §3.4.5 / §3.4.6 / §3.4.7 conformance corpus fixtures.
 *
 * Run with: pnpm --filter @atrib/log-dev exec tsx scripts/generate-conformance-3.4.5-7.ts
 *
 * Output:
 *   spec/conformance/3.4.5/cases/*.json + manifest.json (provenance trace)
 *   spec/conformance/3.4.6/cases/*.json + manifest.json (causal chain)
 *   spec/conformance/3.4.7/cases/*.json + manifest.json (creator activity-map)
 *
 * The three sections share helpers (makeRecord, hashing) so they are
 * generated by a single script. Each section's cases are scoped to its
 * spec-normative properties:
 *
 *   §3.4.5 (provenance trace): producer-claim ancestry walk (INFORMED_BY,
 *     ANNOTATES, REVISES). MUST NOT walk CHAIN_PRECEDES (structure-vs-
 *     claims invariant per §3.1).
 *
 *   §3.4.6 (causal chain): substrate-derived chain_root walk to session
 *     genesis. MUST NOT walk INFORMED_BY / ANNOTATES / REVISES (claims
 *     are not structure).
 *
 *   §3.4.7 (creator activity-map): windowed cross-session view. Default
 *     excludes intra-session edges (SESSION_PRECEDES, SESSION_PARALLEL).
 *     ?include_intra_session=true restores them.
 *
 * Seeds and timestamps are hardcoded so successive regenerations produce
 * byte-identical files.
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import {
  base64urlEncode,
  canonicalRecord,
  genesisChainRoot,
  getPublicKey,
  hexEncode,
  signRecord,
  type AtribRecord,
} from '@atrib/mcp'
import { sha256 } from '@noble/hashes/sha2.js'

const ALICE_SEED = new Uint8Array(32).fill(0x11)
const REFERENCE_TIME_MS = Date.UTC(2026, 0, 1, 0, 0, 0)

const HERE = dirname(fileURLToPath(import.meta.url))
const SPEC_ROOT = resolve(HERE, '../../..')

interface CaseOutput<TInput, TExpected> {
  name: string
  description: string
  input: TInput
  expected: TExpected
}

async function makeRecord(opts: {
  contextId: string
  chainRoot?: string
  timestamp: number
  contentId: string
  eventType?: string
  informedBy?: string[]
  annotates?: string
  revises?: string
}): Promise<AtribRecord> {
  const pub = await getPublicKey(ALICE_SEED)
  const ctx = opts.contextId
  // JCS sorts keys lexicographically. Object key order in this literal does
  // not affect signing (signRecord re-canonicalizes), but matching JCS order
  // here keeps the corpus diff-friendly.
  const record: Record<string, unknown> = {
    spec_version: 'atrib/1.0',
    ...(opts.annotates ? { annotates: opts.annotates } : {}),
    chain_root: opts.chainRoot ?? genesisChainRoot(ctx),
    content_id: opts.contentId,
    context_id: ctx,
    creator_key: base64urlEncode(pub),
    event_type: opts.eventType ?? 'https://atrib.dev/v1/types/tool_call',
    ...(opts.informedBy && opts.informedBy.length > 0 ? { informed_by: [...opts.informedBy].sort() } : {}),
    ...(opts.revises ? { revises: opts.revises } : {}),
    signature: '',
    timestamp: opts.timestamp,
  }
  return signRecord(record as AtribRecord, ALICE_SEED)
}

function hashOf(record: AtribRecord): string {
  return hexEncode(sha256(canonicalRecord(record)))
}

function writeCorpus(
  section: string,
  title: string,
  decisionLink: string,
  note: string,
  cases: CaseOutput<unknown, unknown>[],
) {
  const dir = join(SPEC_ROOT, 'spec', 'conformance', section, 'cases')
  mkdirSync(dir, { recursive: true })
  for (const c of cases) {
    writeFileSync(join(dir, `${c.name}.json`), JSON.stringify(c, null, 2) + '\n', 'utf8')
    console.log(`[${section}] wrote ${c.name}`)
  }
  const manifest = {
    spec_section: section,
    spec_title: title,
    decision_link: decisionLink,
    generated_at: REFERENCE_TIME_MS,
    generator: 'packages/log-dev/scripts/generate-conformance-3.4.5-7.ts',
    cases: cases.map((c) => ({ file: `cases/${c.name}.json`, name: c.name })),
    keys: { alice_pubkey: '' }, // Filled at end after we know the key.
    note,
  }
  writeFileSync(join(SPEC_ROOT, 'spec', 'conformance', section, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8')
  return manifest
}

// ────────────────────────────────────────────────────────────────────────
// §3.4.5 provenance trace
// ────────────────────────────────────────────────────────────────────────

interface TraceInput {
  records: AtribRecord[]
  start_record_index: number
  depth: number
  include_annotations: boolean
  include_revisions: boolean
}
interface TraceExpected {
  record_indexes_in_response: number[]
  truncated_by_depth: boolean
  truncated_by_count: boolean
}

async function buildTraceCases(): Promise<CaseOutput<TraceInput, TraceExpected>[]> {
  const ctx = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  const cases: CaseOutput<TraceInput, TraceExpected>[] = []

  // Case 1: linear informed_by chain. Three records where C is informed by B,
  // B is informed by A. Trace from C must return all three.
  {
    const a = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 1000,
      contentId: `sha256:${'a1'.padEnd(64, '0')}`,
    })
    const b = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 2000,
      contentId: `sha256:${'b1'.padEnd(64, '0')}`,
      informedBy: [`sha256:${hashOf(a)}`],
    })
    const c = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 3000,
      contentId: `sha256:${'c1'.padEnd(64, '0')}`,
      informedBy: [`sha256:${hashOf(b)}`],
    })
    cases.push({
      name: 'linear-informed-by-chain',
      description:
        'Three records linked by informed_by: C→B→A. Trace from C with default depth must surface the full ancestry: {A, B, C}. Records appear in the response regardless of order; the response set membership is the spec-normative property.',
      input: { records: [a, b, c], start_record_index: 2, depth: 5, include_annotations: true, include_revisions: true },
      expected: { record_indexes_in_response: [0, 1, 2], truncated_by_depth: false, truncated_by_count: false },
    })
  }

  // Case 2: structure-vs-claims invariant. A→B→C linked by chain_root only
  // (no informed_by/annotates/revises). Trace from C must return ONLY {C}
  // because chain_root edges (CHAIN_PRECEDES) MUST NOT be walked per §3.1.
  {
    const a = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 4000,
      contentId: `sha256:${'a2'.padEnd(64, '0')}`,
    })
    const b = await makeRecord({
      contextId: ctx,
      chainRoot: `sha256:${hashOf(a)}`,
      timestamp: REFERENCE_TIME_MS + 5000,
      contentId: `sha256:${'b2'.padEnd(64, '0')}`,
    })
    const c = await makeRecord({
      contextId: ctx,
      chainRoot: `sha256:${hashOf(b)}`,
      timestamp: REFERENCE_TIME_MS + 6000,
      contentId: `sha256:${'c2'.padEnd(64, '0')}`,
    })
    cases.push({
      name: 'chain-precedes-not-walked',
      description:
        'Three records linked by chain_root only (CHAIN_PRECEDES). Trace from C MUST return ONLY {C}, chain_root edges are substrate-derived structure per §3.2.4, not producer claims, and §3.4.5 forbids the trace walk from following them. Conflating the structural and claim layers violates the structure-vs-claims separation justifying §1.2.5 informed_by semantics.',
      input: { records: [a, b, c], start_record_index: 2, depth: 5, include_annotations: true, include_revisions: true },
      expected: { record_indexes_in_response: [2], truncated_by_depth: false, truncated_by_count: false },
    })
  }

  // Case 3: depth-1 truncates a 3-deep informed_by walk.
  {
    const a = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 7000,
      contentId: `sha256:${'a3'.padEnd(64, '0')}`,
    })
    const b = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 8000,
      contentId: `sha256:${'b3'.padEnd(64, '0')}`,
      informedBy: [`sha256:${hashOf(a)}`],
    })
    const c = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 9000,
      contentId: `sha256:${'c3'.padEnd(64, '0')}`,
      informedBy: [`sha256:${hashOf(b)}`],
    })
    cases.push({
      name: 'depth-limit-truncates',
      description:
        'Three-record informed_by chain (C→B→A). Trace from C with depth=1 must return {B, C} and set truncated_by_depth=true (B has an unwalked ancestor).',
      input: { records: [a, b, c], start_record_index: 2, depth: 1, include_annotations: true, include_revisions: true },
      expected: { record_indexes_in_response: [1, 2], truncated_by_depth: true, truncated_by_count: false },
    })
  }

  return cases
}

// ────────────────────────────────────────────────────────────────────────
// §3.4.6 causal chain
// ────────────────────────────────────────────────────────────────────────

interface ChainInput {
  records: AtribRecord[]
  start_record_index: number
  depth: number
}
interface ChainExpected {
  record_indexes_in_response: number[]
  truncated_by_depth: boolean
}

async function buildChainCases(): Promise<CaseOutput<ChainInput, ChainExpected>[]> {
  const ctx = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
  const cases: CaseOutput<ChainInput, ChainExpected>[] = []

  // Case 1: linear chain to genesis. A (genesis), B chained from A, C chained
  // from B. Chain from C returns all three; terminates at A's genesis.
  {
    const a = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 10000,
      contentId: `sha256:${'a4'.padEnd(64, '0')}`,
    })
    const b = await makeRecord({
      contextId: ctx,
      chainRoot: `sha256:${hashOf(a)}`,
      timestamp: REFERENCE_TIME_MS + 11000,
      contentId: `sha256:${'b4'.padEnd(64, '0')}`,
    })
    const c = await makeRecord({
      contextId: ctx,
      chainRoot: `sha256:${hashOf(b)}`,
      timestamp: REFERENCE_TIME_MS + 12000,
      contentId: `sha256:${'c4'.padEnd(64, '0')}`,
    })
    cases.push({
      name: 'linear-chain-to-genesis',
      description:
        'Three-record chain A → B → C in one context_id. Chain walk from C must return {A, B, C} and terminate at A (the session-genesis record where chain_root = SHA-256(context_id)). truncated_by_depth=false.',
      input: { records: [a, b, c], start_record_index: 2, depth: 5 },
      expected: { record_indexes_in_response: [0, 1, 2], truncated_by_depth: false },
    })
  }

  // Case 2: informed_by NOT walked. A linked to B via informed_by only.
  // Chain from A returns ONLY {A}, the chain walk ignores producer claims.
  {
    const a = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 13000,
      contentId: `sha256:${'a5'.padEnd(64, '0')}`,
    })
    const b = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 14000,
      contentId: `sha256:${'b5'.padEnd(64, '0')}`,
      informedBy: [`sha256:${hashOf(a)}`],
    })
    cases.push({
      name: 'informed-by-not-walked',
      description:
        'Two records: B is informed by A but B carries the genesis chain_root for its context_id. Chain walk from B MUST return ONLY {B}, informed_by is a producer claim, not substrate structure, and §3.4.6 forbids the chain walk from following producer claims. Symmetric counterpart to §3.4.5\'s chain-precedes-not-walked invariant.',
      input: { records: [a, b], start_record_index: 1, depth: 5 },
      expected: { record_indexes_in_response: [1], truncated_by_depth: false },
    })
  }

  // Case 3: depth-1 truncates a 3-record chain.
  {
    const a = await makeRecord({
      contextId: ctx,
      timestamp: REFERENCE_TIME_MS + 15000,
      contentId: `sha256:${'a6'.padEnd(64, '0')}`,
    })
    const b = await makeRecord({
      contextId: ctx,
      chainRoot: `sha256:${hashOf(a)}`,
      timestamp: REFERENCE_TIME_MS + 16000,
      contentId: `sha256:${'b6'.padEnd(64, '0')}`,
    })
    const c = await makeRecord({
      contextId: ctx,
      chainRoot: `sha256:${hashOf(b)}`,
      timestamp: REFERENCE_TIME_MS + 17000,
      contentId: `sha256:${'c6'.padEnd(64, '0')}`,
    })
    cases.push({
      name: 'depth-limit-truncates',
      description:
        'Three-record chain A → B → C. Chain walk from C with depth=1 must return {B, C} and set truncated_by_depth=true (B has an unwalked predecessor that is not the genesis).',
      input: { records: [a, b, c], start_record_index: 2, depth: 1 },
      expected: { record_indexes_in_response: [1, 2], truncated_by_depth: true },
    })
  }

  return cases
}

// ────────────────────────────────────────────────────────────────────────
// §3.4.7 creator activity-map
// ────────────────────────────────────────────────────────────────────────

interface CreatorGraphInput {
  records: AtribRecord[]
  include_intra_session: boolean
}
interface CreatorGraphExpected {
  record_count: number
  edge_types_excluded: string[]   // edge types that MUST NOT appear in graph.edges
  edge_types_present_at_least_one: string[]  // edge types that MUST appear at least once
  intra_session_edges_filtered: boolean
}

async function buildCreatorGraphCases(): Promise<CaseOutput<CreatorGraphInput, CreatorGraphExpected>[]> {
  const ctxA = 'cccccccccccccccccccccccccccccccc'
  const ctxB = 'dddddddddddddddddddddddddddddddd'
  const cases: CaseOutput<CreatorGraphInput, CreatorGraphExpected>[] = []

  // Cross-session fixture: two records in ctxA + two records in ctxB, with a
  // cross-context informed_by edge from ctxB to ctxA. Both contexts have
  // multiple unchained records so they would generate SESSION_PRECEDES /
  // SESSION_PARALLEL if not filtered.
  const a0 = await makeRecord({
    contextId: ctxA,
    timestamp: REFERENCE_TIME_MS + 20000,
    contentId: `sha256:${'a7'.padEnd(64, '0')}`,
  })
  const a1 = await makeRecord({
    contextId: ctxA,
    timestamp: REFERENCE_TIME_MS + 21000,
    contentId: `sha256:${'a8'.padEnd(64, '0')}`,
  })
  const b0 = await makeRecord({
    contextId: ctxB,
    timestamp: REFERENCE_TIME_MS + 22000,
    contentId: `sha256:${'b7'.padEnd(64, '0')}`,
    informedBy: [`sha256:${hashOf(a0)}`],
  })
  const b1 = await makeRecord({
    contextId: ctxB,
    timestamp: REFERENCE_TIME_MS + 23000,
    contentId: `sha256:${'b8'.padEnd(64, '0')}`,
  })
  const records = [a0, a1, b0, b1]

  // Case 1: default include_intra_session=false → no SESSION_PRECEDES /
  // SESSION_PARALLEL in response, but the cross-session INFORMED_BY edge
  // is preserved. intra_session_edges_filtered must be true.
  cases.push({
    name: 'cross-session-only-by-default',
    description:
      'Four records by one creator across two context_ids, with an INFORMED_BY edge from ctxB to ctxA. The default response (include_intra_session=false) MUST exclude SESSION_PRECEDES and SESSION_PARALLEL edges (intra-session) AND MUST include INFORMED_BY (cross-session). intra_session_edges_filtered MUST be true.',
    input: { records, include_intra_session: false },
    expected: {
      record_count: 4,
      edge_types_excluded: ['SESSION_PRECEDES', 'SESSION_PARALLEL'],
      edge_types_present_at_least_one: ['INFORMED_BY'],
      intra_session_edges_filtered: true,
    },
  })

  // Case 2: include_intra_session=true restores intra-session edges. The
  // cross-context INFORMED_BY edge is still present, so we still expect at
  // least one INFORMED_BY. intra_session_edges_filtered must flip to false.
  cases.push({
    name: 'include-intra-session-true-restores',
    description:
      'Same fixture, include_intra_session=true. The response MUST include intra-session edges (SESSION_PRECEDES at least, between the two unchained records in each context_id) alongside cross-session edges. intra_session_edges_filtered MUST be false.',
    input: { records, include_intra_session: true },
    expected: {
      record_count: 4,
      edge_types_excluded: [],
      edge_types_present_at_least_one: ['INFORMED_BY', 'SESSION_PRECEDES'],
      intra_session_edges_filtered: false,
    },
  })

  return cases
}

// ────────────────────────────────────────────────────────────────────────
// Driver
// ────────────────────────────────────────────────────────────────────────

async function main() {
  const traceCases = await buildTraceCases()
  const chainCases = await buildChainCases()
  const creatorCases = await buildCreatorGraphCases()

  const alicePub = base64urlEncode(await getPublicKey(ALICE_SEED))

  const traceManifest = writeCorpus(
    '3.4.5',
    'Provenance trace (producer-claim ancestry walk)',
    'D068 + §3.4.5',
    'Provenance trace walks producer-claimed ancestry edges only (INFORMED_BY, ANNOTATES, REVISES). The structure-vs-claims invariant (§3.1) requires that CHAIN_PRECEDES NOT be walked. Cases enumerate the load-bearing properties: multi-hop walk, the structural-edge prohibition, and depth truncation.',
    traceCases as unknown as CaseOutput<unknown, unknown>[],
  )
  traceManifest.keys.alice_pubkey = alicePub
  writeFileSync(join(SPEC_ROOT, 'spec', 'conformance', '3.4.5', 'manifest.json'), JSON.stringify(traceManifest, null, 2) + '\n', 'utf8')

  const chainManifest = writeCorpus(
    '3.4.6',
    'Causal chain (substrate-derived chain_root walk)',
    'D068 + §3.4.6',
    'Causal chain walks chain_root linkage only, the substrate-derived structural ordering. Symmetric counterpart to §3.4.5: producer claims (INFORMED_BY, ANNOTATES, REVISES) MUST NOT be walked. Cases enumerate linear-walk-to-genesis, the producer-claim prohibition, and depth truncation.',
    chainCases as unknown as CaseOutput<unknown, unknown>[],
  )
  chainManifest.keys.alice_pubkey = alicePub
  writeFileSync(join(SPEC_ROOT, 'spec', 'conformance', '3.4.6', 'manifest.json'), JSON.stringify(chainManifest, null, 2) + '\n', 'utf8')

  const creatorManifest = writeCorpus(
    '3.4.7',
    'Creator activity-map (windowed cross-session view)',
    '§3.4.7',
    "By default, the creator activity-map excludes intra-session edges (SESSION_PRECEDES, SESSION_PARALLEL) so the cross-session signal isn't swamped. ?include_intra_session=true restores the full edge set. Both modes preserve cross-session edges (CROSS_SESSION, INFORMED_BY across context_ids, PROVENANCE_OF, ANNOTATES, REVISES) and CHAIN_PRECEDES.",
    creatorCases as unknown as CaseOutput<unknown, unknown>[],
  )
  creatorManifest.keys.alice_pubkey = alicePub
  writeFileSync(join(SPEC_ROOT, 'spec', 'conformance', '3.4.7', 'manifest.json'), JSON.stringify(creatorManifest, null, 2) + '\n', 'utf8')

  console.log(`\nGenerated ${traceCases.length + chainCases.length + creatorCases.length} cases across 3 corpora`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
