// SPDX-License-Identifier: Apache-2.0

/**
 * dev.atrib/attribution MCP-extension conformance (D141 / spec §1.5.4.1).
 *
 * Loads each case from spec/conformance/mcp-extension/cases/ (the committed
 * vectors, never the generator) and asserts the expected invariants against
 * the PRODUCTION implementation of the extension contract defined in
 * docs/extensions/dev.atrib-attribution/v0.1.md:
 *
 *   - capability settings validation + the SEP-2133 reserved-prefix rule
 *   - receipt opt-in gating with byte-identical legacy fallback
 *   - Ladder 1 (inbound propagation token) precedence
 *   - Ladder 2 (context identity) precedence
 *   - receipt integrity against real Ed25519-signed records
 *   - the §5.8 degradation contract under forced failures
 *
 * The extension implementation lives in @atrib/mcp's extension-attribution
 * module (which composes the same primitives as packages/mcp/src/context.ts:
 * decodeToken, parseTracestateAtrib, extractTraceId, writeOutboundContext),
 * so the legacy rungs are exercised through the production implementation
 * with the extension rung layered on top exactly as §1.5.4.1 specifies. This
 * file previously carried its own reference implementation; it now consumes
 * the library exports directly so two implementations cannot drift.
 *
 * NOTE: the extension module is imported by relative path into the @atrib/mcp
 * source until the package-root export lands (returned as an index.ts edit
 * with the D141 producer tranche); flip to `from '@atrib/mcp'` at that point.
 * The corpus is regenerated by
 * packages/log-dev/scripts/generate-conformance-mcp-extension.ts.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import canonicalize from 'canonicalize'
import {
  base64urlEncode,
  canonicalRecord,
  encodeToken,
  extractTraceId,
  genesisChainRoot,
  hexEncode,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'
import {
  ATTRIBUTION_EXTENSION_ID,
  ATTRIBUTION_LOG_SUBMISSION_STATUSES,
  buildAttributionReceipt,
  extendResultWithAttribution,
  resolveContextIdentity,
  resolveInboundToken,
  validateAttributionSettings,
  validateExtensionIdentifier,
  verifyAttributionReceipt,
} from '../../mcp/src/extension-attribution.js'
import type {
  AttributionContextResolution,
  AttributionContextSource,
  AttributionResultBlock,
  AttributionSettingsValidation,
  AttributionTokenResolution,
  AttributionTokenSource,
} from '../../mcp/src/extension-attribution.js'

const CORPUS = join(__dirname, '../../../spec/conformance/mcp-extension/cases')

const EXT_ID = ATTRIBUTION_EXTENSION_ID
const LOG_SUBMISSION_STATUSES = new Set<string>(ATTRIBUTION_LOG_SUBMISSION_STATUSES)

interface CaseFile {
  name: string
  spec_section: string
  extension: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

function jcsSha256Hex(value: unknown): string {
  const json = canonicalize(value)
  if (json === undefined) throw new Error('canonicalization produced undefined')
  return hexEncode(sha256(new TextEncoder().encode(json)))
}

// ═══ Family 1: capability ═══════════════════════════════════════════════

describe('mcp-extension conformance: capability', () => {
  it('server-declaration-valid: full server settings object accepted', () => {
    const c = loadCase('capability--server-declaration-valid')
    const expected = c.expected as { valid: boolean; declared: boolean; negotiated_version: string }
    const v = validateAttributionSettings(c.input.settings)
    expect(v.declared).toBe(expected.declared)
    expect(v.negotiatedVersion).toBe(expected.negotiated_version)
    expect(v.ignoredSettingsFields).toEqual([])
  })

  it('client-declaration-valid: accept negotiation recognized', () => {
    const c = loadCase('capability--client-declaration-valid')
    const expected = c.expected as {
      declared: boolean
      negotiated_version: string
      effective_accept: string[]
      accept_record: boolean
    }
    const v = validateAttributionSettings(c.input.settings)
    expect(v.declared).toBe(expected.declared)
    expect(v.negotiatedVersion).toBe(expected.negotiated_version)
    expect(v.effectiveAccept).toEqual(expected.effective_accept)
    expect(v.effectiveAccept.includes('record')).toBe(expected.accept_record)
  })

  it('unknown-settings-fields-ignored: forward compatibility', () => {
    const c = loadCase('capability--unknown-settings-fields-ignored')
    const expected = c.expected as {
      declared: boolean
      negotiated_version: string
      effective_accept: string[]
      ignored_settings_fields: string[]
      ignored_accept_values: string[]
    }
    const v = validateAttributionSettings(c.input.settings)
    expect(v.declared).toBe(expected.declared)
    expect(v.negotiatedVersion).toBe(expected.negotiated_version)
    expect(v.effectiveAccept).toEqual(expected.effective_accept)
    expect(v.ignoredSettingsFields).toEqual(expected.ignored_settings_fields)
    expect(v.ignoredAcceptValues).toEqual(expected.ignored_accept_values)
  })

  it('missing-version-rejected: treated as undeclared, never an error', () => {
    const c = loadCase('capability--missing-version-rejected')
    const expected = c.expected as { declared: boolean; error_raised: boolean }
    let raised = false
    let v: AttributionSettingsValidation | undefined
    try {
      v = validateAttributionSettings(c.input.settings)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(v?.declared).toBe(expected.declared)
  })

  it('reserved-prefix-rejected: SEP-2133 identifier grammar', () => {
    const c = loadCase('capability--reserved-prefix-rejected')
    const identifiers = c.input.identifiers as string[]
    const results = c.expected.results as { identifier: string; valid: boolean }[]
    expect(identifiers.length).toBe(results.length)
    for (const r of results) {
      expect(validateExtensionIdentifier(r.identifier), r.identifier).toBe(r.valid)
    }
  })
})

// ═══ Family 2: gating ═══════════════════════════════════════════════════

function runGatedResult(c: CaseFile): Record<string, unknown> {
  const record = c.input.signed_record as AtribRecord
  const result: Record<string, unknown> = { content: [{ type: 'text', text: 'ok' }] }
  extendResultWithAttribution(result, c.input.request_meta, () => record)
  return result
}

describe('mcp-extension conformance: gating', () => {
  it('declared-receipt-present: prefixed block alongside byte-identical legacy keys', async () => {
    const c = loadCase('gating--declared-receipt-present')
    const expected = c.expected as {
      extension_block_present: boolean
      result_meta: Record<string, unknown>
      legacy_keys: Record<string, string>
    }
    const result = runGatedResult(c)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    expect(meta).toEqual(expected.result_meta)
    expect(meta.atrib).toBe(expected.legacy_keys.atrib)
    expect(meta.tracestate).toBe(expected.legacy_keys.tracestate)
    expect(meta['X-Atrib-Chain']).toBe(expected.legacy_keys['X-Atrib-Chain'])

    // The attached record body is a real signed record (Tier-3 check).
    const block = meta[EXT_ID] as AttributionResultBlock
    expect(block.record).toBeDefined()
    expect(await verifyRecordSignature(block.record as AtribRecord)).toBe(true)
  })

  it('declared-token-only: receipt present, record body omitted', () => {
    const c = loadCase('gating--declared-token-only')
    const expected = c.expected as {
      extension_block_present: boolean
      record_body_present: boolean
      result_meta: Record<string, unknown>
    }
    const result = runGatedResult(c)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    const block = meta[EXT_ID] as Record<string, unknown>
    expect('record' in block).toBe(expected.record_body_present)
    expect(meta).toEqual(expected.result_meta)
  })

  it('undeclared-legacy-only: byte-identical to pre-extension writeOutboundContext output', () => {
    const c = loadCase('gating--undeclared-legacy-only')
    const expected = c.expected as {
      extension_block_present: boolean
      result_meta: Record<string, unknown>
      result_meta_jcs_sha256_hex: string
    }
    const result = runGatedResult(c)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    expect(meta).toEqual(expected.result_meta)
    // Byte-identity pinned by JCS hash against real writeOutboundContext output.
    expect(jcsSha256Hex(meta)).toBe(expected.result_meta_jcs_sha256_hex)
  })

  it('malformed-clientcapabilities-undeclared: treated as undeclared, no error', () => {
    const c = loadCase('gating--malformed-clientcapabilities-undeclared')
    const expected = c.expected as {
      extension_block_present: boolean
      error_raised: boolean
      result_meta: Record<string, unknown>
    }
    let raised = false
    let result: Record<string, unknown> = {}
    try {
      result = runGatedResult(c)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    expect(meta).toEqual(expected.result_meta)
  })
})

// ═══ Family 3: token (Ladder 1) ═════════════════════════════════════════

describe('mcp-extension conformance: token precedence (Ladder 1)', () => {
  interface TokenExpected {
    resolved_source: AttributionTokenSource
    resolved_record_hash_hex?: string
    resolved_creator_key?: string
    conflict_warning?: boolean
    error_raised?: boolean
  }

  function runTokenCase(name: string): void {
    const c = loadCase(name)
    const expected = c.expected as unknown as TokenExpected
    let raised = false
    let resolution: AttributionTokenResolution | undefined
    try {
      resolution = resolveInboundToken(c.input.request_meta)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised ?? false)
    expect(resolution).toBeDefined()
    expect(resolution!.source).toBe(expected.resolved_source)
    if (expected.resolved_record_hash_hex !== undefined) {
      expect(resolution!.recordHashHex).toBe(expected.resolved_record_hash_hex)
    }
    if (expected.resolved_creator_key !== undefined) {
      expect(resolution!.creatorKey).toBe(expected.resolved_creator_key)
    }
    if (expected.conflict_warning !== undefined) {
      expect(resolution!.conflictWarning).toBe(expected.conflict_warning)
    }
  }

  it('extension-key-wins: four conflicting carriers, extension wins with warning', () => {
    runTokenCase('token--extension-key-wins')
  })

  it('malformed-extension-falls-through: lenient parse to _meta.atrib', () => {
    runTokenCase('token--malformed-extension-falls-through')
  })

  it('meta-atrib-over-tracestate: legacy order preserved beneath the extension rung', () => {
    runTokenCase('token--meta-atrib-over-tracestate')
  })

  it('tracestate-over-x-atrib-chain: tracestate beats the fallback header', () => {
    runTokenCase('token--tracestate-over-x-atrib-chain')
  })

  it('x-atrib-chain-fallback: last rung resolves alone', () => {
    runTokenCase('token--x-atrib-chain-fallback')
  })

  it('all-carriers-stripped: chain resolution continues per D067 / §1.2.3.1', () => {
    const c = loadCase('token--all-carriers-stripped')
    const expected = c.expected as {
      resolved_source: null
      inbound_token_resolved: boolean
      synthetic_genesis_chain_root_for_traceparent_context: string
    }
    const resolution = resolveInboundToken(c.input.request_meta)
    expect(resolution.source).toBe(expected.resolved_source)
    expect(resolution.recordHashHex !== undefined).toBe(expected.inbound_token_resolved)
    // The genesis chain_root the D067 ladder bottoms out at is reproducible.
    const meta = c.input.request_meta as Record<string, unknown>
    const traceId = extractTraceId(meta.traceparent as string)
    expect(traceId).toBeDefined()
    expect(genesisChainRoot(traceId as string)).toBe(
      expected.synthetic_genesis_chain_root_for_traceparent_context,
    )
  })
})

// ═══ Family 4: context (Ladder 2) ═══════════════════════════════════════

describe('mcp-extension conformance: context-identity precedence (Ladder 2)', () => {
  interface ContextExpected {
    resolved_context_id: string | null
    resolved_source: AttributionContextSource
    mismatch_warning?: boolean
    error_raised?: boolean
  }

  function runContextCase(name: string): AttributionContextResolution {
    const c = loadCase(name)
    const expected = c.expected as unknown as ContextExpected
    let raised = false
    let resolution: AttributionContextResolution | undefined
    try {
      resolution = resolveContextIdentity(c.input.explicit_context_id_argument, c.input.request_meta)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised ?? false)
    expect(resolution).toBeDefined()
    expect(resolution!.contextId ?? null).toBe(expected.resolved_context_id)
    expect(resolution!.source).toBe(expected.resolved_source)
    if (expected.mismatch_warning !== undefined) {
      expect(resolution!.mismatchWarning).toBe(expected.mismatch_warning)
    }
    return resolution!
  }

  it('explicit-argument-wins: application intent beats transport metadata', () => {
    runContextCase('context--explicit-argument-wins')
  })

  it('extension-over-traceparent: extension block beats trace-id with warning', () => {
    runContextCase('context--extension-over-traceparent')
  })

  it('invalid-extension-hex-falls-through: non-32-hex ignored, never an error', () => {
    runContextCase('context--invalid-extension-hex-falls-through')
  })

  it('no-carrier-env-fallthrough: transport yields nothing, D078/D083 applies producer-side', () => {
    runContextCase('context--no-carrier-env-fallthrough')
  })

  it('unknown-fields-ignored: extra block fields have no record-field effect', () => {
    const c = loadCase('context--unknown-fields-ignored')
    const expected = c.expected as {
      resolved_record_hash_hex: string
      ignored_fields: string[]
      record_field_effects: string[]
    }
    runContextCase('context--unknown-fields-ignored')

    // Both defined fields still resolve; everything else is ignored.
    const meta = c.input.request_meta as Record<string, unknown>
    const tokenResolution = resolveInboundToken(meta)
    expect(tokenResolution.source).toBe('extension')
    expect(tokenResolution.recordHashHex).toBe(expected.resolved_record_hash_hex)

    const block = meta[EXT_ID] as Record<string, unknown>
    const definedFields = new Set(['token', 'context_id'])
    const ignored = Object.keys(block)
      .filter((k) => !definedFields.has(k))
      .sort()
    expect(ignored).toEqual(expected.ignored_fields)
    // v0.1 maps exactly one block field onto a signed-record field.
    expect(expected.record_field_effects).toEqual(['context_id'])
    expect(expected.ignored_fields).toContain('session_token')
    expect(expected.ignored_fields).toContain('provenance_token')
  })
})

// ═══ Family 5: receipt ══════════════════════════════════════════════════

describe('mcp-extension conformance: receipt integrity', () => {
  it('consistent: receipt fields recompute from the real signed record', async () => {
    const c = loadCase('receipt--consistent')
    const block = c.input.result_block as unknown as AttributionResultBlock
    const expected = c.expected as {
      receipt_valid: boolean
      token: string
      record_hash: string
      creator_key: string
      context_id: string
      chain_root: string
      args_hash_recomputes_from_tool_args: boolean
      record_signature_verifies: boolean
    }
    const record = block.record as AtribRecord

    // Receipt block is internally consistent per the production verifier.
    expect(verifyAttributionReceipt(block).valid).toBe(expected.receipt_valid)

    // The production builder reproduces the pinned block from the record.
    expect(buildAttributionReceipt(record, { includeRecord: true })).toEqual(block)

    // Every receipt field recomputes from the record's canonical bytes.
    expect(block.token).toBe(encodeToken(record))
    expect(block.token).toBe(expected.token)
    expect(`sha256:${hexEncode(sha256(canonicalRecord(record)))}`).toBe(expected.record_hash)
    expect(block.receipt.record_hash).toBe(expected.record_hash)
    expect(record.creator_key).toBe(expected.creator_key)
    expect(record.context_id).toBe(expected.context_id)
    expect(record.chain_root).toBe(expected.chain_root)
    expect(genesisChainRoot(record.context_id)).toBe(expected.chain_root)

    // args_hash is a real §8.3 plain-sha256 commitment to the pinned args.
    const recomputedArgsHash = `sha256:${jcsSha256Hex(c.input.tool_args)}`
    expect(recomputedArgsHash === record.args_hash).toBe(expected.args_hash_recomputes_from_tool_args)

    // Tier-3: the attached record's signature verifies independently.
    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_verifies)
  })

  it('hash-mismatch-flagged: mismatched receipt discarded, tool result untouched', () => {
    const c = loadCase('receipt--hash-mismatch-flagged')
    const block = c.input.result_block as unknown as AttributionResultBlock
    const expected = c.expected as {
      receipt_valid: boolean
      mismatched_fields: string[]
      attached_record_hash: string
      claimed_record_hash: string
      tool_result_invalidated: boolean
    }
    const verdict = verifyAttributionReceipt(block)
    expect(verdict.valid).toBe(expected.receipt_valid)
    expect(verdict.mismatched).toEqual(expected.mismatched_fields)

    // Both hashes are real: the attached record recomputes to one, the
    // receipt claims the other.
    const record = block.record as AtribRecord
    expect(`sha256:${hexEncode(sha256(canonicalRecord(record)))}`).toBe(expected.attached_record_hash)
    expect(block.receipt.record_hash).toBe(expected.claimed_record_hash)
    expect(expected.tool_result_invalidated).toBe(false)
  })

  it('log-submission-nonblocking: queued receipt valid before submission settles', () => {
    const c = loadCase('receipt--log-submission-nonblocking')
    const block = c.input.result_block as unknown as AttributionResultBlock
    const expected = c.expected as {
      receipt_valid: boolean
      log_submission: string
      allowed_statuses: string[]
      proof_bundle_required: boolean
      awaiting_submission_forbidden: boolean
    }
    // Valid without any record body, proof bundle, or settled submission.
    expect(verifyAttributionReceipt(block).valid).toBe(expected.receipt_valid)
    expect(block.record).toBeUndefined()
    expect(block.receipt.log_submission).toBe(expected.log_submission)
    expect([...LOG_SUBMISSION_STATUSES].sort()).toEqual([...expected.allowed_statuses].sort())
    for (const status of expected.allowed_statuses) {
      expect(LOG_SUBMISSION_STATUSES.has(status)).toBe(true)
    }
    expect(expected.proof_bundle_required).toBe(false)
    expect(expected.awaiting_submission_forbidden).toBe(true)
  })
})

// ═══ Family 6: degradation ══════════════════════════════════════════════

describe('mcp-extension conformance: degradation (§5.8)', () => {
  it('signing-failure-passthrough: result byte-identical, no error', () => {
    const c = loadCase('degradation--signing-failure-passthrough')
    const expected = c.expected as {
      result_jcs_sha256_hex: string
      extension_block_present: boolean
      error_raised: boolean
    }
    const result = structuredClone(c.input.tool_result) as Record<string, unknown>
    let raised = false
    try {
      extendResultWithAttribution(result, c.input.request_meta, () => {
        throw new Error('forced signing failure')
      })
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(result._meta).toBeUndefined()
    expect(jcsSha256Hex(result)).toBe(expected.result_jcs_sha256_hex)
    expect(expected.extension_block_present).toBe(false)
  })

  it('capability-read-failure-passthrough: throwing capability read swallowed', () => {
    const c = loadCase('degradation--capability-read-failure-passthrough')
    const expected = c.expected as {
      result_jcs_sha256_hex: string
      extension_block_present: boolean
      error_raised: boolean
    }
    const result = structuredClone(c.input.tool_result) as Record<string, unknown>
    // A signable record exists; the failure is injected at capability read.
    const dummyRecord: AtribRecord = {
      spec_version: 'atrib/1.0',
      content_id: 'sha256:' + '00'.repeat(32),
      creator_key: base64urlEncode(new Uint8Array(32)),
      chain_root: genesisChainRoot('0'.repeat(31) + '1'),
      event_type: 'https://atrib.dev/v1/types/tool_call',
      context_id: '0'.repeat(31) + '1',
      timestamp: 0,
      signature: '',
    }
    const throwingMeta = new Proxy(
      {},
      {
        get(): never {
          throw new Error('forced capability-read failure')
        },
        has(): never {
          throw new Error('forced capability-read failure')
        },
      },
    )
    let raised = false
    try {
      extendResultWithAttribution(result, throwingMeta, () => dummyRecord)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(result._meta).toBeUndefined()
    expect(jcsSha256Hex(result)).toBe(expected.result_jcs_sha256_hex)
    expect(expected.extension_block_present).toBe(false)
  })

  it('missing-meta-never-blocks: total _meta loss, both ladders resolve to nothing', () => {
    const c = loadCase('degradation--missing-meta-never-blocks')
    const expected = c.expected as {
      inbound_token_resolved: boolean
      resolved_context_id: string | null
      tool_call_proceeds: boolean
      error_raised: boolean
    }
    const params = c.input.request_params as Record<string, unknown>
    expect(params._meta).toBeUndefined()
    let raised = false
    let proceeds = false
    try {
      const tokenResolution = resolveInboundToken(params._meta)
      const contextResolution = resolveContextIdentity(undefined, params._meta)
      expect(tokenResolution.recordHashHex !== undefined).toBe(expected.inbound_token_resolved)
      expect(contextResolution.contextId ?? null).toBe(expected.resolved_context_id)
      proceeds = true
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(proceeds).toBe(expected.tool_call_proceeds)
  })
})
