// SPDX-License-Identifier: Apache-2.0

/**
 * dev.atrib/attribution MCP-extension conformance (P049 / spec §1.5.4).
 *
 * Loads each case from spec/conformance/mcp-extension/cases/ (the committed
 * vectors, never the generator) and asserts the expected invariants against
 * a reference implementation of the extension contract defined in
 * docs/extensions/dev.atrib-attribution/v0.1.md:
 *
 *   - capability settings validation + the SEP-2133 reserved-prefix rule
 *   - receipt opt-in gating with byte-identical legacy fallback
 *   - Ladder 1 (inbound propagation token) precedence
 *   - Ladder 2 (context identity) precedence
 *   - receipt integrity against real Ed25519-signed records
 *   - the §5.8 degradation contract under forced failures
 *
 * The reference resolution reuses the same primitives as
 * packages/mcp/src/context.ts (decodeToken, parseTracestateAtrib,
 * extractTraceId, writeOutboundContext) so the legacy rungs are exercised
 * through the production implementation, with the extension rung layered
 * on top exactly as §1.5.4 specifies. The corpus is regenerated by
 * packages/log-dev/scripts/generate-conformance-mcp-extension.ts.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import canonicalize from 'canonicalize'
import {
  EVENT_TYPE_SHORT_TO_URI,
  base64urlEncode,
  canonicalRecord,
  decodeToken,
  encodeToken,
  extractTraceId,
  genesisChainRoot,
  hexEncode,
  parseTracestateAtrib,
  sha256,
  verifyRecord as verifyRecordSignature,
  writeOutboundContext,
  type AtribRecord,
} from '@atrib/mcp'

const CORPUS = join(__dirname, '../../../spec/conformance/mcp-extension/cases')

const EXT_ID = 'dev.atrib/attribution'
const CLIENT_CAPABILITIES_META_KEY = 'io.modelcontextprotocol/clientCapabilities'
const RESERVED_PREFIX_LABELS = new Set(['mcp', 'modelcontextprotocol'])
const KNOWN_SETTINGS_FIELDS = new Set([
  'version',
  'accept',
  'signs',
  'receipts',
  'disclosure',
  'creator_key',
  'logs',
  'directory',
])
const KNOWN_ACCEPT_VALUES = new Set(['token', 'record'])
const LOG_SUBMISSION_STATUSES = new Set(['queued', 'submitted', 'disabled', 'failed'])
const HEX32 = /^[0-9a-f]{32}$/

interface CaseFile {
  name: string
  spec_section: string
  extension: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

function jcsSha256Hex(value: unknown): string {
  const json = canonicalize(value)
  if (json === undefined) throw new Error('canonicalization produced undefined')
  return hexEncode(sha256(new TextEncoder().encode(json)))
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

// ─── Reference implementation: extension spec §3 (identifier grammar) ──

function validateExtensionIdentifier(identifier: string): boolean {
  const parts = identifier.split('/')
  if (parts.length !== 2) return false
  const [prefix, name] = parts
  if (!prefix || !name) return false
  const labels = prefix.split('.')
  if (labels.length < 2) return false
  for (const label of labels) {
    if (!/^[a-z0-9-]+$/.test(label)) return false
    if (RESERVED_PREFIX_LABELS.has(label)) return false
  }
  return /^[a-z0-9-]+$/.test(name)
}

// ─── Reference implementation: extension spec §4 (settings validation) ─

interface SettingsValidation {
  declared: boolean
  negotiatedVersion?: string
  effectiveAccept: string[]
  ignoredSettingsFields: string[]
  ignoredAcceptValues: string[]
}

function validateSettings(settings: unknown): SettingsValidation {
  const undeclared: SettingsValidation = {
    declared: false,
    effectiveAccept: ['token'],
    ignoredSettingsFields: [],
    ignoredAcceptValues: [],
  }
  if (!isPlainObject(settings)) return undeclared
  const version = settings.version
  if (typeof version !== 'string' || version.length === 0) return undeclared

  const ignoredSettingsFields = Object.keys(settings)
    .filter((k) => !KNOWN_SETTINGS_FIELDS.has(k))
    .sort()

  const ignoredAcceptValues: string[] = []
  let effectiveAccept: string[] = ['token']
  if (Array.isArray(settings.accept)) {
    const recognized = settings.accept.filter((v): v is string => {
      if (typeof v === 'string' && KNOWN_ACCEPT_VALUES.has(v)) return true
      if (typeof v === 'string') ignoredAcceptValues.push(v)
      return false
    })
    if (recognized.length > 0) effectiveAccept = recognized
  }

  return {
    declared: true,
    negotiatedVersion: version,
    effectiveAccept,
    ignoredSettingsFields,
    ignoredAcceptValues,
  }
}

/** Extension spec §6.1: per-request client declaration detection. */
function detectClientDeclaration(meta: unknown): SettingsValidation {
  if (!isPlainObject(meta)) return validateSettings(undefined)
  const caps = meta[CLIENT_CAPABILITIES_META_KEY]
  if (!isPlainObject(caps)) return validateSettings(undefined)
  const extensions = caps.extensions
  if (!isPlainObject(extensions)) return validateSettings(undefined)
  return validateSettings(extensions[EXT_ID])
}

// ─── Reference implementation: extension spec §5.2 (Ladder 1) ──────────

type TokenSource = 'extension' | 'meta-atrib' | 'tracestate' | 'x-atrib-chain' | null

interface TokenResolution {
  source: TokenSource
  recordHashHex?: string
  creatorKey?: string
  conflictWarning: boolean
}

function decodeCarrier(value: unknown): { hashHex: string; key: string } | null {
  if (typeof value !== 'string' || value.length === 0) return null
  const decoded = decodeToken(value)
  if (!decoded) return null
  return { hashHex: hexEncode(decoded.recordHash), key: base64urlEncode(decoded.creatorKey) }
}

function resolveInboundToken(meta: unknown): TokenResolution {
  const m = isPlainObject(meta) ? meta : {}

  // Legacy rungs, in §1.5.4 order, via the production parsers.
  const legacy: { source: Exclude<TokenSource, 'extension' | null>; hit: { hashHex: string; key: string } }[] = []
  const metaAtrib = decodeCarrier(m.atrib)
  if (metaAtrib) legacy.push({ source: 'meta-atrib', hit: metaAtrib })
  if (typeof m.tracestate === 'string') {
    const entry = parseTracestateAtrib(m.tracestate)
    const decoded = entry ? decodeCarrier(entry) : null
    if (decoded) legacy.push({ source: 'tracestate', hit: decoded })
  }
  const xChain = decodeCarrier(m['X-Atrib-Chain'] ?? m['x-atrib-chain'])
  if (xChain) legacy.push({ source: 'x-atrib-chain', hit: xChain })

  // Extension rung on top: lenient parse, falls through when malformed.
  const block = m[EXT_ID]
  if (isPlainObject(block)) {
    const extension = decodeCarrier(block.token)
    if (extension) {
      const conflictWarning = legacy.some((l) => l.hit.hashHex !== extension.hashHex)
      return {
        source: 'extension',
        recordHashHex: extension.hashHex,
        creatorKey: extension.key,
        conflictWarning,
      }
    }
  }

  const first = legacy[0]
  if (first) {
    return {
      source: first.source,
      recordHashHex: first.hit.hashHex,
      creatorKey: first.hit.key,
      conflictWarning: false,
    }
  }
  return { source: null, conflictWarning: false }
}

// ─── Reference implementation: extension spec §5.3 (Ladder 2) ──────────

type ContextSource = 'argument' | 'extension' | 'traceparent' | 'env-registry-fallthrough'

interface ContextResolution {
  contextId?: string
  source: ContextSource
  mismatchWarning: boolean
}

function resolveContextIdentity(explicitArgument: unknown, meta: unknown): ContextResolution {
  const m = isPlainObject(meta) ? meta : {}
  const block = m[EXT_ID]
  const extensionValue =
    isPlainObject(block) && typeof block.context_id === 'string' && HEX32.test(block.context_id)
      ? block.context_id
      : undefined
  const traceValue = typeof m.traceparent === 'string' ? extractTraceId(m.traceparent) : undefined

  if (typeof explicitArgument === 'string' && HEX32.test(explicitArgument)) {
    const lowerCarrier = extensionValue ?? traceValue
    return {
      contextId: explicitArgument,
      source: 'argument',
      mismatchWarning: lowerCarrier !== undefined && lowerCarrier !== explicitArgument,
    }
  }
  if (extensionValue !== undefined) {
    return {
      contextId: extensionValue,
      source: 'extension',
      mismatchWarning: traceValue !== undefined && traceValue !== extensionValue,
    }
  }
  if (traceValue !== undefined) {
    return { contextId: traceValue, source: 'traceparent', mismatchWarning: false }
  }
  // No per-request carrier resolved. Producer-side D078/D083 env-file
  // resolution applies next; at the transport layer the result is undefined.
  return { source: 'env-registry-fallthrough', mismatchWarning: false }
}

// ─── Reference implementation: extension spec §6 (gated result carriage) ─

function buildExtensionResultBlock(record: AtribRecord, includeRecord: boolean): Record<string, unknown> {
  const shortName = Object.entries(EVENT_TYPE_SHORT_TO_URI).find(([, uri]) => uri === record.event_type)?.[0]
  const block: Record<string, unknown> = {
    token: encodeToken(record),
    receipt: {
      record_hash: `sha256:${hexEncode(sha256(canonicalRecord(record)))}`,
      creator_key: record.creator_key,
      context_id: record.context_id,
      event_type: shortName ?? record.event_type,
      chain_root: record.chain_root,
      log_submission: 'queued',
    },
  }
  if (includeRecord) block.record = record
  return block
}

/**
 * §5.8-conformant result extension. Signing, capability detection, and
 * carriage all live inside one try/catch: any failure leaves the tool
 * result byte-identical to passthrough and never throws to the caller.
 */
function extendResultSafely(
  result: Record<string, unknown>,
  requestMeta: unknown,
  sign: () => AtribRecord,
): void {
  try {
    const record = sign()
    const declaration = detectClientDeclaration(requestMeta)
    writeOutboundContext(result, record)
    if (declaration.declared) {
      const meta = result._meta as Record<string, unknown>
      meta[EXT_ID] = buildExtensionResultBlock(record, declaration.effectiveAccept.includes('record'))
    }
  } catch {
    // §5.8: extension failures never affect the primary tool result.
  }
}

// ─── Reference implementation: extension spec §6.2 (receipt verification) ─

interface ReceiptBlock {
  token: string
  receipt: {
    record_hash: string
    creator_key: string
    context_id: string
    event_type: string
    chain_root: string
    log_submission: string
  }
  record?: AtribRecord
}

function verifyReceiptBlock(block: ReceiptBlock): { valid: boolean; mismatched: string[] } {
  const mismatched: string[] = []
  const decoded = decodeToken(block.token)
  if (!decoded) return { valid: false, mismatched: ['token'] }
  const tokenHashHex = hexEncode(decoded.recordHash)
  const tokenKey = base64urlEncode(decoded.creatorKey)

  if (block.receipt.record_hash !== `sha256:${tokenHashHex}`) mismatched.push('record_hash')
  if (block.receipt.creator_key !== tokenKey) mismatched.push('creator_key')
  if (!LOG_SUBMISSION_STATUSES.has(block.receipt.log_submission)) mismatched.push('log_submission')

  if (block.record) {
    const recordHashHex = hexEncode(sha256(canonicalRecord(block.record)))
    if (block.token !== encodeToken(block.record) && !mismatched.includes('token')) {
      mismatched.push('token')
    }
    if (block.receipt.record_hash !== `sha256:${recordHashHex}` && !mismatched.includes('record_hash')) {
      mismatched.push('record_hash')
    }
    if (block.receipt.creator_key !== block.record.creator_key && !mismatched.includes('creator_key')) {
      mismatched.push('creator_key')
    }
    if (block.receipt.context_id !== block.record.context_id) mismatched.push('context_id')
    if (block.receipt.chain_root !== block.record.chain_root) mismatched.push('chain_root')
  }

  return { valid: mismatched.length === 0, mismatched }
}

// ═══ Family 1: capability ═══════════════════════════════════════════════

describe('mcp-extension conformance: capability', () => {
  it('server-declaration-valid: full server settings object accepted', () => {
    const c = loadCase('capability--server-declaration-valid')
    const expected = c.expected as { valid: boolean; declared: boolean; negotiated_version: string }
    const v = validateSettings(c.input.settings)
    expect(v.declared).toBe(expected.declared)
    expect(v.negotiatedVersion).toBe(expected.negotiated_version)
    expect(v.ignoredSettingsFields).toEqual([])
  })

  it('client-declaration-valid: accept negotiation recognized', () => {
    const c = loadCase('capability--client-declaration-valid')
    const expected = c.expected as {
      declared: boolean
      negotiated_version: string
      effective_accept: string[]
      accept_record: boolean
    }
    const v = validateSettings(c.input.settings)
    expect(v.declared).toBe(expected.declared)
    expect(v.negotiatedVersion).toBe(expected.negotiated_version)
    expect(v.effectiveAccept).toEqual(expected.effective_accept)
    expect(v.effectiveAccept.includes('record')).toBe(expected.accept_record)
  })

  it('unknown-settings-fields-ignored: forward compatibility', () => {
    const c = loadCase('capability--unknown-settings-fields-ignored')
    const expected = c.expected as {
      declared: boolean
      negotiated_version: string
      effective_accept: string[]
      ignored_settings_fields: string[]
      ignored_accept_values: string[]
    }
    const v = validateSettings(c.input.settings)
    expect(v.declared).toBe(expected.declared)
    expect(v.negotiatedVersion).toBe(expected.negotiated_version)
    expect(v.effectiveAccept).toEqual(expected.effective_accept)
    expect(v.ignoredSettingsFields).toEqual(expected.ignored_settings_fields)
    expect(v.ignoredAcceptValues).toEqual(expected.ignored_accept_values)
  })

  it('missing-version-rejected: treated as undeclared, never an error', () => {
    const c = loadCase('capability--missing-version-rejected')
    const expected = c.expected as { declared: boolean; error_raised: boolean }
    let raised = false
    let v: SettingsValidation | undefined
    try {
      v = validateSettings(c.input.settings)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(v?.declared).toBe(expected.declared)
  })

  it('reserved-prefix-rejected: SEP-2133 identifier grammar', () => {
    const c = loadCase('capability--reserved-prefix-rejected')
    const identifiers = c.input.identifiers as string[]
    const results = c.expected.results as { identifier: string; valid: boolean }[]
    expect(identifiers.length).toBe(results.length)
    for (const r of results) {
      expect(validateExtensionIdentifier(r.identifier), r.identifier).toBe(r.valid)
    }
  })
})

// ═══ Family 2: gating ═══════════════════════════════════════════════════

function runGatedResult(c: CaseFile): Record<string, unknown> {
  const record = c.input.signed_record as AtribRecord
  const result: Record<string, unknown> = { content: [{ type: 'text', text: 'ok' }] }
  extendResultSafely(result, c.input.request_meta, () => record)
  return result
}

describe('mcp-extension conformance: gating', () => {
  it('declared-receipt-present: prefixed block alongside byte-identical legacy keys', async () => {
    const c = loadCase('gating--declared-receipt-present')
    const expected = c.expected as {
      extension_block_present: boolean
      result_meta: Record<string, unknown>
      legacy_keys: Record<string, string>
    }
    const result = runGatedResult(c)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    expect(meta).toEqual(expected.result_meta)
    expect(meta.atrib).toBe(expected.legacy_keys.atrib)
    expect(meta.tracestate).toBe(expected.legacy_keys.tracestate)
    expect(meta['X-Atrib-Chain']).toBe(expected.legacy_keys['X-Atrib-Chain'])

    // The attached record body is a real signed record (Tier-3 check).
    const block = meta[EXT_ID] as ReceiptBlock
    expect(block.record).toBeDefined()
    expect(await verifyRecordSignature(block.record as AtribRecord)).toBe(true)
  })

  it('declared-token-only: receipt present, record body omitted', () => {
    const c = loadCase('gating--declared-token-only')
    const expected = c.expected as {
      extension_block_present: boolean
      record_body_present: boolean
      result_meta: Record<string, unknown>
    }
    const result = runGatedResult(c)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    const block = meta[EXT_ID] as Record<string, unknown>
    expect('record' in block).toBe(expected.record_body_present)
    expect(meta).toEqual(expected.result_meta)
  })

  it('undeclared-legacy-only: byte-identical to pre-extension writeOutboundContext output', () => {
    const c = loadCase('gating--undeclared-legacy-only')
    const expected = c.expected as {
      extension_block_present: boolean
      result_meta: Record<string, unknown>
      result_meta_jcs_sha256_hex: string
    }
    const result = runGatedResult(c)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    expect(meta).toEqual(expected.result_meta)
    // Byte-identity pinned by JCS hash against real writeOutboundContext output.
    expect(jcsSha256Hex(meta)).toBe(expected.result_meta_jcs_sha256_hex)
  })

  it('malformed-clientcapabilities-undeclared: treated as undeclared, no error', () => {
    const c = loadCase('gating--malformed-clientcapabilities-undeclared')
    const expected = c.expected as {
      extension_block_present: boolean
      error_raised: boolean
      result_meta: Record<string, unknown>
    }
    let raised = false
    let result: Record<string, unknown> = {}
    try {
      result = runGatedResult(c)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    const meta = result._meta as Record<string, unknown>
    expect(EXT_ID in meta).toBe(expected.extension_block_present)
    expect(meta).toEqual(expected.result_meta)
  })
})

// ═══ Family 3: token (Ladder 1) ═════════════════════════════════════════

describe('mcp-extension conformance: token precedence (Ladder 1)', () => {
  interface TokenExpected {
    resolved_source: TokenSource
    resolved_record_hash_hex?: string
    resolved_creator_key?: string
    conflict_warning?: boolean
    error_raised?: boolean
  }

  function runTokenCase(name: string): void {
    const c = loadCase(name)
    const expected = c.expected as unknown as TokenExpected
    let raised = false
    let resolution: TokenResolution | undefined
    try {
      resolution = resolveInboundToken(c.input.request_meta)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised ?? false)
    expect(resolution).toBeDefined()
    expect(resolution!.source).toBe(expected.resolved_source)
    if (expected.resolved_record_hash_hex !== undefined) {
      expect(resolution!.recordHashHex).toBe(expected.resolved_record_hash_hex)
    }
    if (expected.resolved_creator_key !== undefined) {
      expect(resolution!.creatorKey).toBe(expected.resolved_creator_key)
    }
    if (expected.conflict_warning !== undefined) {
      expect(resolution!.conflictWarning).toBe(expected.conflict_warning)
    }
  }

  it('extension-key-wins: four conflicting carriers, extension wins with warning', () => {
    runTokenCase('token--extension-key-wins')
  })

  it('malformed-extension-falls-through: lenient parse to _meta.atrib', () => {
    runTokenCase('token--malformed-extension-falls-through')
  })

  it('meta-atrib-over-tracestate: legacy order preserved beneath the extension rung', () => {
    runTokenCase('token--meta-atrib-over-tracestate')
  })

  it('tracestate-over-x-atrib-chain: tracestate beats the fallback header', () => {
    runTokenCase('token--tracestate-over-x-atrib-chain')
  })

  it('x-atrib-chain-fallback: last rung resolves alone', () => {
    runTokenCase('token--x-atrib-chain-fallback')
  })

  it('all-carriers-stripped: chain resolution continues per D067 / §1.2.3.1', () => {
    const c = loadCase('token--all-carriers-stripped')
    const expected = c.expected as {
      resolved_source: null
      inbound_token_resolved: boolean
      synthetic_genesis_chain_root_for_traceparent_context: string
    }
    const resolution = resolveInboundToken(c.input.request_meta)
    expect(resolution.source).toBe(expected.resolved_source)
    expect(resolution.recordHashHex !== undefined).toBe(expected.inbound_token_resolved)
    // The genesis chain_root the D067 ladder bottoms out at is reproducible.
    const meta = c.input.request_meta as Record<string, unknown>
    const traceId = extractTraceId(meta.traceparent as string)
    expect(traceId).toBeDefined()
    expect(genesisChainRoot(traceId as string)).toBe(
      expected.synthetic_genesis_chain_root_for_traceparent_context,
    )
  })
})

// ═══ Family 4: context (Ladder 2) ═══════════════════════════════════════

describe('mcp-extension conformance: context-identity precedence (Ladder 2)', () => {
  interface ContextExpected {
    resolved_context_id: string | null
    resolved_source: ContextSource
    mismatch_warning?: boolean
    error_raised?: boolean
  }

  function runContextCase(name: string): ContextResolution {
    const c = loadCase(name)
    const expected = c.expected as unknown as ContextExpected
    let raised = false
    let resolution: ContextResolution | undefined
    try {
      resolution = resolveContextIdentity(c.input.explicit_context_id_argument, c.input.request_meta)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised ?? false)
    expect(resolution).toBeDefined()
    expect(resolution!.contextId ?? null).toBe(expected.resolved_context_id)
    expect(resolution!.source).toBe(expected.resolved_source)
    if (expected.mismatch_warning !== undefined) {
      expect(resolution!.mismatchWarning).toBe(expected.mismatch_warning)
    }
    return resolution!
  }

  it('explicit-argument-wins: application intent beats transport metadata', () => {
    runContextCase('context--explicit-argument-wins')
  })

  it('extension-over-traceparent: extension block beats trace-id with warning', () => {
    runContextCase('context--extension-over-traceparent')
  })

  it('invalid-extension-hex-falls-through: non-32-hex ignored, never an error', () => {
    runContextCase('context--invalid-extension-hex-falls-through')
  })

  it('no-carrier-env-fallthrough: transport yields nothing, D078/D083 applies producer-side', () => {
    runContextCase('context--no-carrier-env-fallthrough')
  })

  it('unknown-fields-ignored: extra block fields have no record-field effect', () => {
    const c = loadCase('context--unknown-fields-ignored')
    const expected = c.expected as {
      resolved_record_hash_hex: string
      ignored_fields: string[]
      record_field_effects: string[]
    }
    runContextCase('context--unknown-fields-ignored')

    // Both defined fields still resolve; everything else is ignored.
    const meta = c.input.request_meta as Record<string, unknown>
    const tokenResolution = resolveInboundToken(meta)
    expect(tokenResolution.source).toBe('extension')
    expect(tokenResolution.recordHashHex).toBe(expected.resolved_record_hash_hex)

    const block = meta[EXT_ID] as Record<string, unknown>
    const definedFields = new Set(['token', 'context_id'])
    const ignored = Object.keys(block)
      .filter((k) => !definedFields.has(k))
      .sort()
    expect(ignored).toEqual(expected.ignored_fields)
    // v0.1 maps exactly one block field onto a signed-record field.
    expect(expected.record_field_effects).toEqual(['context_id'])
    expect(expected.ignored_fields).toContain('session_token')
    expect(expected.ignored_fields).toContain('provenance_token')
  })
})

// ═══ Family 5: receipt ══════════════════════════════════════════════════

describe('mcp-extension conformance: receipt integrity', () => {
  it('consistent: receipt fields recompute from the real signed record', async () => {
    const c = loadCase('receipt--consistent')
    const block = c.input.result_block as unknown as ReceiptBlock
    const expected = c.expected as {
      receipt_valid: boolean
      token: string
      record_hash: string
      creator_key: string
      context_id: string
      chain_root: string
      args_hash_recomputes_from_tool_args: boolean
      record_signature_verifies: boolean
    }
    const record = block.record as AtribRecord

    // Receipt block is internally consistent per the reference verifier.
    expect(verifyReceiptBlock(block).valid).toBe(expected.receipt_valid)

    // Every receipt field recomputes from the record's canonical bytes.
    expect(block.token).toBe(encodeToken(record))
    expect(block.token).toBe(expected.token)
    expect(`sha256:${hexEncode(sha256(canonicalRecord(record)))}`).toBe(expected.record_hash)
    expect(block.receipt.record_hash).toBe(expected.record_hash)
    expect(record.creator_key).toBe(expected.creator_key)
    expect(record.context_id).toBe(expected.context_id)
    expect(record.chain_root).toBe(expected.chain_root)
    expect(genesisChainRoot(record.context_id)).toBe(expected.chain_root)

    // args_hash is a real §8.3 plain-sha256 commitment to the pinned args.
    const recomputedArgsHash = `sha256:${jcsSha256Hex(c.input.tool_args)}`
    expect(recomputedArgsHash === record.args_hash).toBe(expected.args_hash_recomputes_from_tool_args)

    // Tier-3: the attached record's signature verifies independently.
    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_verifies)
  })

  it('hash-mismatch-flagged: mismatched receipt discarded, tool result untouched', () => {
    const c = loadCase('receipt--hash-mismatch-flagged')
    const block = c.input.result_block as unknown as ReceiptBlock
    const expected = c.expected as {
      receipt_valid: boolean
      mismatched_fields: string[]
      attached_record_hash: string
      claimed_record_hash: string
      tool_result_invalidated: boolean
    }
    const verdict = verifyReceiptBlock(block)
    expect(verdict.valid).toBe(expected.receipt_valid)
    expect(verdict.mismatched).toEqual(expected.mismatched_fields)

    // Both hashes are real: the attached record recomputes to one, the
    // receipt claims the other.
    const record = block.record as AtribRecord
    expect(`sha256:${hexEncode(sha256(canonicalRecord(record)))}`).toBe(expected.attached_record_hash)
    expect(block.receipt.record_hash).toBe(expected.claimed_record_hash)
    expect(expected.tool_result_invalidated).toBe(false)
  })

  it('log-submission-nonblocking: queued receipt valid before submission settles', () => {
    const c = loadCase('receipt--log-submission-nonblocking')
    const block = c.input.result_block as unknown as ReceiptBlock
    const expected = c.expected as {
      receipt_valid: boolean
      log_submission: string
      allowed_statuses: string[]
      proof_bundle_required: boolean
      awaiting_submission_forbidden: boolean
    }
    // Valid without any record body, proof bundle, or settled submission.
    expect(verifyReceiptBlock(block).valid).toBe(expected.receipt_valid)
    expect(block.record).toBeUndefined()
    expect(block.receipt.log_submission).toBe(expected.log_submission)
    expect([...LOG_SUBMISSION_STATUSES].sort()).toEqual([...expected.allowed_statuses].sort())
    for (const status of expected.allowed_statuses) {
      expect(LOG_SUBMISSION_STATUSES.has(status)).toBe(true)
    }
    expect(expected.proof_bundle_required).toBe(false)
    expect(expected.awaiting_submission_forbidden).toBe(true)
  })
})

// ═══ Family 6: degradation ══════════════════════════════════════════════

describe('mcp-extension conformance: degradation (§5.8)', () => {
  it('signing-failure-passthrough: result byte-identical, no error', () => {
    const c = loadCase('degradation--signing-failure-passthrough')
    const expected = c.expected as {
      result_jcs_sha256_hex: string
      extension_block_present: boolean
      error_raised: boolean
    }
    const result = structuredClone(c.input.tool_result) as Record<string, unknown>
    let raised = false
    try {
      extendResultSafely(result, c.input.request_meta, () => {
        throw new Error('forced signing failure')
      })
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(result._meta).toBeUndefined()
    expect(jcsSha256Hex(result)).toBe(expected.result_jcs_sha256_hex)
    expect(expected.extension_block_present).toBe(false)
  })

  it('capability-read-failure-passthrough: throwing capability read swallowed', () => {
    const c = loadCase('degradation--capability-read-failure-passthrough')
    const expected = c.expected as {
      result_jcs_sha256_hex: string
      extension_block_present: boolean
      error_raised: boolean
    }
    const result = structuredClone(c.input.tool_result) as Record<string, unknown>
    // A signable record exists; the failure is injected at capability read.
    const dummyRecord: AtribRecord = {
      spec_version: 'atrib/1.0',
      content_id: 'sha256:' + '00'.repeat(32),
      creator_key: base64urlEncode(new Uint8Array(32)),
      chain_root: genesisChainRoot('0'.repeat(31) + '1'),
      event_type: EVENT_TYPE_SHORT_TO_URI.tool_call,
      context_id: '0'.repeat(31) + '1',
      timestamp: 0,
      signature: '',
    }
    const throwingMeta = new Proxy(
      {},
      {
        get(): never {
          throw new Error('forced capability-read failure')
        },
        has(): never {
          throw new Error('forced capability-read failure')
        },
      },
    )
    let raised = false
    try {
      extendResultSafely(result, throwingMeta, () => dummyRecord)
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(result._meta).toBeUndefined()
    expect(jcsSha256Hex(result)).toBe(expected.result_jcs_sha256_hex)
    expect(expected.extension_block_present).toBe(false)
  })

  it('missing-meta-never-blocks: total _meta loss, both ladders resolve to nothing', () => {
    const c = loadCase('degradation--missing-meta-never-blocks')
    const expected = c.expected as {
      inbound_token_resolved: boolean
      resolved_context_id: string | null
      tool_call_proceeds: boolean
      error_raised: boolean
    }
    const params = c.input.request_params as Record<string, unknown>
    expect(params._meta).toBeUndefined()
    let raised = false
    let proceeds = false
    try {
      const tokenResolution = resolveInboundToken(params._meta)
      const contextResolution = resolveContextIdentity(undefined, params._meta)
      expect(tokenResolution.recordHashHex !== undefined).toBe(expected.inbound_token_resolved)
      expect(contextResolution.contextId ?? null).toBe(expected.resolved_context_id)
      proceeds = true
    } catch {
      raised = true
    }
    expect(raised).toBe(expected.error_raised)
    expect(proceeds).toBe(expected.tool_call_proceeds)
  })
})
