// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §1.2.6 conformance: provenance_token (D044).
 *
 * Loads each case from spec/conformance/1.2.6/cases/ and asserts the
 * expected invariants. The corpus itself is regenerated by
 * packages/log-dev/scripts/generate-conformance-1.2.6.ts; this test
 * verifies that @atrib/verify (and the underlying @atrib/mcp signing
 * primitives) honor the §1.2.6 contract.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  base64urlEncode,
  canonicalRecord,
  canonicalSigningInput,
  genesisChainRoot,
  hexEncode,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'
import { verifyRecord } from '../src/verify-record.js'

const CORPUS = join(__dirname, '../../../spec/conformance/1.2.6/cases')

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

describe('spec §1.2.6 conformance', () => {
  it('genesis-with-provenance: signature round-trips with provenance_token in canonical form', async () => {
    const c = loadCase('genesis-with-provenance')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      record_hash_hex: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
    }

    // Canonical signing input matches the spec-mandated JCS form.
    const actualSigningInput = new TextDecoder().decode(canonicalSigningInput(record))
    expect(actualSigningInput).toBe(expected.canonical_signing_input_utf8)

    // record_hash matches.
    const actualHash = hexEncode(sha256(canonicalRecord(record)))
    expect(actualHash).toBe(expected.record_hash_hex)

    // Signature verifies.
    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
  })

  it('upstream-derivation: provenance_token derives from upstream canonical hash', async () => {
    const c = loadCase('upstream-derivation')
    const upstream = c.input.upstream_record as AtribRecord
    const downstream = c.input.downstream_record as AtribRecord
    const expected = c.expected as {
      derived_provenance_token: string
      upstream_full_record_hash: string
      downstream_signature_verifies: boolean
    }

    // Implementation reproduces the §1.2.6 derivation: token = base64url(sha256(JCS(upstream))[:16]).
    const upstreamHashBytes = sha256(canonicalRecord(upstream))
    const reproducedToken = base64urlEncode(upstreamHashBytes.slice(0, 16))
    expect(reproducedToken).toBe(expected.derived_provenance_token)

    // The record carries the derived token.
    const downstreamWithToken = downstream as AtribRecord & { provenance_token?: string }
    expect(downstreamWithToken.provenance_token).toBe(expected.derived_provenance_token)

    // Full upstream hash also matches.
    expect(`sha256:${hexEncode(upstreamHashBytes)}`).toBe(expected.upstream_full_record_hash)

    // Downstream signature verifies independently.
    expect(await verifyRecordSignature(downstream)).toBe(expected.downstream_signature_verifies)

    // verifyRecord with the upstream candidate resolves the provenance.
    const result = await verifyRecord(downstream, { upstreamCandidate: upstream })
    expect(result.provenance).toBeDefined()
    expect(result.provenance!.upstream_resolved).toBe(true)
    expect(result.provenance!.upstream_record_hash).toBe(expected.upstream_full_record_hash)
  })

  it('non-genesis-with-provenance: genesis-only invariant flagged by verifyRecord caller-checks', async () => {
    const c = loadCase('non-genesis-with-provenance')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      genesis_chain_root_for_context: string
      record_chain_root: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
    }

    // Signature itself verifies, rejection is at the policy layer.
    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)

    // The expected genesis chain_root for the context_id is computable.
    expect(genesisChainRoot(record.context_id)).toBe(expected.genesis_chain_root_for_context)

    // The record's chain_root is NOT the genesis chain_root, which is the
    // structural condition for §1.2.6 rejection. (verifyRecord itself does
    // not enforce, see the function docstring on policy boundary.)
    expect(record.chain_root).not.toBe(expected.genesis_chain_root_for_context)
    expect(record.chain_root).toBe(expected.record_chain_root)

    // Validators MUST reject this record per §2.6.1 / §1.2.6.
    expect(expected.validator_should_accept).toBe(false)
  })

  it('omits-when-absent: canonical form has no provenance_token field when not anchoring', async () => {
    const c = loadCase('omits-when-absent')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      provenance_token_in_canonical_form: boolean
      record_hash_hex: string
    }

    // Signing input does not contain "provenance_token".
    const signingInput = new TextDecoder().decode(canonicalSigningInput(record))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)
    expect(signingInput.includes('provenance_token')).toBe(expected.provenance_token_in_canonical_form)

    // record_hash matches.
    expect(hexEncode(sha256(canonicalRecord(record)))).toBe(expected.record_hash_hex)
  })
})
