// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §1.11 conformance: delegation certificates (D140).
 *
 * Loads each case from spec/conformance/delegation-certificates/cases/
 * and asserts the expected invariants. The corpus is regenerated by
 * packages/log-dev/scripts/generate-conformance-delegation-certificates.ts;
 * the reference implementation now lives in `src/delegation.ts` (promoted
 * from this file's original in-test walk) and this suite pins it against
 * the §1.11 contract:
 *
 *   - certificate JCS canonical form, principal Ed25519 signature,
 *     cert_hash derivation, self-certificate + wrong-signer rejection
 *   - the §1.11.4 verifier walk (record -> run key -> certificate ->
 *     principal) with in_window / context_bound / cert_bound / scope
 *     facts as signals, never invalidation (§6.7.3 posture)
 *   - depth-0 identity: byte-for-byte equality with the §1.4 corpus
 *   - delegation_cert_hash lex-slotting between creator_key and
 *     event_type, with distinct signatures for presence vs absence
 *   - §1.9.2 signing rule 3 (principal-signed run-key revocation) and
 *     its rejection when the referenced certificate does not cover
 *     revoked_key
 *   - the D067 multi-producer posture: cert_bound stays null for run
 *     keys that joined a context whose genesis another producer signed
 *     (the signed-by qualifier: genesis commitments only bind records
 *     whose creator_key signed that genesis)
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import canonicalize from 'canonicalize'
import {
  canonicalRecord,
  canonicalSigningInput,
  hexEncode,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'
import {
  checkCostPolicy,
  delegationCertErrors,
  delegationCertHash,
  delegationCertSignatureVerifies,
  delegationCertSigningInput,
  evaluateDelegation,
  evaluateRevokerAuthorization,
  type CostPolicyUsage,
  type DelegatedRecord,
  type DelegationCertificate,
  type DelegationCostPolicy,
  type DelegationOutcome,
  type KeyRevocationRecordLike,
} from '../src/delegation.js'
import { buildRevocationRegistry, applyRevocation, type MinimalRecord } from '../src/revocations.js'
import type { VerificationState } from '../src/types.js'

const CORPUS = join(__dirname, '../../../spec/conformance/delegation-certificates/cases')
const SIGNING_VECTORS_1_4 = join(__dirname, '../../../spec/conformance/1.4/signing-vectors.json')

// ── Corpus shapes ─────────────────────────────────────────────────────

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

/** Field-order helper: index of a key in a JCS canonical string. */
function keyIndex(canonicalJson: string, key: string): number {
  return canonicalJson.indexOf(`"${key}":`)
}

// ── Tests ─────────────────────────────────────────────────────────────

describe('spec §1.11 conformance: delegation certificates', () => {
  it('cert-canonical-full: JCS form, principal signature, cert_hash', async () => {
    const c = loadCase('cert-canonical-full')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      canonical_signed_form_utf8: string
      cert_hash: string
      principal_signature_verifies: boolean
      cert_valid: boolean
      jcs_field_order: string[]
    }

    const signingInput = new TextDecoder().decode(delegationCertSigningInput(cert))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)

    const signedForm = canonicalize(cert)
    expect(signedForm).toBe(expected.canonical_signed_form_utf8)

    // Declared JCS field order is the actual order in the canonical bytes.
    const positions = expected.jcs_field_order.map((k) =>
      keyIndex(expected.canonical_signed_form_utf8, k),
    )
    for (const p of positions) expect(p).toBeGreaterThanOrEqual(0)
    expect([...positions].sort((a, b) => a - b)).toEqual(positions)

    expect(delegationCertHash(cert)).toBe(expected.cert_hash)
    expect(await delegationCertSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
    expect((await delegationCertErrors(cert)).length === 0).toBe(expected.cert_valid)
  })

  it('cert-canonical-minimal: absence-not-null, distinct hash from full form', async () => {
    const c = loadCase('cert-canonical-minimal')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      cert_hash: string
      principal_signature_verifies: boolean
      optional_fields_in_canonical_form: boolean
      differs_from_full_form_cert_hash: string
    }

    const signingInput = new TextDecoder().decode(delegationCertSigningInput(cert))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)
    const hasOptional =
      signingInput.includes('"context_id"') ||
      signingInput.includes('"not_before"') ||
      signingInput.includes('"scope"')
    expect(hasOptional).toBe(expected.optional_fields_in_canonical_form)

    expect(delegationCertHash(cert)).toBe(expected.cert_hash)
    expect(expected.cert_hash).not.toBe(expected.differs_from_full_form_cert_hash)
    expect(await delegationCertSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
  })

  it('cert-invalid-self: signature verifies, certificate rejected as evidence', async () => {
    const c = loadCase('cert-invalid-self')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      cert_hash: string
      principal_signature_verifies: boolean
      cert_valid: boolean
      errors: string[]
    }

    expect(delegationCertHash(cert)).toBe(expected.cert_hash)
    expect(await delegationCertSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
    const errors = await delegationCertErrors(cert)
    expect(errors.length === 0).toBe(expected.cert_valid)
    expect(errors).toEqual(expected.errors)
  })

  it('cert-invalid-wrong-signer: principal signature fails, certificate rejected', async () => {
    const c = loadCase('cert-invalid-wrong-signer')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      cert_hash: string
      principal_signature_verifies: boolean
      cert_valid: boolean
      errors: string[]
    }

    expect(delegationCertHash(cert)).toBe(expected.cert_hash)
    expect(await delegationCertSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
    const errors = await delegationCertErrors(cert)
    expect(errors.length === 0).toBe(expected.cert_valid)
    expect(errors).toEqual(expected.errors)
  })

  // Shared runner for the walk cases: record signature is checked with the
  // UNCHANGED §1.4.3 procedure, then the delegation outcome is compared
  // deep-equal against the corpus contract.
  async function assertWalkCase(name: string): Promise<void> {
    const c = loadCase(name)
    const record = c.input.record as DelegatedRecord
    const genesis = (c.input.genesis_record ?? null) as DelegatedRecord | null
    const certs = c.input.certificates as DelegationCertificate[]
    const expected = c.expected as {
      record_signature_valid: boolean
      record_hash: string
      delegation: DelegationOutcome
    }

    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_valid)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(record)))).toBe(expected.record_hash)

    const outcome = await evaluateDelegation(record, genesis, certs)
    expect(outcome).toEqual(expected.delegation)
  }

  it('walk-valid: depth-1 resolution with all facts positive', async () => {
    await assertWalkCase('walk-valid')
  })

  it('walk-expired: in_window false is a signal; record stays valid', async () => {
    await assertWalkCase('walk-expired')
    const c = loadCase('walk-expired')
    const record = c.input.record as DelegatedRecord
    const cert = (c.input.certificates as DelegationCertificate[])[0]
    expect(cert).toBeDefined()
    expect(record.timestamp).toBeGreaterThan(cert!.not_after)
  })

  it('walk-scope-mismatch: out-of-scope is a signal, not invalidation (§6.7.3)', async () => {
    await assertWalkCase('walk-scope-mismatch')
    const c = loadCase('walk-scope-mismatch')
    // The signal-not-block invariant: the corpus pins record validity true
    // alongside in_scope false.
    expect((c.expected as { signal_not_block: boolean }).signal_not_block).toBe(true)
    expect((c.expected as { record_signature_valid: boolean }).record_signature_valid).toBe(true)
    const delegation = (c.expected as { delegation: DelegationOutcome }).delegation
    expect(delegation.scope_check?.in_scope).toBe(false)
  })

  it('walk-scope-cost-policy: cost_policy scope is usage-fact-evaluable, signal-only (D165)', async () => {
    await assertWalkCase('walk-scope-cost-policy')
    const c = loadCase('walk-scope-cost-policy')
    expect((c.expected as { signal_not_block: boolean }).signal_not_block).toBe(true)
    // From the record alone the walk names both cost constraints as
    // unverifiable. Absence no longer looks like a positive evaluation.
    const delegation = (c.expected as { delegation: DelegationOutcome }).delegation
    expect(delegation.scope_check).toEqual({
      in_scope: true,
      fully_evaluated: false,
      attenuation_ok: null,
      mismatches: [],
      unverifiable: ['cost_policy.model_tiers', 'cost_policy.max_tokens'],
    })
    // The pinned usage vectors evaluate through checkCostPolicy.
    const cert = (c.input.certificates as DelegationCertificate[])[0]!
    const costPolicy = (cert.scope as { cost_policy?: DelegationCostPolicy }).cost_policy
    expect(costPolicy).toBeDefined()
    const vectors = c.input.usage_vectors as Array<{
      name: string
      usage: CostPolicyUsage
      expected: { in_scope: boolean; mismatches: string[] }
    }>
    expect(vectors.length).toBeGreaterThan(0)
    for (const v of vectors) {
      expect(checkCostPolicy(costPolicy!, v.usage), v.name).toEqual(v.expected)
    }
  })

  it('walk-wrong-principal-signature: invalid cert falls back to depth 0', async () => {
    await assertWalkCase('walk-wrong-principal-signature')
  })

  it('walk-run-key-mismatch: cert never selected; delegation_unresolved surfaces', async () => {
    await assertWalkCase('walk-run-key-mismatch')
    const c = loadCase('walk-run-key-mismatch')
    const record = c.input.record as DelegatedRecord
    const cert = (c.input.certificates as DelegationCertificate[])[0]
    expect(cert).toBeDefined()
    expect(cert!.run_pubkey).not.toBe(record.creator_key)
    expect(record.delegation_cert_hash).toBe(delegationCertHash(cert!))
  })

  it('cert-malformed-run-key: rejects the malformed key before signature interpretation', async () => {
    const c = loadCase('cert-malformed-run-key')
    const expected = c.expected as { errors: string[] }
    expect(await delegationCertErrors(c.input.certificate as DelegationCertificate)).toEqual(
      expected.errors,
    )
  })

  it('walk-ambiguous-principals: surfaces overlapping candidates without selecting one', async () => {
    const c = loadCase('walk-ambiguous-principals')
    const expected = c.expected as {
      delegation_ambiguous: boolean
      candidate_count: number
      depth: 0 | 1
    }
    const outcome = await evaluateDelegation(
      c.input.record as DelegatedRecord,
      c.input.genesis_record as DelegatedRecord,
      c.input.certificates as DelegationCertificate[],
    )
    expect(outcome.depth).toBe(expected.depth)
    expect(outcome.delegation_ambiguous).toBe(expected.delegation_ambiguous)
    expect(outcome.candidates).toHaveLength(expected.candidate_count)
  })

  it('walk-depth-limit: rejects a second delegation hop', async () => {
    const c = loadCase('walk-depth-limit')
    const expected = c.expected as { depth: 0 | 1; cert_valid: boolean; errors: string[] }
    const outcome = await evaluateDelegation(
      c.input.record as DelegatedRecord,
      c.input.genesis_record as DelegatedRecord,
      c.input.certificates as DelegationCertificate[],
    )
    expect(outcome.depth).toBe(expected.depth)
    expect(outcome.cert_valid).toBe(expected.cert_valid)
    expect(outcome.errors).toEqual(expected.errors)
  })

  it('depth0-identity: byte-identical to the §1.4 corpus, delegation depth 0', async () => {
    const c = loadCase('depth0-identity')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      canonical_signing_input: string
      signature_base64url: string
      record_hash_hex: string
      record_signature_valid: boolean
      byte_identical_to_1_4_vector: boolean
      delegation: DelegationOutcome
    }

    // Byte identity against the live §1.4 corpus file: the embedded record
    // and expectations must equal the source vector exactly.
    const vectors = JSON.parse(readFileSync(SIGNING_VECTORS_1_4, 'utf8')) as {
      vectors: {
        input: { record: Record<string, unknown> }
        expected: Record<string, unknown>
      }[]
    }
    const sourceIndex = c.input.source_vector_index as number
    const source = vectors.vectors[sourceIndex]
    expect(source).toBeDefined()
    // The §1.4 vector's input.record carries signature: "" (signing is the
    // exercise there); the signed form is input.record + expected signature.
    expect(record).toEqual({
      ...source!.input.record,
      signature: source!.expected.signature_base64url,
    })
    expect(expected.canonical_signing_input).toBe(source!.expected.canonical_signing_input)
    expect(expected.signature_base64url).toBe(source!.expected.signature_base64url)
    expect(expected.record_hash_hex).toBe(source!.expected.record_hash_hex)
    expect(expected.byte_identical_to_1_4_vector).toBe(true)

    // Verification is byte-for-byte today's §1.4.3 procedure.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(record))
    expect(signingInput).toBe(expected.canonical_signing_input)
    expect(record.signature).toBe(expected.signature_base64url)
    expect(hexEncode(sha256(canonicalRecord(record)))).toBe(expected.record_hash_hex)
    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_valid)

    // With no certificate, the walk returns depth 0: attribution to
    // creator_key exactly as today.
    const outcome = await evaluateDelegation(record, null, [])
    expect(outcome).toEqual(expected.delegation)
  })

  it('genesis-field-canonical-form: lex slot between creator_key and event_type; distinct signatures', async () => {
    const c = loadCase('genesis-field-canonical-form')
    const withField = c.input.record_with_field as DelegatedRecord
    const withoutField = c.input.record_without_field as DelegatedRecord
    const expected = c.expected as {
      with_field_canonical_signing_input_utf8: string
      without_field_canonical_signing_input_utf8: string
      field_slots_after: string
      field_slots_before: string
      with_field_record_hash: string
      without_field_record_hash: string
      signatures_distinct: boolean
      record_hashes_distinct: boolean
      delegation_cert_hash: string
    }

    const withInput = new TextDecoder().decode(canonicalSigningInput(withField))
    const withoutInput = new TextDecoder().decode(canonicalSigningInput(withoutField))
    expect(withInput).toBe(expected.with_field_canonical_signing_input_utf8)
    expect(withoutInput).toBe(expected.without_field_canonical_signing_input_utf8)

    // Lex slotting: creator_key < delegation_cert_hash < event_type.
    const afterIdx = keyIndex(withInput, expected.field_slots_after)
    const fieldIdx = keyIndex(withInput, 'delegation_cert_hash')
    const beforeIdx = keyIndex(withInput, expected.field_slots_before)
    expect(afterIdx).toBeGreaterThanOrEqual(0)
    expect(fieldIdx).toBeGreaterThan(afterIdx)
    expect(beforeIdx).toBeGreaterThan(fieldIdx)

    // Absence-not-null: the without-form omits the field entirely.
    expect(withoutInput.includes('delegation_cert_hash')).toBe(false)
    expect(withoutInput.includes('null')).toBe(false)

    // Presence/absence changes the canonical form: distinct signatures + hashes.
    expect(withField.signature === withoutField.signature).toBe(!expected.signatures_distinct)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(withField)))).toBe(
      expected.with_field_record_hash,
    )
    expect('sha256:' + hexEncode(sha256(canonicalRecord(withoutField)))).toBe(
      expected.without_field_record_hash,
    )
    expect(expected.with_field_record_hash === expected.without_field_record_hash).toBe(
      !expected.record_hashes_distinct,
    )

    // The committed hash is the certificate's hash, and both records verify.
    expect(withField.delegation_cert_hash).toBe(expected.delegation_cert_hash)
    expect(delegationCertHash(c.input.certificate as DelegationCertificate)).toBe(
      expected.delegation_cert_hash,
    )
    expect(await verifyRecordSignature(withField)).toBe(true)
    expect(await verifyRecordSignature(withoutField)).toBe(true)
  })

  // Shared runner for the §1.9-extension revocation cases.
  async function assertRevocationCase(name: string): Promise<{
    caseFile: CaseFile
    auth: { authorized: boolean; rule?: string; reason?: string }
  }> {
    const c = loadCase(name)
    const entries = c.input.log_entries as { log_index: number; record: AtribRecord }[]
    const certs = c.input.certificates as DelegationCertificate[]
    const expected = c.expected as {
      revocation_signature_valid: boolean
      revoker_authorized: boolean
      verification_states: Record<string, string>
    }

    const revEntry = entries.find(
      (e) => e.record.event_type === 'https://atrib.dev/v1/types/key_revocation',
    )
    expect(revEntry).toBeDefined()
    const rev = revEntry!.record as KeyRevocationRecordLike

    // The revocation record's own signature (principal-signed; extra fields
    // covered by the signature since JCS canonicalizes the full body).
    expect(await verifyRecordSignature(rev)).toBe(expected.revocation_signature_valid)

    // §1.9.2 authorization including rule 3.
    const auth = await evaluateRevokerAuthorization(rev, certs)
    expect(auth.authorized).toBe(expected.revoker_authorized)

    // Only authorized revocations enter the registry; then §1.9.3 applies.
    const authorized: MinimalRecord[] = []
    for (const e of entries) {
      const r = e.record as KeyRevocationRecordLike
      if (r.event_type !== 'https://atrib.dev/v1/types/key_revocation') continue
      if (!(await evaluateRevokerAuthorization(r, certs)).authorized) continue
      authorized.push({ ...r, log_index: e.log_index })
    }
    const registry = buildRevocationRegistry(authorized)
    for (const e of entries) {
      const want = expected.verification_states[String(e.log_index)]
      if (want === undefined) continue
      const state = applyRevocation(
        {
          creator_key: e.record.creator_key,
          log_index: e.log_index,
          verification_state: 'signature_valid' as VerificationState,
        },
        registry,
      )
      expect(state, `${name} log_index ${e.log_index}`).toBe(want)
    }
    return { caseFile: c, auth }
  }

  it('revocation-run-key: principal-signed run-key revocation (§1.9.2 rule 3)', async () => {
    const { caseFile, auth } = await assertRevocationCase('revocation-run-key')
    const expected = caseFile.expected as {
      revocation_canonical_signing_input_utf8: string
      revoker_rule: string
      field_slots_after: string
      field_slots_before: string
      record_hashes: Record<string, string>
    }
    expect(auth.rule).toBe(expected.revoker_rule)

    const entries = caseFile.input.log_entries as { log_index: number; record: AtribRecord }[]
    const rev = entries.find(
      (e) => e.record.event_type === 'https://atrib.dev/v1/types/key_revocation',
    )!.record as KeyRevocationRecordLike

    // Canonical signing input pins the JCS order: creator_key <
    // delegation_cert_hash < event_type.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(rev))
    expect(signingInput).toBe(expected.revocation_canonical_signing_input_utf8)
    const afterIdx = keyIndex(signingInput, expected.field_slots_after)
    const fieldIdx = keyIndex(signingInput, 'delegation_cert_hash')
    const beforeIdx = keyIndex(signingInput, expected.field_slots_before)
    expect(afterIdx).toBeGreaterThanOrEqual(0)
    expect(fieldIdx).toBeGreaterThan(afterIdx)
    expect(beforeIdx).toBeGreaterThan(fieldIdx)

    // Record hashes reproduce.
    for (const e of entries) {
      expect('sha256:' + hexEncode(sha256(canonicalRecord(e.record)))).toBe(
        expected.record_hashes[String(e.log_index)],
      )
    }
  })

  it('revocation-cert-not-covering: unauthorized revoker rejected, states unaffected', async () => {
    const { caseFile, auth } = await assertRevocationCase('revocation-cert-not-covering')
    const expected = caseFile.expected as { rejection_reason: string }
    expect(auth.reason).toBe(expected.rejection_reason)
  })

  it('multi-producer-cert-bound-null: joining run key keeps cert_bound null (D067)', async () => {
    const c = loadCase('multi-producer-cert-bound-null')
    const record = c.input.record as DelegatedRecord
    const genesis = c.input.genesis_record as DelegatedRecord
    const certs = c.input.certificates as DelegationCertificate[]
    const expected = c.expected as {
      record_signature_valid: boolean
      record_hash: string
      genesis_creator_key: string
      genesis_signed_by_record_creator: boolean
      delegation: DelegationOutcome
    }

    // The context genesis was signed by a different producer key.
    expect(genesis.creator_key).toBe(expected.genesis_creator_key)
    expect(genesis.creator_key === record.creator_key).toBe(
      expected.genesis_signed_by_record_creator,
    )
    // The joining record chains to the other producer's genesis (§1.2.3.1).
    expect(record.chain_root).toBe('sha256:' + hexEncode(sha256(canonicalRecord(genesis))))

    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_valid)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(record)))).toBe(expected.record_hash)

    const outcome = await evaluateDelegation(record, genesis, certs)
    expect(outcome).toEqual(expected.delegation)
    expect(outcome.cert_bound).toBeNull()
    expect(outcome.context_bound).toBe(true)
  })
})
