// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §2.11 anchor-plurality conformance (D138; extends D050).
 *
 * Loads each case from spec/conformance/2.11/anchors/cases/ and asserts the
 * expected invariants against the LIBRARY implementations:
 *
 *   - verifier side: `verifyAnchorPlurality` from
 *     packages/verify/src/anchor-plurality.ts — legacy `log_proofs`
 *     elements (absent anchor_type) parse as `atrib-log`; discriminator
 *     malformation rules; unknown anchor_type values surfaced, not counted,
 *     never invalidating; the `anchor_plurality` annotation (single_anchor
 *     is a tier, never a failure; pending OTS proofs excluded until
 *     upgraded in place; independence counted over operator groups); and
 *     the unchanged §2.11.4 hard conditions (cross_log_threshold_not_met,
 *     cross_log_equivocation_detected, cross_log_censorship_suspected).
 *   - producer side: `resolveAnchorPosture` from
 *     packages/mcp/src/anchors.ts — the §2.11.12 allow_single_anchor
 *     posture resolution.
 *   - the fresh anchoring-signature claim artifact
 *     ("atrib-anchor/v1:" + record_hash, Ed25519-signed by an anchoring key
 *     that is NOT the record's signing key) and the proof that the record's
 *     own signature cannot ride the digest path.
 *   - determinism: two runs over the same bundle + trust config produce an
 *     identical verdict (the §4.6-style two-run discipline).
 *
 * The corpus is regenerated by
 * packages/log-dev/scripts/generate-conformance-anchors.ts; this test
 * consumes the committed vectors only.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import * as ed from '@noble/ed25519'
import { sha512 } from '@noble/hashes/sha2.js'
import {
  base64urlDecode,
  canonicalRecord,
  canonicalSigningInput,
  hexEncode,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'
import {
  ANCHOR_CLAIM_PREFIX,
  verifyAnchorPlurality,
} from '../src/anchor-plurality.js'
import type {
  AnchorNotFoundResponse,
  AnchorPluralityAnnotation,
  AnchorPluralityVerdict,
  AnchorProofBundle,
  AnchorProofElement,
  AnchorTrustConfig,
  AnchorDisagreeingPair,
} from '../src/anchor-plurality.js'
import { resolveAnchorPosture } from '../../mcp/src/anchors.js'
import type { AnchorSetConfig } from '../../mcp/src/anchors.js'

// @noble/ed25519 v3 needs sha512 wired (same wiring as @atrib/mcp signing).
ed.hashes.sha512 = sha512
ed.hashes.sha512Async = (m: Uint8Array) => Promise.resolve(sha512(m))

const CORPUS = join(__dirname, '../../../spec/conformance/2.11/anchors/cases')

const utf8Decode = new TextDecoder()

// ── Corpus shapes ────────────────────────────────────────────────────

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

/** Producer-posture resolution shape pinned by the corpus (name + library fields). */
interface PostureResolution {
  name: string
  effective_anchor_count: number
  used_default_set: boolean
  warn: boolean
  sidecar_anchor_config: { configured: number; allow_single_anchor: boolean } | null
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

function b64decode(s: string): Uint8Array {
  return new Uint8Array(Buffer.from(s, 'base64'))
}

/**
 * JCS-equivalent serialization for the FLAT objects this corpus signs
 * (ASCII string / integer values only): JSON.stringify with sorted keys.
 * Must byte-match packages/log-dev/scripts/generate-conformance-anchors.ts.
 */
function sortedJson(obj: Record<string, string | number>): string {
  const sorted: Record<string, string | number> = {}
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = obj[key] as string | number
  }
  return JSON.stringify(sorted)
}

// ── Shared helpers for the tests ─────────────────────────────────────

async function runCaseVerdict(
  c: CaseFile,
  bundleKey = 'bundle',
  trustKey = 'trust',
): Promise<AnchorPluralityVerdict> {
  const bundle = c.input[bundleKey] as AnchorProofBundle
  const trust = c.input[trustKey] as AnchorTrustConfig
  const notFound = (c.input['not_found_responses'] as AnchorNotFoundResponse[] | undefined) ?? []
  const verdict = await verifyAnchorPlurality(bundle, trust, notFound)
  // Determinism: a second run over the same inputs is identical (§4.6-style).
  const rerun = await verifyAnchorPlurality(bundle, trust, notFound)
  expect(rerun).toEqual(verdict)
  return verdict
}

describe('spec §2.11 anchors conformance', () => {
  it('legacy-single-log: absent anchor_type parses as atrib-log; single anchor is a tier, not a failure', async () => {
    const c = loadCase('legacy-single-log')
    const record = c.input['record'] as AtribRecord
    const expected = c.expected as unknown as {
      resolved_anchor_types: string[]
      record_signature_ok: boolean
      atrib_log_proof_verifies: boolean
      anchor_plurality: AnchorPluralityAnnotation
      hard_reject: boolean
    }

    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_ok)

    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
    expect(verdict.anchor_plurality.verified_count).toBe(1)
    expect(expected.resolved_anchor_types).toEqual(['atrib-log'])
    // The tier flag never invalidates: single_anchor true AND the record valid.
    expect(verdict.anchor_plurality.single_anchor).toBe(true)
  })

  it('discriminator-malformed-elements: rules (a) and (b) exclude elements without invalidating the record', async () => {
    const c = loadCase('discriminator-malformed-elements')
    const expected = c.expected as unknown as {
      malformed_indices: number[]
      anchor_plurality: AnchorPluralityAnnotation
      record_signature_ok: boolean
      hard_reject: boolean
    }
    const record = c.input['record'] as AtribRecord

    const verdict = await runCaseVerdict(c)
    expect(verdict.malformed_indices).toEqual(expected.malformed_indices)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_ok)
  })

  it('unknown-anchor-type: surfaced, not counted, not invalidating', async () => {
    const c = loadCase('unknown-anchor-type')
    const expected = c.expected as unknown as {
      anchor_plurality: AnchorPluralityAnnotation
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.anchor_plurality.unknown_types).toEqual(['example-quantum-beacon/v9'])
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('plurality-atrib-log-plus-rfc3161: two independent anchors meet the default plurality', async () => {
    const c = loadCase('plurality-atrib-log-plus-rfc3161')
    const expected = c.expected as unknown as {
      anchor_plurality: AnchorPluralityAnnotation
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.anchor_plurality.plurality_met).toBe(true)
    expect(verdict.anchor_plurality.single_anchor).toBe(false)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it.each(['rfc3161-binding-mismatch', 'opentimestamps-binding-mismatch'])(
    '%s: a per-type commitment mismatch is invalid and excluded from plurality',
    async (name) => {
      const c = loadCase(name)
      const expected = c.expected as { invalid_indices: number[]; hard_reject: boolean }
      const verdict = await runCaseVerdict(c)
      expect(verdict.invalid_indices).toEqual(expected.invalid_indices)
      expect(verdict.hard_reject).toBe(expected.hard_reject)
    },
  )

  it('malformed-unknown-precedence: malformed elements do not become unknown types', async () => {
    const c = loadCase('malformed-unknown-precedence')
    const expected = c.expected as {
      malformed_indices: number[]
      unknown_types: string[]
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.malformed_indices).toEqual(expected.malformed_indices)
    expect(verdict.anchor_plurality.unknown_types).toEqual(expected.unknown_types)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('rekor-anchor-claim: fresh anchoring signature over the reconstructible claim artifact verifies end to end', async () => {
    const c = loadCase('rekor-anchor-claim')
    const record = c.input['record'] as AtribRecord
    const bundle = c.input['bundle'] as AnchorProofBundle
    const expected = c.expected as unknown as {
      anchor_claim_artifact_utf8: string
      anchor_claim_prefix: string
      artifact_reconstructs_from_record_hash: boolean
      anchoring_signature_verifies: boolean
      anchoring_key_b64url: string
      anchoring_key_differs_from_creator_key: boolean
      set_signing_input_utf8: string
      anchor_plurality: AnchorPluralityAnnotation
      hard_reject: boolean
    }

    // The claim artifact is deterministically reconstructible from record_hash.
    const recordHash = 'sha256:' + hexEncode(sha256(canonicalRecord(record)))
    expect(bundle.record_hash).toBe(recordHash)
    expect(expected.anchor_claim_prefix).toBe(ANCHOR_CLAIM_PREFIX)
    expect(expected.anchor_claim_artifact_utf8).toBe(ANCHOR_CLAIM_PREFIX + recordHash)

    // Independent re-verification of the embedded anchoring signature.
    const rekorEl = bundle.log_proofs[1] as AnchorProofElement
    const proof = rekorEl.proof as Record<string, unknown>
    const bodyBytes = b64decode(proof['entry_body_b64'] as string)
    const body = JSON.parse(utf8Decode.decode(bodyBytes)) as Record<string, string>
    const artifactBytes = b64decode(body['artifact_b64'] as string)
    expect(utf8Decode.decode(artifactBytes)).toBe(expected.anchor_claim_artifact_utf8)
    const sigOk = await ed.verifyAsync(
      base64urlDecode(body['signature_b64url'] as string),
      artifactBytes,
      base64urlDecode(body['public_key_b64url'] as string),
    )
    expect(sigOk).toBe(expected.anchoring_signature_verifies)

    // The anchoring key is FRESH: not the record's signing key.
    expect(body['public_key_b64url']).toBe(expected.anchoring_key_b64url)
    expect(body['public_key_b64url'] === record.creator_key).toBe(
      !expected.anchoring_key_differs_from_creator_key,
    )

    // The SET signing input reconstructs byte-for-byte.
    const setInput = sortedJson({
      entry_body_b64: proof['entry_body_b64'] as string,
      integrated_time_ms: proof['integrated_time_ms'] as number,
      log_index: proof['log_index'] as number,
    })
    expect(setInput).toBe(expected.set_signing_input_utf8)

    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('rekor-claim-binding-mismatch: a genuinely-signed claim for another record is an invalid proof, not counted', async () => {
    const c = loadCase('rekor-claim-binding-mismatch')
    const expected = c.expected as unknown as {
      invalid_indices: number[]
      artifact_reconstructs_from_record_hash: boolean
      embedded_signature_verifies_over_its_own_artifact: boolean
      anchor_plurality: AnchorPluralityAnnotation
      hard_reject: boolean
    }
    const bundle = c.input['bundle'] as AnchorProofBundle

    // The embedded signature IS valid over its own (mismatched) artifact.
    const rekorEl = bundle.log_proofs[1] as AnchorProofElement
    const proof = rekorEl.proof as Record<string, unknown>
    const body = JSON.parse(
      utf8Decode.decode(b64decode(proof['entry_body_b64'] as string)),
    ) as Record<string, string>
    const artifactBytes = b64decode(body['artifact_b64'] as string)
    const artifact = utf8Decode.decode(artifactBytes)
    expect(artifact === ANCHOR_CLAIM_PREFIX + bundle.record_hash).toBe(
      expected.artifact_reconstructs_from_record_hash,
    )
    const sigOk = await ed.verifyAsync(
      base64urlDecode(body['signature_b64url'] as string),
      artifactBytes,
      base64urlDecode(body['public_key_b64url'] as string),
    )
    expect(sigOk).toBe(expected.embedded_signature_verifies_over_its_own_artifact)

    // But the binding fails, so the element is invalid and not counted.
    const verdict = await runCaseVerdict(c)
    expect(verdict.invalid_indices).toEqual(expected.invalid_indices)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it("record-signature-digest-path-invalid: the record's own signature cannot ride the digest path", async () => {
    const c = loadCase('record-signature-digest-path-invalid')
    const record = c.input['record'] as AtribRecord
    const expected = c.expected as unknown as {
      record_hash: string
      signature_verifies_over_signing_input: boolean
      signature_verifies_over_full_canonical_record: boolean
      signing_input_differs_from_hashed_bytes: boolean
    }

    const sigBytes = base64urlDecode(record.signature)
    const pubkey = base64urlDecode(record.creator_key)

    // record_hash covers the COMPLETE record INCLUDING the signature (§1.2.3).
    const fullBytes = canonicalRecord(record)
    expect('sha256:' + hexEncode(sha256(fullBytes))).toBe(expected.record_hash)

    // The signature verifies over the signature-less form (§1.4.2)...
    const signingInput = canonicalSigningInput(record)
    expect(await ed.verifyAsync(sigBytes, signingInput, pubkey)).toBe(
      expected.signature_verifies_over_signing_input,
    )

    // ...and does NOT verify over the bytes behind record_hash. This is why a
    // hashedrekord-style upload (data.hash = record_hash, sig = record
    // signature) fails by construction, and why anchors carry a FRESH
    // anchoring signature over the reconstructible claim artifact instead.
    expect(await ed.verifyAsync(sigBytes, fullBytes, pubkey)).toBe(
      expected.signature_verifies_over_full_canonical_record,
    )
    expect(hexEncode(signingInput) !== hexEncode(fullBytes)).toBe(
      expected.signing_input_differs_from_hashed_bytes,
    )
  })

  it('ots-pending-then-upgraded: pending excluded from plurality; in-place upgrade meets it', async () => {
    const c = loadCase('ots-pending-then-upgraded')
    const expected = c.expected as unknown as {
      pending: { anchor_plurality: AnchorPluralityAnnotation; hard_reject: boolean }
      upgraded: { anchor_plurality: AnchorPluralityAnnotation; hard_reject: boolean }
    }

    const pendingVerdict = await runCaseVerdict(c, 'bundle_pending')
    expect(pendingVerdict.anchor_plurality).toEqual(expected.pending.anchor_plurality)
    expect(pendingVerdict.hard_reject).toBe(expected.pending.hard_reject)

    const upgradedVerdict = await runCaseVerdict(c, 'bundle_upgraded')
    expect(upgradedVerdict.anchor_plurality).toEqual(expected.upgraded.anchor_plurality)
    expect(upgradedVerdict.hard_reject).toBe(expected.upgraded.hard_reject)
  })

  it('same-operator-group: independence counts distinct operator groups, not elements', async () => {
    const c = loadCase('same-operator-group')
    const expected = c.expected as unknown as {
      default_grouping: { anchor_plurality: AnchorPluralityAnnotation }
      declared_group: { anchor_plurality: AnchorPluralityAnnotation }
    }

    const defaultVerdict = await runCaseVerdict(c, 'bundle', 'trust_default_grouping')
    expect(defaultVerdict.anchor_plurality).toEqual(expected.default_grouping.anchor_plurality)

    const groupedVerdict = await runCaseVerdict(c, 'bundle', 'trust_declared_group')
    expect(groupedVerdict.anchor_plurality).toEqual(expected.declared_group.anchor_plurality)
    expect(groupedVerdict.anchor_plurality.independent_count).toBe(1)
    expect(groupedVerdict.anchor_plurality.single_anchor).toBe(true)
  })

  it('threshold-not-met: §2.11.4 M=2 rejection unchanged; untrusted proofs surfaced not counted', async () => {
    const c = loadCase('threshold-not-met')
    const expected = c.expected as unknown as {
      trusted_verified_count: number
      cross_log_threshold_not_met: boolean
      untrusted_surfaced: string[]
      anchor_plurality: AnchorPluralityAnnotation
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.trusted_verified_count).toBe(expected.trusted_verified_count)
    expect(verdict.cross_log_threshold_not_met).toBe(expected.cross_log_threshold_not_met)
    expect(verdict.untrusted_surfaced).toEqual(expected.untrusted_surfaced)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('equivocation-detected: §2.11.4 leaf-byte disagreement rejection unchanged, pair surfaced', async () => {
    const c = loadCase('equivocation-detected')
    const expected = c.expected as unknown as {
      cross_log_equivocation_detected: boolean
      disagreeing_pair: AnchorDisagreeingPair
      anchor_plurality: AnchorPluralityAnnotation
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.cross_log_equivocation_detected).toBe(expected.cross_log_equivocation_detected)
    expect(verdict.disagreeing_pair).toEqual(expected.disagreeing_pair)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('censorship-suspected: not-found from a trusted log alongside a verified proof is flagged with the silent log', async () => {
    const c = loadCase('censorship-suspected')
    const expected = c.expected as unknown as {
      cross_log_censorship_suspected: boolean
      silent_log: string
      anchor_plurality: AnchorPluralityAnnotation
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.cross_log_censorship_suspected).toBe(expected.cross_log_censorship_suspected)
    expect(verdict.silent_log).toBe(expected.silent_log)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    // Flag, not reject: censorship suspicion alone is not a hard rejection.
    expect(verdict.hard_reject).toBe(false)
  })

  it('allow-single-anchor-config: producer posture resolves per the precedence rules, never throwing', () => {
    const c = loadCase('allow-single-anchor-config')
    const configs = c.input['configs'] as Array<{ name: string; config: AnchorSetConfig }>
    const expected = c.expected as unknown as {
      resolutions: PostureResolution[]
      never_throws_on_primary_path: boolean
      never_disables_signing: boolean
    }

    const resolutions = configs.map(({ name, config }) => ({
      name,
      ...resolveAnchorPosture(config),
    }))
    expect(resolutions).toEqual(expected.resolutions)
    expect(expected.never_throws_on_primary_path).toBe(true)
    expect(expected.never_disables_signing).toBe(true)
  })
})
