// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §5.5.7 conformance: universal evidence envelope (P042 ADR).
 *
 * Loads each committed case from spec/conformance/evidence-envelope/cases/
 * (never the generator) and asserts the expected invariants. The corpus is
 * regenerated by
 * packages/log-dev/scripts/generate-conformance-evidence-envelope.ts.
 *
 * This file is the reference consumer implementation. It exercises the REAL
 * @atrib/verify library surface promoted from this suite's former inline
 * logic (packages/verify/src/evidence-envelope.ts):
 *   - the envelope shape checker `validateEnvelope` (closed tier + ref.kind
 *     enums, hash format, inline/ref.kind coupling, record_hash sibling rule),
 *   - the profile registration classifier `classifyProfile` (absolute HTTPS
 *     type URIs, full-URI profile identity),
 *   - the deterministic `mapLegacyEvidenceBlock` mapping for the frozen
 *     five-protocol legacy set,
 *   - instance-scoped tier semantics (`orderEnvelopeInstances`,
 *     `isRelayIdentitySwap`, `assessReproducibility`),
 * and recomputes every committed hash with the library's `jcsSha256` /
 * `rawSha256` (real `canonicalize`, RFC 8785), cross-checking the
 * generator's JCS implementation through the committed vectors. The
 * never-flips-valid case drives the actual verifyRecord() path.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  canonicalRecord,
  hexEncode,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'
import { verifyRecord } from '../src/verify-record.js'
import type { AuthorizationEvidenceInput } from '../src/authorization-evidence.js'
import {
  ATRIB_PROFILE_BASE,
  EVIDENCE_REF_KINDS,
  EVIDENCE_TIERS,
  LEGACY_PROTOCOL_TO_PROFILE,
  assessReproducibility,
  classifyProfile as libClassifyProfile,
  isRelayIdentitySwap as libIsRelayIdentitySwap,
  jcsSha256 as libJcsSha256,
  mapLegacyEvidenceBlock,
  orderEnvelopeInstances,
  rawSha256 as libRawSha256,
  renderEnvelopeOpaque,
  validateEnvelope,
  type EvidenceEnvelope,
  type EvidenceTier as LibEvidenceTier,
  type LegacyEvidenceBlock,
} from '../src/evidence-envelope.js'

const CORPUS = join(__dirname, '../../../spec/conformance/evidence-envelope')
const CASES = join(CORPUS, 'cases')

const utf8 = new TextEncoder()

// ─── Fixture loading ───────────────────────────────────────────────────

interface CaseFile {
  name: string
  spec_section: string
  family: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(family: string, name: string): CaseFile {
  return JSON.parse(readFileSync(join(CASES, `${family}--${name}.json`), 'utf8')) as CaseFile
}

interface Manifest {
  spec_section: string
  tier_enum: string[]
  ref_kind_enum: string[]
  atrib_profile_registry: string[]
  frozen_legacy_protocols: string[]
  legacy_protocol_to_profile: Record<string, string>
  families: string[]
  cases: { file: string; name: string; family: string }[]
}

const manifest = JSON.parse(readFileSync(join(CORPUS, 'manifest.json'), 'utf8')) as Manifest

// ─── Library adapters (thin wrappers over the real @atrib/verify exports) ─
//
// The reference-model logic this suite formerly re-implemented inline now
// lives in packages/verify/src/evidence-envelope.ts. These aliases keep the
// test bodies unchanged while routing every assertion through the REAL
// exports, so the corpus verifies the shipped library, not a private copy.

const TIERS = EVIDENCE_TIERS
const REF_KINDS = EVIDENCE_REF_KINDS

type EvidenceTier = LibEvidenceTier
type LegacyBlockLike = LegacyEvidenceBlock

// Loose fixture-cast shape (fixtures are arbitrary JSON, validated by the
// library's `validateEnvelope`, which accepts `unknown`).
interface EnvelopeLike {
  envelope?: unknown
  profile?: unknown
  profile_version?: unknown
  tier?: unknown
  payload?: {
    hash?: unknown
    media_type?: unknown
    ref?: { kind?: unknown; uri?: unknown; record_hash?: unknown }
    inline?: unknown
  }
  facts?: unknown
  result?: {
    valid?: unknown
    constraints?: unknown
    errors?: unknown
    warnings?: unknown
  }
  verifier?: { name?: unknown; version?: unknown; checked_at_ms?: unknown }
}

/** §5.5.7 shape checker → the library's `validateEnvelope`. Empty = accept. */
function checkEnvelopeShape(envelope: EnvelopeLike): string[] {
  return validateEnvelope(envelope).reasons
}

/** Profile registration classifier → the library's `classifyProfile`. */
function classifyProfile(uri: string, registry: string[]) {
  return libClassifyProfile(uri, registry)
}

// Real RFC 8785 hashing, re-exported from the library.
const jcsSha256 = libJcsSha256
const rawSha256 = libRawSha256

/** Deterministic legacy → envelope mapping (spec name: fromLegacyEvidenceBlock). */
function referenceFromLegacyEvidenceBlock(block: LegacyBlockLike): EvidenceEnvelope {
  return mapLegacyEvidenceBlock(block)
}

interface TierInstance {
  tier: EvidenceTier
  verifier?: { name: string; checked_at_ms?: number }
}

/** Consumer ordering → the library's `orderEnvelopeInstances`. */
function orderInstances<T extends TierInstance>(instances: T[]): T[] {
  return orderEnvelopeInstances(instances as unknown as EvidenceEnvelope[]) as unknown as T[]
}

/** Relay-swap detector → the library's `isRelayIdentitySwap`. */
function isRelayIdentitySwap(
  original: Record<string, unknown>,
  relayed: Record<string, unknown>,
): boolean {
  return libIsRelayIdentitySwap(original, relayed)
}

// ─── Tests ─────────────────────────────────────────────────────────────

describe('spec §5.5.7 conformance: manifest', () => {
  it('pins the closed enums, the frozen legacy protocol set, and every committed case', () => {
    expect(manifest.spec_section).toBe('5.5.7')
    expect(manifest.tier_enum).toEqual([...TIERS])
    expect(manifest.ref_kind_enum).toEqual([...REF_KINDS])
    // The legacy protocol string set is frozen at exactly five rows.
    expect(manifest.frozen_legacy_protocols).toHaveLength(5)
    expect(manifest.legacy_protocol_to_profile).toEqual(LEGACY_PROTOCOL_TO_PROFILE)
    // Every manifest case exists on disk and self-describes.
    for (const entry of manifest.cases) {
      const parsed = JSON.parse(readFileSync(join(CORPUS, entry.file), 'utf8')) as CaseFile
      expect(parsed.name).toBe(entry.name)
      expect(parsed.family).toBe(entry.family)
      expect(parsed.spec_section).toBe('5.5.7')
    }
  })
})

describe('spec §5.5.7 conformance: shape/', () => {
  it('minimal-valid: smallest well-formed envelope accepted; payload hash recomputes over JCS', () => {
    const c = loadCase('shape', 'minimal-valid')
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])
    expect(jcsSha256(c.input.payload_material)).toBe(c.expected.payload_hash)
    expect((envelope.payload as { hash: string }).hash).toBe(c.expected.payload_hash)
  })

  it('maximal-valid: every optional field accepted; inline payload matches its hash commitment', () => {
    const c = loadCase('shape', 'maximal-valid')
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])
    const payload = envelope.payload as { hash: string; inline: unknown; ref: { kind: string } }
    expect(payload.ref.kind).toBe('inline')
    // inline bytes recompute to the committed hash: hash rule for JSON
    // media types is sha256 over JCS bytes.
    expect(jcsSha256(payload.inline)).toBe(c.expected.payload_hash)
    expect(payload.hash).toBe(c.expected.payload_hash)
    expect(jcsSha256(c.input.payload_material)).toBe(c.expected.payload_hash)
  })

  it.each([
    ['missing-tier'],
    ['missing-payload-hash'],
    ['invalid-tier-value'],
    ['invalid-hash-prefix'],
    ['inline-with-non-inline-ref'],
    ['record-kind-rejected'],
  ])('%s: rejected with the pinned reasons', (name) => {
    const c = loadCase('shape', name)
    const reasons = checkEnvelopeShape(c.input.envelope as EnvelopeLike)
    expect(c.expected.accept).toBe(false)
    for (const expectedReason of c.expected.reject_reasons as string[]) {
      expect(reasons).toContain(expectedReason)
    }
  })

  it('record-hash-sibling: record payload spells ref.record_hash beside a retrievability kind, and the real record round-trips', async () => {
    const c = loadCase('shape', 'record-hash-sibling')
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])

    const record = c.input.referenced_record as AtribRecord
    // The referenced record carries a genuine Ed25519 signature.
    expect(await verifyRecordSignature(record)).toBe(c.expected.referenced_record_signature_ok)

    // payload.hash commits to the record's canonical JCS bytes.
    const recordHash = 'sha256:' + hexEncode(sha256(canonicalRecord(record)))
    expect(recordHash).toBe(c.expected.record_hash)
    const payload = envelope.payload as { hash: string; ref: { kind: string; record_hash: string } }
    expect(payload.hash).toBe(recordHash)
    expect(payload.ref.record_hash).toBe(recordHash)
    // "record" is not a kind; the retrievability axis stays independent.
    expect(REF_KINDS as readonly string[]).toContain(payload.ref.kind)
    expect(payload.ref.kind).not.toBe('record')
  })
})

describe('spec §5.5.7 conformance: registry/', () => {
  it.each([
    ['atrib-profile-registered'],
    ['third-party-profile'],
    ['foreign-domain-collision'],
  ])('%s: classified by full URI against the atrib registry', (name) => {
    const c = loadCase('registry', name)
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])
    const classification = classifyProfile(
      envelope.profile as string,
      c.input.atrib_profile_registry as string[],
    )
    expect(classification.uri_valid).toBe(c.expected.uri_valid)
    expect(classification.atrib_maintained).toBe(c.expected.atrib_maintained)
    expect(classification.registered).toBe(c.expected.registered)
    expect(classification.treat_as).toBe(c.expected.treat_as)
  })

  it.each([['non-https-profile-rejected'], ['bare-name-profile-rejected']])(
    '%s: rejected on profile_uri',
    (name) => {
      const c = loadCase('registry', name)
      const reasons = checkEnvelopeShape(c.input.envelope as EnvelopeLike)
      expect(c.expected.accept).toBe(false)
      for (const expectedReason of c.expected.reject_reasons as string[]) {
        expect(reasons).toContain(expectedReason)
      }
      const classification = classifyProfile(
        (c.input.envelope as EnvelopeLike).profile as string,
        manifest.atrib_profile_registry,
      )
      expect(classification.uri_valid).toBe(false)
    },
  )

  it('foreign-domain-collision never resolves to the atrib profile of the same name', () => {
    const c = loadCase('registry', 'foreign-domain-collision')
    const profile = (c.input.envelope as EnvelopeLike).profile as string
    expect(profile.endsWith('/oauth2')).toBe(true)
    expect(profile).not.toBe(`${ATRIB_PROFILE_BASE}oauth2`)
    const classification = classifyProfile(profile, manifest.atrib_profile_registry)
    expect(classification.atrib_maintained).toBe(false)
    expect(classification.treat_as).toBe('unknown-preserve')
  })
})

describe('spec §5.5.7 conformance: unknown-profile/', () => {
  it('unknown-profile-preserved: round-trips byte-identical (JCS hash pinned) and renders opaquely', () => {
    const c = loadCase('unknown-profile', 'unknown-profile-preserved')
    const envelope = c.input.envelope as EnvelopeLike
    // The shape is valid even though the profile is unknown.
    expect(checkEnvelopeShape(envelope)).toEqual([])
    // Consumer pass-through MUST NOT mutate the envelope: the JCS hash of
    // the whole envelope after the consumer's preserve path equals the
    // committed hash. (The reference preserve path is the identity.)
    const preserved = envelope
    expect(jcsSha256(preserved)).toBe(c.expected.round_trip_jcs_sha256)
    // Payload hash recomputes over raw bytes (non-JSON media type rule).
    expect(rawSha256(c.input.payload_material_utf8 as string)).toBe(
      (envelope.payload as { hash: string }).hash,
    )
    // The opaque rendering surface: profile URI, tier, payload hash. The
    // library's `renderEnvelopeOpaque` extracts exactly these safe fields.
    const opaque = c.expected.opaque_render as {
      profile: string
      tier: string
      payload_hash: string
    }
    const rendered = renderEnvelopeOpaque(preserved as unknown as EvidenceEnvelope)
    expect(rendered.profile).toBe(opaque.profile)
    expect(rendered.tier).toBe(opaque.tier)
    expect(rendered.payload_hash).toBe(opaque.payload_hash)
    expect(envelope.profile).toBe(opaque.profile)
    expect(envelope.tier).toBe(opaque.tier)
    expect((envelope.payload as { hash: string }).hash).toBe(opaque.payload_hash)
  })

  it('unknown-profile-never-dropped: mixed known/unknown evidence lists keep every entry in order', () => {
    const c = loadCase('unknown-profile', 'unknown-profile-never-dropped')
    const list = c.input.evidence_list as EnvelopeLike[]
    // The reference consumer's storage/relay path keeps all entries.
    const kept = list.filter((envelope) => checkEnvelopeShape(envelope).length === 0)
    expect(kept).toHaveLength(c.expected.preserved_count as number)
    expect(kept.map((envelope) => envelope.profile)).toEqual(c.expected.profiles_in_order)
    expect(c.expected.drop_forbidden).toBe(true)
  })
})

describe('spec §5.5.7 conformance: legacy-mapping/', () => {
  it.each([
    ['legacy-oauth2'],
    ['legacy-mcp-oauth'],
    ['legacy-aauth'],
    ['legacy-x401'],
    ['legacy-ap2-vi'],
  ])('%s: independent mapping implementation reproduces the committed envelope exactly', (name) => {
    const c = loadCase('legacy-mapping', name)
    const block = c.input.legacy_block as unknown as LegacyBlockLike
    const mapped = referenceFromLegacyEvidenceBlock(block)
    // Two implementations (generator in @atrib/log-dev, this reference in
    // @atrib/verify) MUST produce identical envelopes.
    expect(mapped).toEqual(c.expected.envelope)
    // The mapped envelope is itself well-formed.
    expect(checkEnvelopeShape(mapped as EnvelopeLike)).toEqual([])
    // Pinned hashes recompute with the real RFC 8785 implementation.
    expect(jcsSha256(block)).toBe(c.expected.payload_hash)
    if (block.details !== undefined) {
      expect(jcsSha256(block.details)).toBe(c.expected.details_hash)
    }
    // The mapping never inserts the mapper's identity (tier rule 2).
    expect('verifier' in mapped).toBe(false)
    // Legacy result semantics survive the mapping unchanged.
    expect((mapped['result'] as { valid: boolean }).valid).toBe(block.valid)
  })

  it('legacy-unknown-protocol-rejected: the frozen five-row table rejects a sixth protocol string', () => {
    const c = loadCase('legacy-mapping', 'legacy-unknown-protocol-rejected')
    const block = c.input.legacy_block as unknown as LegacyBlockLike
    expect(c.expected.mapping_must_reject).toBe(true)
    expect(() => referenceFromLegacyEvidenceBlock(block)).toThrow(/unknown legacy evidence protocol/)
    expect(c.expected.frozen_protocols).toEqual(Object.keys(LEGACY_PROTOCOL_TO_PROFILE))
    expect(Object.keys(LEGACY_PROTOCOL_TO_PROFILE)).toHaveLength(5)
  })
})

describe('spec §5.5.7 conformance: tier/', () => {
  it('tier-ladder-all-four: one payload at all four tiers shares an identity key and orders tier-descending', () => {
    const c = loadCase('tier', 'tier-ladder-all-four')
    const envelopes = c.input.envelopes as (EnvelopeLike & TierInstance)[]
    expect(envelopes).toHaveLength(4)

    const expectedHash = c.expected.payload_hash as string
    // Raw-bytes hash rule for application/jwt payloads.
    expect(rawSha256(c.input.payload_material_utf8 as string)).toBe(expectedHash)

    const identityKey = c.expected.identity_key as { profile: string; payload_hash: string }
    for (const envelope of envelopes) {
      expect(checkEnvelopeShape(envelope)).toEqual([])
      expect(envelope.profile).toBe(identityKey.profile)
      expect((envelope.payload as { hash: string }).hash).toBe(identityKey.payload_hash)
    }

    const ordered = orderInstances(envelopes)
    expect(ordered.map((envelope) => envelope.tier)).toEqual(c.expected.tier_order_descending)
  })

  it('relay-identity-swap-rejected: a relayed instance differing only in verifier identity is flagged', () => {
    const c = loadCase('tier', 'relay-identity-swap-rejected')
    const original = c.input.original as Record<string, unknown>
    const relayed = c.input.relayed as Record<string, unknown>
    expect(isRelayIdentitySwap(original, relayed)).toBe(c.expected.relay_violation)
    // A genuinely re-verified instance (its own verifier AND its own
    // checked_at_ms / result evidence) is NOT a swap.
    const reverified = {
      ...relayed,
      verifier: { name: 'relay.example', checked_at_ms: 9999999999999 },
    }
    expect(isRelayIdentitySwap(original, reverified)).toBe(true) // body unchanged: still a relay
    const reverifiedWithNewChecks = {
      ...relayed,
      tier: 'shape',
      verifier: { name: 'relay.example', checked_at_ms: 9999999999999 },
    }
    expect(isRelayIdentitySwap(original, reverifiedWithNewChecks)).toBe(false)
  })

  it('verified-withheld-not-reproducible: well-formed but reported claimed-not-reproducible', () => {
    const c = loadCase('tier', 'verified-withheld-not-reproducible')
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])
    expect(envelope.tier).toBe('verified')
    // The library's `assessReproducibility` reports the §2.12.7 ladder posture.
    const assessment = assessReproducibility(envelope as unknown as EvidenceEnvelope)
    expect(assessment.reproducible).toBe(c.expected.reproducible)
    expect(assessment.report).toBe(c.expected.report)
    expect(c.expected.report).toBe('claimed-not-reproducible')
  })

  it('evidence-never-flips-valid: failing evidence leaves verifyRecord().valid true, and the mapped envelope carries the failure', async () => {
    const c = loadCase('tier', 'evidence-never-flips-valid')
    const record = c.input.record as AtribRecord

    // The record itself is genuinely signed.
    expect(await verifyRecordSignature(record)).toBe(c.expected.signature_ok)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(record)))).toBe(c.input.record_hash)

    // Drive the real @atrib/verify path with the failing OAuth evidence.
    const result = await verifyRecord(record, {
      authorizationEvidence: c.input.authorization_evidence as AuthorizationEvidenceInput[],
    })

    // The load-bearing invariant: evidence never flips record validity.
    expect(result.valid).toBe(c.expected.record_valid)
    expect(result.signatureOk).toBe(c.expected.signature_ok)
    expect(result.evidence).toHaveLength(c.expected.evidence_count as number)
    expect(result.evidence!.map((block) => block.valid)).toEqual(c.expected.evidence_valid)

    // The failing legacy block maps to an envelope that carries the
    // failure in result.valid, at tier 'attested', under the frozen
    // profile URI, while the record verification above stays untouched.
    const block = result.evidence![0]!
    const mapped = referenceFromLegacyEvidenceBlock(block as unknown as LegacyBlockLike)
    expect((mapped['result'] as { valid: boolean }).valid).toBe(
      c.expected.mapped_envelope_result_valid,
    )
    expect(mapped['tier']).toBe(c.expected.mapped_envelope_tier)
    expect(mapped['profile']).toBe(c.expected.mapped_envelope_profile)
    expect(checkEnvelopeShape(mapped as EnvelopeLike)).toEqual([])
  })
})

describe('spec §5.5.7 conformance: continuation-packet/', () => {
  it('baton-envelope-valid: ninth registered profile; raw-bytes hash over the packet; baton record signature verifies', async () => {
    const c = loadCase('continuation-packet', 'baton-envelope-valid')
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])

    const cls = classifyProfile(
      envelope.profile as string,
      c.input.atrib_profile_registry as string[],
    )
    expect(cls.registered).toBe(c.expected.registered)
    expect(cls.atrib_maintained).toBe(c.expected.atrib_maintained)

    // Raw-bytes hash rule for text/markdown packets.
    expect(rawSha256(c.input.packet_material_utf8 as string)).toBe(
      (envelope.payload as { hash: string }).hash,
    )

    const baton = c.input.referenced_baton_record as AtribRecord
    expect(await verifyRecordSignature(baton)).toBe(c.expected.referenced_baton_record_signature_ok)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(baton)))).toBe(c.expected.baton_record_hash)
    expect((envelope.facts as Record<string, string>).baton_record_hash).toBe(
      c.expected.baton_record_hash,
    )
  })

  it('packet-hash-mismatch: shape-valid envelope whose hash does not match the packet bytes fails profile verification', () => {
    const c = loadCase('continuation-packet', 'packet-hash-mismatch')
    const envelope = c.input.envelope as EnvelopeLike
    // The envelope itself is shape-valid; the mismatch is profile-level.
    expect(checkEnvelopeShape(envelope)).toEqual([])
    expect(rawSha256(c.input.packet_material_utf8 as string)).not.toBe(
      (envelope.payload as { hash: string }).hash,
    )
    expect(c.expected.accept).toBe(false)
    expect(c.expected.reject_reasons).toEqual(['payload_hash_mismatch'])
  })

  it('withheld-packet-declared: public projection carries hash and role-term facts, never the packet body', () => {
    const c = loadCase('continuation-packet', 'withheld-packet-declared')
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])
    expect((envelope.payload as { ref: { kind: string } }).ref.kind).toBe('withheld')
    expect(envelope.payload!.inline).toBeUndefined()
    // Exactly the profile's sanitization-contract facts, nothing else.
    expect(Object.keys(envelope.facts as Record<string, unknown>).sort()).toEqual(
      c.expected.public_facts,
    )
  })

  it('signed-baton-record: the baton-pass observation as payload via the record_hash sibling rule', async () => {
    const c = loadCase('continuation-packet', 'signed-baton-record')
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])

    const record = c.input.referenced_record as AtribRecord
    const recomputed = 'sha256:' + hexEncode(sha256(canonicalRecord(record)))
    expect(recomputed).toBe(c.expected.record_hash)
    expect((envelope.payload as { hash: string }).hash).toBe(recomputed)
    expect((envelope.payload as { ref: { record_hash: string } }).ref.record_hash).toBe(recomputed)
    expect(await verifyRecordSignature(record)).toBe(c.expected.referenced_record_signature_ok)
  })
})

describe('spec §5.5.7 conformance: payments envelopes', () => {
  it.each([
    ['payments-detection', 'detection-envelope-valid'],
    ['payments-settlement', 'recommendation-envelope-valid'],
  ])('%s/%s: the payments profile accepts the committed envelope', (family, name) => {
    const c = loadCase(family, name)
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])
    expect(jcsSha256(c.input.payload_material)).toBe((envelope.payload as { hash: string }).hash)
    const profile = classifyProfile(
      envelope.profile as string,
      c.input.atrib_profile_registry as string[],
    )
    expect(profile.registered).toBe(c.expected.registered)
    expect(profile.atrib_maintained).toBe(c.expected.atrib_maintained)
  })

  it.each([
    ['payments-detection', 'detection-payload-hash-mismatch'],
    ['payments-settlement', 'tampered-recommendation-rejected'],
  ])('%s/%s: profile payload mismatches remain visible', (family, name) => {
    const c = loadCase(family, name)
    const envelope = c.input.envelope as EnvelopeLike
    expect(checkEnvelopeShape(envelope)).toEqual([])
    expect(jcsSha256(c.input.payload_material)).not.toBe((envelope.payload as { hash: string }).hash)
    expect(c.expected.accept).toBe(false)
  })
})
