// SPDX-License-Identifier: Apache-2.0

/**
 * session_checkpoint conformance (D139, spec §1.2.10).
 *
 * Loads each case from spec/conformance/session-checkpoint/cases/ and
 * asserts the expected invariants. The corpus itself is regenerated by
 * packages/log-dev/scripts/generate-conformance-session-checkpoint.ts;
 * this test consumes the COMMITTED vectors (never the generator) and
 * exercises the shipped verifier implementation in
 * packages/verify/src/session-checkpoint.ts — structural validation, root
 * recomputation, consistency-proof verification, equivocation detection,
 * freshness tiering, and the composed verifySessionCheckpointRecord —
 * plus the @atrib/mcp signing/entry primitives for canonical-form and
 * byte/URI-duality checks.
 *
 * Families:
 *   schema-*                checkpoint object presence rules (required on
 *                           session_checkpoint, rejected elsewhere; the
 *                           §1.2.7 / §1.2.9 pattern)
 *   tree-*                  real RFC 6962 roots over ordered record-hash
 *                           leaves (§2.3.2 leaf rule, raw 32-byte preimages)
 *   consistency-*           append-only extension + equivocation pair
 *   retroactive-* and freshness-*  present-only-when-true flag, absence-not-null,
 *                           categorical freshness facts
 *   byte-uri-duality        0xFF vs 0x08 log-entry encodings over
 *                           byte-identical signed records
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  canonicalSigningInput,
  hexDecode,
  hexEncode,
  leafHash,
  serializeEntry,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'
import {
  checkConsecutiveSessionCheckpoints,
  detectSessionCheckpointEquivocation,
  recomputeSessionRoot,
  recomputeSessionRootFromLeafBytes,
  sessionCheckpointArgsHash,
  sessionCheckpointFreshness,
  sessionCheckpointRecordHash,
  sessionLeafBytes,
  validateSessionCheckpointStructural,
  verifySessionCheckpointRecord,
  verifySessionConsistencyProof,
  type SessionCheckpointRecord,
} from '../src/session-checkpoint.js'

const CORPUS = join(__dirname, '../../../spec/conformance/session-checkpoint/cases')

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

function recordHashHex(record: AtribRecord): string {
  return sessionCheckpointRecordHash(record).slice('sha256:'.length)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('session_checkpoint conformance (§1.2.10)', () => {
  it('schema-first-checkpoint: valid first checkpoint, JCS slot, root, freshness', async () => {
    const c = loadCase('schema-first-checkpoint')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      record_hash_hex: string
      session_root: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      verifier_freshness_fact: string
    }

    // Canonical signing input matches the spec-mandated JCS form.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(record))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)

    // JCS slot: `checkpoint` sorts after `chain_root` and before `content_id`.
    const chainRootIdx = signingInput.indexOf('"chain_root"')
    const checkpointIdx = signingInput.indexOf('"checkpoint"')
    const contentIdIdx = signingInput.indexOf('"content_id"')
    expect(chainRootIdx).toBeGreaterThanOrEqual(0)
    expect(checkpointIdx).toBeGreaterThan(chainRootIdx)
    expect(contentIdIdx).toBeGreaterThan(checkpointIdx)

    // record_hash and signature.
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)
    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)

    // First-checkpoint presence rules: no prior_checkpoint, first_index 0.
    expect(record.checkpoint!.first_index).toBe(0)
    expect('prior_checkpoint' in record.checkpoint!).toBe(false)
    expect('retroactive' in record.checkpoint!).toBe(false)

    // Real RFC 6962 root over the ordered record-hash leaves.
    expect(recomputeSessionRoot(leaves)).toBe(expected.session_root)
    expect(record.checkpoint!.session_root).toBe(expected.session_root)

    // Leaves ARE the covered records' canonical hashes.
    const leafRecords = c.input.leaf_records as AtribRecord[]
    leafRecords.forEach((leafRecord, i) => {
      expect(sessionCheckpointRecordHash(leafRecord)).toBe(leaves[i])
    })

    // args_hash commits the flat leaf list per D099: sha256(JCS({leaves})).
    expect(record.args_hash).toBe(sessionCheckpointArgsHash(leaves))

    // Structural validation accepts; freshness is contemporaneous.
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
    expect(expected.validator_should_accept).toBe(true)
    const maxLeafTs = c.input.max_covered_leaf_timestamp as number
    expect(sessionCheckpointFreshness(record, maxLeafTs)).toBe(expected.verifier_freshness_fact)

    // Composed verifier: every fact from one call.
    const verification = await verifySessionCheckpointRecord(record, {
      leaves,
      maxCoveredLeafTimestamp: maxLeafTs,
    })
    expect(verification.signatureOk).toBe(expected.verifier_signature_ok)
    expect(verification.recordHash).toBe(`sha256:${expected.record_hash_hex}`)
    expect(verification.structuralRejection).toBeUndefined()
    expect(verification.rootMatchesLeaves).toBe(true)
    expect(verification.argsHashMatchesLeaves).toBe(true)
    expect(verification.freshness).toBe(expected.verifier_freshness_fact)
  })

  it.each([
    ['schema-missing-checkpoint-rejected'],
    ['schema-checkpoint-on-wrong-event-type-rejected'],
    ['schema-first-index-bounds-rejected'],
    ['schema-prior-present-at-first-index-zero-rejected'],
    ['schema-prior-absent-at-positive-first-index-rejected'],
    ['tree-empty-rejected'],
    ['retroactive-false-rejected'],
  ])('%s: signature valid, structural validation rejects with the pinned reason', async (name) => {
    const c = loadCase(name)
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      record_hash_hex: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      rejection_reason: string
    }

    // Signature itself verifies; rejection is at the policy layer.
    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)

    // Structural validation MUST reject with the pinned reason.
    expect(expected.validator_should_accept).toBe(false)
    expect(validateSessionCheckpointStructural(record)).toBe(expected.rejection_reason)

    // The composed verifier carries the same rejection alongside the
    // still-valid signature.
    const verification = await verifySessionCheckpointRecord(record)
    expect(verification.signatureOk).toBe(expected.verifier_signature_ok)
    expect(verification.structuralRejection).toBe(expected.rejection_reason)
  })

  it('tree-1-leaf: root over a single leaf equals sha256(0x00 || leaf_bytes)', async () => {
    const c = loadCase('tree-1-leaf')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const expected = c.expected as {
      session_root_hex: string
      leaf_hash_equals_root: boolean
      verifier_signature_ok: boolean
    }

    expect(leaves).toHaveLength(1)
    expect(recomputeSessionRoot(leaves)).toBe(`sha256:${expected.session_root_hex}`)
    expect(record.checkpoint!.session_root).toBe(`sha256:${expected.session_root_hex}`)
    expect(record.checkpoint!.tree_size).toBe(1)

    // MTH([x]) = leaf_hash(x): the single-leaf root IS the leaf hash.
    const single = hexEncode(leafHash(sessionLeafBytes(leaves[0]!)))
    expect(single === expected.session_root_hex).toBe(expected.leaf_hash_equals_root)

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
  })

  it('tree-2-leaves: two-leaf root; hex-string leaves MUST NOT reproduce it', async () => {
    const c = loadCase('tree-2-leaves')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const expected = c.expected as {
      session_root_hex: string
      hex_string_leaf_root_hex: string
      hex_string_leaf_root_must_not_match: boolean
    }

    expect(leaves).toHaveLength(2)
    expect(recomputeSessionRoot(leaves)).toBe(`sha256:${expected.session_root_hex}`)
    expect(record.checkpoint!.session_root).toBe(`sha256:${expected.session_root_hex}`)

    // Raw-32-byte-leaf trap: a tree over the UTF-8 bytes of the prefixed
    // hex strings produces a DIFFERENT root. Leaves are raw hash bytes.
    const utf8 = new TextEncoder()
    const trapRoot = recomputeSessionRootFromLeafBytes(leaves.map((ref) => utf8.encode(ref)))
    expect(trapRoot).toBe(`sha256:${expected.hex_string_leaf_root_hex}`)
    expect(trapRoot !== `sha256:${expected.session_root_hex}`).toBe(
      expected.hex_string_leaf_root_must_not_match,
    )
  })

  it('tree-5-leaves: odd unbalanced root; prior checkpoint is a leaf, never itself', async () => {
    const c = loadCase('tree-5-leaves')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const priorRecord = c.input.prior_checkpoint_record as SessionCheckpointRecord
    const expected = c.expected as {
      session_root_hex: string
      prior_checkpoint_is_leaf_at_index: number
      verifier_signature_ok: boolean
    }

    expect(leaves).toHaveLength(5)
    expect(recomputeSessionRoot(leaves)).toBe(`sha256:${expected.session_root_hex}`)
    expect(record.checkpoint!.session_root).toBe(`sha256:${expected.session_root_hex}`)
    expect(record.checkpoint!.tree_size).toBe(5)

    // The prior checkpoint appears as a leaf in the NEXT tree (self-exclusion:
    // a checkpoint's own hash depends on session_root, so it can never be
    // a leaf of its own tree).
    const priorHash = sessionCheckpointRecordHash(priorRecord)
    expect(leaves[expected.prior_checkpoint_is_leaf_at_index]).toBe(priorHash)
    expect(leaves).not.toContain(sessionCheckpointRecordHash(record))

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
  })

  it('tree-empty-rejected: RFC 6962 empty-tree root sentinel is pinned', () => {
    const c = loadCase('tree-empty-rejected')
    const expected = c.expected as { rfc6962_empty_tree_root_hex: string }
    // MTH([]) = SHA-256("") per RFC 6962; atrib prohibits committing to it.
    expect(hexEncode(sha256(new Uint8Array(0)))).toBe(expected.rfc6962_empty_tree_root_hex)
    expect(recomputeSessionRootFromLeafBytes([])).toBe(
      `sha256:${expected.rfc6962_empty_tree_root_hex}`,
    )
  })

  it('consistency-valid-extension: append-only K1 → K2 with a verifying §2.1.4 proof', async () => {
    const c = loadCase('consistency-valid-extension')
    const k1 = c.input.first_checkpoint as SessionCheckpointRecord
    const k2 = c.input.second_checkpoint as SessionCheckpointRecord
    const firstLeaves = c.input.first_leaves as string[]
    const secondLeaves = c.input.second_leaves as string[]
    const proofHex = c.input.consistency_proof_hex as string[]
    const expected = c.expected as {
      first_record_hash: string
      prior_checkpoint_matches: boolean
      first_index_equals_prior_tree_size: boolean
      consistency_proof_verifies: boolean
      append_only: boolean
    }

    // Both records are genuinely signed and structurally valid.
    expect(await verifyRecordSignature(k1)).toBe(true)
    expect(await verifyRecordSignature(k2)).toBe(true)
    expect(validateSessionCheckpointStructural(k1)).toBeUndefined()
    expect(validateSessionCheckpointStructural(k2)).toBeUndefined()

    // Full consecutive-checkpoint verdict from the shipped checker.
    const proof = proofHex.map(hexDecode)
    const check = checkConsecutiveSessionCheckpoints(k1, k2, {
      firstLeaves,
      secondLeaves,
      consistencyProof: proof,
    })
    expect(sessionCheckpointRecordHash(k1)).toBe(expected.first_record_hash)
    expect(check.priorCheckpointMatches).toBe(expected.prior_checkpoint_matches)
    expect(check.firstIndexMatchesPriorTreeSize).toBe(expected.first_index_equals_prior_tree_size)
    expect(check.appendOnly).toBe(expected.append_only)
    expect(check.firstRootRecomputes).toBe(true)
    expect(check.secondRootRecomputes).toBe(true)
    expect(check.consistencyProofVerifies).toBe(expected.consistency_proof_verifies)
    expect(check.consistent).toBe(true)
    expect(check.equivocation).toBeUndefined()

    // Append-only: the leaf prefix 0..K1.tree_size-1 is identical.
    expect(secondLeaves.slice(0, k1.checkpoint!.tree_size)).toEqual(firstLeaves)

    // Roots recompute from the committed leaf lists.
    expect(recomputeSessionRoot(firstLeaves)).toBe(k1.checkpoint!.session_root)
    expect(recomputeSessionRoot(secondLeaves)).toBe(k2.checkpoint!.session_root)

    // The committed RFC 6962 §2.1.4 consistency proof verifies from
    // (K1.session_root, 2) to (K2.session_root, 5).
    expect(
      verifySessionConsistencyProof({
        firstTreeSize: k1.checkpoint!.tree_size,
        secondTreeSize: k2.checkpoint!.tree_size,
        firstRoot: k1.checkpoint!.session_root,
        secondRoot: k2.checkpoint!.session_root,
        proof,
      }),
    ).toBe(expected.consistency_proof_verifies)

    // Tamper check: a truncated proof MUST NOT verify.
    expect(
      verifySessionConsistencyProof({
        firstTreeSize: k1.checkpoint!.tree_size,
        secondTreeSize: k2.checkpoint!.tree_size,
        firstRoot: k1.checkpoint!.session_root,
        secondRoot: k2.checkpoint!.session_root,
        proof: proof.slice(0, proof.length - 1),
      }),
    ).toBe(false)
  })

  it('consistency-equivocation-pair: same prior, divergent roots → equivocation fact', async () => {
    const c = loadCase('consistency-equivocation-pair')
    const a = c.input.first_variant as SessionCheckpointRecord
    const b = c.input.second_variant as SessionCheckpointRecord
    const aLeaves = c.input.first_variant_leaves as string[]
    const bLeaves = c.input.second_variant_leaves as string[]
    const expected = c.expected as {
      both_signatures_verify: boolean
      same_creator_key: boolean
      same_prior_checkpoint: boolean
      roots_diverge: boolean
      equivocation: boolean
    }

    // Both signatures are genuine: the pair itself is the evidence.
    expect((await verifyRecordSignature(a)) && (await verifyRecordSignature(b))).toBe(
      expected.both_signatures_verify,
    )
    expect(a.creator_key === b.creator_key).toBe(expected.same_creator_key)
    expect(
      a.checkpoint!.prior_checkpoint === b.checkpoint!.prior_checkpoint &&
        a.checkpoint!.prior_checkpoint === (c.input.shared_prior_checkpoint as string),
    ).toBe(expected.same_prior_checkpoint)

    // Each root recomputes from its own committed leaf list, yet they diverge.
    expect(recomputeSessionRoot(aLeaves)).toBe(a.checkpoint!.session_root)
    expect(recomputeSessionRoot(bLeaves)).toBe(b.checkpoint!.session_root)
    expect(a.checkpoint!.session_root !== b.checkpoint!.session_root).toBe(expected.roots_diverge)

    // Categorical equivocation fact from the shipped detector: same
    // creator_key, same prior_checkpoint, same covered range, inconsistent
    // roots.
    const evidence = detectSessionCheckpointEquivocation(a, b)
    expect(evidence !== undefined).toBe(expected.equivocation)
    expect(evidence!.reason).toBe('divergent-roots-same-claim')
    expect(evidence!.creator_key).toBe(a.creator_key)
    expect(evidence!.prior_checkpoint).toBe(c.input.shared_prior_checkpoint as string)
    expect(evidence!.first_record_hash).toBe(sessionCheckpointRecordHash(a))
    expect(evidence!.second_record_hash).toBe(sessionCheckpointRecordHash(b))
  })

  it('retroactive-declared: backfill checkpoint carries retroactive: true', async () => {
    const c = loadCase('retroactive-declared')
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      record_hash_hex: string
      retroactive_present: boolean
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      verifier_freshness_fact: string
    }

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)
    expect(record.checkpoint!.retroactive === true).toBe(expected.retroactive_present)
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
    expect(expected.validator_should_accept).toBe(true)

    const maxLeafTs = c.input.max_covered_leaf_timestamp as number
    const bound = c.input.verifier_staleness_bound_ms as number
    expect(sessionCheckpointFreshness(record, maxLeafTs, bound)).toBe(
      expected.verifier_freshness_fact,
    )
  })

  it('retroactive-absence-not-null: absence and presence produce different signed bytes', async () => {
    const c = loadCase('retroactive-absence-not-null')
    const plain = c.input.record_without_flag as SessionCheckpointRecord
    const flagged = c.input.record_with_flag as SessionCheckpointRecord
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      retroactive_in_canonical_form: boolean
      record_hash_hex_without_flag: string
      record_hash_hex_with_flag: string
      record_hashes_differ: boolean
      validator_should_accept_both: boolean
    }

    // The non-retroactive canonical form contains no "retroactive" key.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(plain))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)
    expect(signingInput.includes('retroactive')).toBe(expected.retroactive_in_canonical_form)

    // Same payload except retroactive: true → different hash and signature.
    expect(recordHashHex(plain)).toBe(expected.record_hash_hex_without_flag)
    expect(recordHashHex(flagged)).toBe(expected.record_hash_hex_with_flag)
    expect(recordHashHex(plain) !== recordHashHex(flagged)).toBe(expected.record_hashes_differ)
    expect(plain.signature).not.toBe(flagged.signature)

    // Both variants are valid: absence and true are the only legal states.
    expect(await verifyRecordSignature(plain)).toBe(true)
    expect(await verifyRecordSignature(flagged)).toBe(true)
    expect(validateSessionCheckpointStructural(plain)).toBeUndefined()
    expect(validateSessionCheckpointStructural(flagged)).toBeUndefined()
    expect(expected.validator_should_accept_both).toBe(true)
  })

  it('freshness-stale-undeclared: stale checkpoint without the flag gets the fact, not a block', async () => {
    const c = loadCase('freshness-stale-undeclared')
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      verifier_freshness_fact: string
    }

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)

    // Signal, not block: structurally valid, validators accept.
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
    expect(expected.validator_should_accept).toBe(true)

    const maxLeafTs = c.input.max_covered_leaf_timestamp as number
    const bound = c.input.verifier_staleness_bound_ms as number
    expect(sessionCheckpointFreshness(record, maxLeafTs, bound)).toBe(
      expected.verifier_freshness_fact,
    )

    // The composed verifier surfaces the same fact without blocking.
    const verification = await verifySessionCheckpointRecord(record, {
      leaves: c.input.leaves as string[],
      maxCoveredLeafTimestamp: maxLeafTs,
      stalenessBoundMs: bound,
    })
    expect(verification.structuralRejection).toBeUndefined()
    expect(verification.rootMatchesLeaves).toBe(true)
    expect(verification.freshness).toBe(expected.verifier_freshness_fact)
  })

  it('byte-uri-duality: identical signed bytes under 0xFF and 0x08 log entries', async () => {
    const c = loadCase('byte-uri-duality')
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      record_hash_hex: string
      entry_pre_promotion_hex: string
      entry_post_promotion_hex: string
      pre_promotion_event_type_byte: number
      post_promotion_event_type_byte: number
      entries_identical_except_byte_89: boolean
    }

    // The signed record verifies; its event_type is the URI, so the signed
    // bytes carry no log-entry byte at all.
    expect(await verifyRecordSignature(record)).toBe(true)
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)

    // Pre-promotion: the log operator encodes the (not-yet-normative) URI
    // under the 0xFF extension slot per §2.3.1.
    const entryPre = serializeEntry({
      record_hash_hex: recordHashHex(record),
      creator_key_b64url: record.creator_key,
      context_id: record.context_id,
      timestamp: record.timestamp,
      event_type: record.event_type,
    })
    expect(hexEncode(entryPre)).toBe(expected.entry_pre_promotion_hex)
    expect(entryPre[89]).toBe(expected.pre_promotion_event_type_byte)

    // Post-promotion: same 90-byte entry with byte 89 flipped to 0x08.
    const entryPost = hexDecode(expected.entry_post_promotion_hex)
    expect(entryPost).toHaveLength(90)
    expect(entryPost[89]).toBe(expected.post_promotion_event_type_byte)
    let identicalExceptLast = true
    for (let i = 0; i < 89; i++) {
      if (entryPre[i] !== entryPost[i]) identicalExceptLast = false
    }
    expect(identicalExceptLast && entryPre[89] !== entryPost[89]).toBe(
      expected.entries_identical_except_byte_89,
    )

    // The record itself is byte-identical across the promotion: the entry
    // encodings both commit to the SAME record_hash over the SAME canonical
    // bytes (bytes 1-32 of each entry).
    expect(hexEncode(entryPre.slice(1, 33))).toBe(expected.record_hash_hex)
    expect(hexEncode(entryPost.slice(1, 33))).toBe(expected.record_hash_hex)
  })
})
