// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §2.11 anchor-plurality conformance (P043 ADR; extends D050).
 *
 * Loads each case from spec/conformance/2.11/anchors/cases/ and asserts the
 * expected invariants against a REFERENCE implementation of the anchor
 * interface contained in this file:
 *
 *   - legacy `log_proofs` elements (absent anchor_type) parse as `atrib-log`
 *   - discriminator malformation rules (anchor_type present without
 *     anchor_id+proof; anchor_type absent without the legacy triple)
 *   - unknown anchor_type values surfaced, not counted, never invalidating
 *   - the `anchor_plurality` annotation: single_anchor is a tier, never a
 *     failure; pending OTS proofs excluded until upgraded in place;
 *     independence counted over operator groups
 *   - §2.11.4 hard conditions unchanged: cross_log_threshold_not_met,
 *     cross_log_equivocation_detected, cross_log_censorship_suspected
 *   - the fresh anchoring-signature claim artifact
 *     ("atrib-anchor/v1:" + record_hash, Ed25519-signed by an anchoring key
 *     that is NOT the record's signing key) and the proof that the record's
 *     own signature cannot ride the digest path
 *   - producer-side allow_single_anchor posture resolution
 *   - determinism: two runs over the same bundle + trust config produce an
 *     identical annotation (the §4.6-style two-run discipline)
 *
 * The corpus is regenerated by
 * packages/log-dev/scripts/generate-conformance-anchors.ts; this test
 * consumes the committed vectors only.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import * as ed from '@noble/ed25519'
import { sha512 } from '@noble/hashes/sha2.js'
import {
  base64urlDecode,
  canonicalRecord,
  canonicalSigningInput,
  hexEncode,
  leafHash,
  sha256,
  verifyInclusion,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'

// @noble/ed25519 v3 needs sha512 wired (same wiring as @atrib/mcp signing).
ed.hashes.sha512 = sha512
ed.hashes.sha512Async = (m: Uint8Array) => Promise.resolve(sha512(m))

const CORPUS = join(__dirname, '../../../spec/conformance/2.11/anchors/cases')

const ANCHOR_CLAIM_PREFIX = 'atrib-anchor/v1:'
const KNOWN_NON_LOG_TYPES = new Set(['sigstore-rekor', 'rfc3161-tsa', 'opentimestamps'])

const utf8 = new TextEncoder()
const utf8Decode = new TextDecoder()

// ── Corpus shapes ────────────────────────────────────────────────────

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

interface AnchorElement {
  anchor_type?: string
  anchor_id?: string
  proof?: Record<string, unknown>
  log_id?: string
  log_index?: number
  checkpoint?: string
  inclusion_proof?: string[]
  entry_bytes_b64?: string
}

interface AnchorBundle {
  record_hash: string
  log_proofs: AnchorElement[]
}

interface TrustEntry {
  origin: string
  pubkey_b64: string
}

interface TrustConfig {
  trust_material: {
    logs: Record<string, TrustEntry>
    rekor?: Record<string, TrustEntry>
  }
  trusted_logs?: string[]
  threshold_m?: number
  required_anchors?: number
  operator_groups?: Array<{
    group: string
    members: Array<{ anchor_type: string; anchor_id: string }>
  }>
}

interface NotFoundResponse {
  log_id: string
  status: string
  epoch_window_ms: [number, number]
}

interface AnchorPlurality {
  proof_count: number
  verified_count: number
  pending_count: number
  malformed_count: number
  unknown_types: string[]
  independent_count: number
  plurality_met: boolean
  single_anchor: boolean
  equivocation_detected: boolean
  anchored_at_range_ms: [number, number] | null
}

interface DisagreeingPair {
  log_id_a: string
  leaf_hash_a_hex: string
  log_id_b: string
  leaf_hash_b_hex: string
}

interface AnchorVerdict {
  anchor_plurality: AnchorPlurality
  malformed_indices: number[]
  invalid_indices: number[]
  trusted_verified_count: number
  cross_log_threshold_not_met: boolean
  cross_log_equivocation_detected: boolean
  cross_log_censorship_suspected: boolean
  silent_log: string | null
  untrusted_surfaced: string[]
  disagreeing_pair: DisagreeingPair | null
  hard_reject: boolean
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

function b64decode(s: string): Uint8Array {
  return new Uint8Array(Buffer.from(s, 'base64'))
}

/**
 * JCS-equivalent serialization for the FLAT objects this corpus signs
 * (ASCII string / integer values only): JSON.stringify with sorted keys.
 * Must byte-match packages/log-dev/scripts/generate-conformance-anchors.ts.
 */
function sortedJson(obj: Record<string, string | number>): string {
  const sorted: Record<string, string | number> = {}
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = obj[key] as string | number
  }
  return JSON.stringify(sorted)
}

/** §2.4.2 key_id = SHA-256(key_name || 0x0A || 0x01 || public_key_bytes)[:4] */
function computeKeyId(origin: string, publicKey: Uint8Array): Uint8Array {
  const nameBytes = utf8.encode(origin)
  const preimage = new Uint8Array(nameBytes.length + 2 + publicKey.length)
  preimage.set(nameBytes, 0)
  preimage[nameBytes.length] = 0x0a
  preimage[nameBytes.length + 1] = 0x01
  preimage.set(publicKey, nameBytes.length + 2)
  return sha256(preimage).slice(0, 4)
}

interface ParsedCheckpoint {
  origin: string
  treeSize: number
  root: Uint8Array
  bodyBytes: Uint8Array
  keyId: Uint8Array
  signature: Uint8Array
}

/** Parse a §2.4.3 signed note (3-line body + blank line + signature line). */
function parseCheckpoint(checkpoint: string): ParsedCheckpoint | null {
  const lines = checkpoint.split('\n')
  if (lines.length < 5) return null
  const origin = lines[0]
  const sizeStr = lines[1]
  const rootB64 = lines[2]
  if (origin === undefined || sizeStr === undefined || rootB64 === undefined) return null
  if (lines[3] !== '') return null
  const sigLine = lines[4]
  if (sigLine === undefined) return null
  const m = sigLine.match(/^[—-] (\S+) (\S+)\s*$/)
  if (!m) return null
  const sigOrigin = m[1] as string
  if (sigOrigin !== origin) return null
  const decoded = b64decode(m[2] as string)
  if (decoded.length !== 4 + 64) return null
  if (!/^\d+$/.test(sizeStr)) return null
  const body = `${origin}\n${sizeStr}\n${rootB64}\n`
  return {
    origin,
    treeSize: Number(sizeStr),
    root: b64decode(rootB64),
    bodyBytes: utf8.encode(body),
    keyId: decoded.slice(0, 4),
    signature: decoded.slice(4),
  }
}

/** Verify a signed checkpoint against a trust-material entry. */
async function verifyCheckpoint(
  checkpoint: string,
  material: TrustEntry,
): Promise<ParsedCheckpoint | null> {
  const parsed = parseCheckpoint(checkpoint)
  if (!parsed) return null
  if (parsed.origin !== material.origin) return null
  const pubkey = b64decode(material.pubkey_b64)
  const expectedKeyId = computeKeyId(material.origin, pubkey)
  if (hexEncode(parsed.keyId) !== hexEncode(expectedKeyId)) return null
  const ok = await ed.verifyAsync(parsed.signature, parsed.bodyBytes, pubkey)
  return ok ? parsed : null
}

type ElementStatus = 'verified' | 'pending' | 'invalid' | 'malformed' | 'unknown'

interface ElementResult {
  status: ElementStatus
  anchorType: string
  anchorId: string
  attestedTimeMs: number | null
  /** Committed entry bytes (atrib-log elements only), for §2.11.4 step 4. */
  entryBytesB64: string | null
}

/**
 * Reference verification for one log_proofs element. Pure given the bundle's
 * record_hash and the trust material: no network, no clock, no randomness.
 */
async function verifyElement(
  el: AnchorElement,
  recordHash: string,
  trust: TrustConfig,
): Promise<ElementResult> {
  const anchorType = el.anchor_type
  const recordHashHex = recordHash.startsWith('sha256:')
    ? recordHash.slice('sha256:'.length)
    : recordHash

  // Rule (a): anchor_type absent (or explicit "atrib-log") requires the
  // legacy (log_id, checkpoint, inclusion_proof) triple.
  if (anchorType === undefined || anchorType === 'atrib-log') {
    if (
      typeof el.log_id !== 'string' ||
      typeof el.checkpoint !== 'string' ||
      !Array.isArray(el.inclusion_proof) ||
      (anchorType === undefined && el.proof !== undefined)
    ) {
      return {
        status: 'malformed',
        anchorType: 'atrib-log',
        anchorId: typeof el.log_id === 'string' ? el.log_id : '',
        attestedTimeMs: null,
        entryBytesB64: null,
      }
    }
    const base: Omit<ElementResult, 'status'> = {
      anchorType: 'atrib-log',
      anchorId: el.log_id,
      attestedTimeMs: null,
      entryBytesB64: el.entry_bytes_b64 ?? null,
    }
    const material = trust.trust_material.logs[el.log_id]
    if (!material || typeof el.entry_bytes_b64 !== 'string' || typeof el.log_index !== 'number') {
      return { ...base, status: 'invalid' }
    }
    const parsed = await verifyCheckpoint(el.checkpoint, material)
    if (!parsed) return { ...base, status: 'invalid' }
    const entryBytes = b64decode(el.entry_bytes_b64)
    // The 90-byte entry embeds record_hash at bytes [1..33] (§2.3.1).
    if (entryBytes.length !== 90 || hexEncode(entryBytes.slice(1, 33)) !== recordHashHex) {
      return { ...base, status: 'invalid' }
    }
    const proof = el.inclusion_proof.map(b64decode)
    const ok = verifyInclusion(el.log_index, parsed.treeSize, leafHash(entryBytes), proof, parsed.root)
    return { ...base, status: ok ? 'verified' : 'invalid' }
  }

  // Rule (b): anchor_type present and != "atrib-log" requires anchor_id + proof.
  if (typeof el.anchor_id !== 'string' || typeof el.proof !== 'object' || el.proof === null) {
    if (!KNOWN_NON_LOG_TYPES.has(anchorType)) {
      return { status: 'unknown', anchorType, anchorId: el.anchor_id ?? '', attestedTimeMs: null, entryBytesB64: null }
    }
    return { status: 'malformed', anchorType, anchorId: el.anchor_id ?? '', attestedTimeMs: null, entryBytesB64: null }
  }

  const base: Omit<ElementResult, 'status'> = {
    anchorType,
    anchorId: el.anchor_id,
    attestedTimeMs: null,
    entryBytesB64: null,
  }

  if (!KNOWN_NON_LOG_TYPES.has(anchorType)) {
    // Forward compatibility: surfaced, not counted, never invalidating.
    return { ...base, status: 'unknown' }
  }

  const proof = el.proof

  if (anchorType === 'sigstore-rekor') {
    const material = trust.trust_material.rekor?.[el.anchor_id]
    const entryBodyB64 = proof['entry_body_b64']
    const logIndex = proof['log_index']
    const checkpoint = proof['checkpoint']
    const inclusionProof = proof['inclusion_proof']
    const integratedTimeMs = proof['integrated_time_ms']
    const setB64 = proof['signed_entry_timestamp_b64']
    if (
      !material ||
      typeof entryBodyB64 !== 'string' ||
      typeof logIndex !== 'number' ||
      typeof checkpoint !== 'string' ||
      !Array.isArray(inclusionProof) ||
      typeof integratedTimeMs !== 'number' ||
      typeof setB64 !== 'string'
    ) {
      return { ...base, status: 'invalid' }
    }
    // 1. Reconstruct the anchor-claim artifact from the bundle's record_hash.
    const expectedArtifact = ANCHOR_CLAIM_PREFIX + recordHash
    const bodyBytes = b64decode(entryBodyB64)
    let body: Record<string, unknown>
    try {
      body = JSON.parse(utf8Decode.decode(bodyBytes)) as Record<string, unknown>
    } catch {
      return { ...base, status: 'invalid' }
    }
    const artifactB64 = body['artifact_b64']
    const pubB64url = body['public_key_b64url']
    const sigB64url = body['signature_b64url']
    if (
      typeof artifactB64 !== 'string' ||
      typeof pubB64url !== 'string' ||
      typeof sigB64url !== 'string'
    ) {
      return { ...base, status: 'invalid' }
    }
    const artifactBytes = b64decode(artifactB64)
    const artifact = utf8Decode.decode(artifactBytes)
    // Binding: the entry's artifact MUST reconstruct from record_hash and
    // carry the domain-separation prefix.
    if (artifact !== expectedArtifact || !artifact.startsWith(ANCHOR_CLAIM_PREFIX)) {
      return { ...base, status: 'invalid' }
    }
    // 2. Verify the FRESH anchoring signature over the artifact bytes.
    const sigOk = await ed.verifyAsync(
      base64urlDecode(sigB64url),
      artifactBytes,
      base64urlDecode(pubB64url),
    )
    if (!sigOk) return { ...base, status: 'invalid' }
    // 3. Verify the inclusion proof against the checkpoint.
    const parsed = await verifyCheckpoint(checkpoint, material)
    if (!parsed) return { ...base, status: 'invalid' }
    const inclusionOk = verifyInclusion(
      logIndex,
      parsed.treeSize,
      leafHash(bodyBytes),
      (inclusionProof as string[]).map(b64decode),
      parsed.root,
    )
    if (!inclusionOk) return { ...base, status: 'invalid' }
    // 4. Verify the signed entry timestamp over the reconstructed input.
    const setInput = sortedJson({
      entry_body_b64: entryBodyB64,
      integrated_time_ms: integratedTimeMs,
      log_index: logIndex,
    })
    const setOk = await ed.verifyAsync(
      b64decode(setB64),
      utf8.encode(setInput),
      b64decode(material.pubkey_b64),
    )
    if (!setOk) return { ...base, status: 'invalid' }
    return { ...base, status: 'verified', attestedTimeMs: integratedTimeMs }
  }

  if (anchorType === 'rfc3161-tsa') {
    // STRUCTURAL verification in this corpus revision: the commitment-binding
    // field must equal the bundle's record hash; the DER token is opaque.
    const hashedMessageHex = proof['hashed_message_hex']
    const tokenB64 = proof['timestamp_token_b64']
    const genTimeMs = proof['gen_time_ms']
    if (
      typeof hashedMessageHex !== 'string' ||
      typeof tokenB64 !== 'string' ||
      typeof genTimeMs !== 'number' ||
      hashedMessageHex !== recordHashHex ||
      b64decode(tokenB64).length === 0
    ) {
      return { ...base, status: 'invalid' }
    }
    return { ...base, status: 'verified', attestedTimeMs: genTimeMs }
  }

  // opentimestamps
  const commitmentHex = proof['commitment_hex']
  const otsB64 = proof['ots_b64']
  const status = proof['status']
  if (
    typeof commitmentHex !== 'string' ||
    typeof otsB64 !== 'string' ||
    commitmentHex !== recordHashHex ||
    b64decode(otsB64).length === 0
  ) {
    return { ...base, status: 'invalid' }
  }
  if (status === 'pending') return { ...base, status: 'pending' }
  const attestedTimeMs = proof['attested_time_ms']
  if (status !== 'complete' || typeof attestedTimeMs !== 'number') {
    return { ...base, status: 'invalid' }
  }
  return { ...base, status: 'verified', attestedTimeMs }
}

/** Operator-group key: declared group, else one group per (type, id) pair. */
function groupOf(anchorType: string, anchorId: string, trust: TrustConfig): string {
  for (const g of trust.operator_groups ?? []) {
    for (const m of g.members) {
      if (m.anchor_type === anchorType && m.anchor_id === anchorId) return `group:${g.group}`
    }
  }
  return `pair:${anchorType} ${anchorId}`
}

/**
 * Reference implementation of the anchor_plurality annotation and the
 * §2.11.4 hard conditions. Deterministic: same bundle + trust config in,
 * identical verdict out.
 */
async function computeAnchorVerdict(
  bundle: AnchorBundle,
  trust: TrustConfig,
  notFoundResponses: NotFoundResponse[] = [],
): Promise<AnchorVerdict> {
  const results: ElementResult[] = []
  for (const el of bundle.log_proofs) {
    results.push(await verifyElement(el, bundle.record_hash, trust))
  }

  const malformedIndices: number[] = []
  const invalidIndices: number[] = []
  const unknownTypes: string[] = []
  const groups = new Set<string>()
  const times: number[] = []
  let verified = 0
  let pending = 0

  results.forEach((r, i) => {
    if (r.status === 'malformed') malformedIndices.push(i)
    if (r.status === 'invalid') invalidIndices.push(i)
    if (r.status === 'unknown' && !unknownTypes.includes(r.anchorType)) {
      unknownTypes.push(r.anchorType)
    }
    if (r.status === 'pending') pending += 1
    if (r.status === 'verified') {
      verified += 1
      groups.add(groupOf(r.anchorType, r.anchorId, trust))
      if (r.attestedTimeMs !== null) times.push(r.attestedTimeMs)
    }
  })

  const requiredAnchors = trust.required_anchors ?? 2
  const thresholdM = trust.threshold_m ?? 1
  const trustedLogs = trust.trusted_logs ?? []

  // §2.11.4 threshold: count verified atrib-log proofs in the trusted set.
  const trustedVerified = results.filter(
    (r) => r.status === 'verified' && r.anchorType === 'atrib-log' && trustedLogs.includes(r.anchorId),
  )
  const untrustedSurfaced = results
    .filter(
      (r) =>
        r.status === 'verified' && r.anchorType === 'atrib-log' && !trustedLogs.includes(r.anchorId),
    )
    .map((r) => r.anchorId)
  const thresholdNotMet = trustedVerified.length < thresholdM

  // §2.11.4 equivocation: pairwise leaf-byte comparison across trusted logs.
  let equivocation = false
  let disagreeingPair: DisagreeingPair | null = null
  for (let i = 0; i < trustedVerified.length; i++) {
    for (let j = i + 1; j < trustedVerified.length; j++) {
      const a = trustedVerified[i] as ElementResult
      const b = trustedVerified[j] as ElementResult
      if (a.entryBytesB64 !== null && b.entryBytesB64 !== null && a.entryBytesB64 !== b.entryBytesB64) {
        equivocation = true
        disagreeingPair = {
          log_id_a: a.anchorId,
          leaf_hash_a_hex: hexEncode(leafHash(b64decode(a.entryBytesB64))),
          log_id_b: b.anchorId,
          leaf_hash_b_hex: hexEncode(leafHash(b64decode(b.entryBytesB64))),
        }
      }
    }
  }

  // §2.11.4 censorship-shaped equivocation: a trusted log reports not-found
  // while another trusted log holds a verified proof.
  let censorship = false
  let silentLog: string | null = null
  for (const nf of notFoundResponses) {
    if (nf.status === 'not_found' && trustedLogs.includes(nf.log_id) && trustedVerified.length > 0) {
      censorship = true
      silentLog = nf.log_id
    }
  }

  const independentCount = groups.size
  const annotation: AnchorPlurality = {
    proof_count: bundle.log_proofs.length,
    verified_count: verified,
    pending_count: pending,
    malformed_count: malformedIndices.length,
    unknown_types: unknownTypes,
    independent_count: independentCount,
    plurality_met: independentCount >= requiredAnchors,
    single_anchor: independentCount === 1,
    equivocation_detected: equivocation,
    anchored_at_range_ms: times.length > 0 ? [Math.min(...times), Math.max(...times)] : null,
  }

  return {
    anchor_plurality: annotation,
    malformed_indices: malformedIndices,
    invalid_indices: invalidIndices,
    trusted_verified_count: trustedVerified.length,
    cross_log_threshold_not_met: thresholdNotMet,
    cross_log_equivocation_detected: equivocation,
    cross_log_censorship_suspected: censorship,
    silent_log: silentLog,
    untrusted_surfaced: untrustedSurfaced,
    disagreeing_pair: disagreeingPair,
    // Hard rejection is reserved for the §2.11.4 conditions. single_anchor
    // is a tier, never a failure.
    hard_reject: thresholdNotMet || equivocation,
  }
}

// ── Producer-side posture (reference, pure) ─────────────────────────

interface AnchorConfig {
  anchors?: Array<Record<string, unknown>>
  allow_single_anchor?: boolean
}

interface PostureResolution {
  name: string
  effective_anchor_count: number
  used_default_set: boolean
  warn: boolean
  sidecar_anchor_config: { configured: number; allow_single_anchor: boolean } | null
}

const BUILT_IN_DEFAULT_SET_SIZE = 2

function resolveAnchorPosture(name: string, config: AnchorConfig): PostureResolution {
  if (config.anchors === undefined) {
    return {
      name,
      effective_anchor_count: BUILT_IN_DEFAULT_SET_SIZE,
      used_default_set: true,
      warn: false,
      sidecar_anchor_config: null,
    }
  }
  const configured = config.anchors.length
  if (configured >= 2 || config.allow_single_anchor === true) {
    return {
      name,
      effective_anchor_count: configured,
      used_default_set: false,
      warn: false,
      sidecar_anchor_config: null,
    }
  }
  // Warn + sidecar marker; never a throw on the primary path (§5.8).
  return {
    name,
    effective_anchor_count: configured,
    used_default_set: false,
    warn: true,
    sidecar_anchor_config: { configured, allow_single_anchor: false },
  }
}

// ── Shared helpers for the tests ─────────────────────────────────────

async function runCaseVerdict(
  c: CaseFile,
  bundleKey = 'bundle',
  trustKey = 'trust',
): Promise<AnchorVerdict> {
  const bundle = c.input[bundleKey] as AnchorBundle
  const trust = c.input[trustKey] as TrustConfig
  const notFound = (c.input['not_found_responses'] as NotFoundResponse[] | undefined) ?? []
  const verdict = await computeAnchorVerdict(bundle, trust, notFound)
  // Determinism: a second run over the same inputs is identical (§4.6-style).
  const rerun = await computeAnchorVerdict(bundle, trust, notFound)
  expect(rerun).toEqual(verdict)
  return verdict
}

describe('spec §2.11 anchors conformance', () => {
  it('legacy-single-log: absent anchor_type parses as atrib-log; single anchor is a tier, not a failure', async () => {
    const c = loadCase('legacy-single-log')
    const record = c.input['record'] as AtribRecord
    const expected = c.expected as unknown as {
      resolved_anchor_types: string[]
      record_signature_ok: boolean
      atrib_log_proof_verifies: boolean
      anchor_plurality: AnchorPlurality
      hard_reject: boolean
    }

    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_ok)

    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
    expect(verdict.anchor_plurality.verified_count).toBe(1)
    expect(expected.resolved_anchor_types).toEqual(['atrib-log'])
    // The tier flag never invalidates: single_anchor true AND the record valid.
    expect(verdict.anchor_plurality.single_anchor).toBe(true)
  })

  it('discriminator-malformed-elements: rules (a) and (b) exclude elements without invalidating the record', async () => {
    const c = loadCase('discriminator-malformed-elements')
    const expected = c.expected as unknown as {
      malformed_indices: number[]
      anchor_plurality: AnchorPlurality
      record_signature_ok: boolean
      hard_reject: boolean
    }
    const record = c.input['record'] as AtribRecord

    const verdict = await runCaseVerdict(c)
    expect(verdict.malformed_indices).toEqual(expected.malformed_indices)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_ok)
  })

  it('unknown-anchor-type: surfaced, not counted, not invalidating', async () => {
    const c = loadCase('unknown-anchor-type')
    const expected = c.expected as unknown as {
      anchor_plurality: AnchorPlurality
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.anchor_plurality.unknown_types).toEqual(['example-quantum-beacon/v9'])
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('plurality-atrib-log-plus-rfc3161: two independent anchors meet the default plurality', async () => {
    const c = loadCase('plurality-atrib-log-plus-rfc3161')
    const expected = c.expected as unknown as { anchor_plurality: AnchorPlurality; hard_reject: boolean }
    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.anchor_plurality.plurality_met).toBe(true)
    expect(verdict.anchor_plurality.single_anchor).toBe(false)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('rekor-anchor-claim: fresh anchoring signature over the reconstructible claim artifact verifies end to end', async () => {
    const c = loadCase('rekor-anchor-claim')
    const record = c.input['record'] as AtribRecord
    const bundle = c.input['bundle'] as AnchorBundle
    const expected = c.expected as unknown as {
      anchor_claim_artifact_utf8: string
      anchor_claim_prefix: string
      artifact_reconstructs_from_record_hash: boolean
      anchoring_signature_verifies: boolean
      anchoring_key_b64url: string
      anchoring_key_differs_from_creator_key: boolean
      set_signing_input_utf8: string
      anchor_plurality: AnchorPlurality
      hard_reject: boolean
    }

    // The claim artifact is deterministically reconstructible from record_hash.
    const recordHash = 'sha256:' + hexEncode(sha256(canonicalRecord(record)))
    expect(bundle.record_hash).toBe(recordHash)
    expect(expected.anchor_claim_prefix).toBe(ANCHOR_CLAIM_PREFIX)
    expect(expected.anchor_claim_artifact_utf8).toBe(ANCHOR_CLAIM_PREFIX + recordHash)

    // Independent re-verification of the embedded anchoring signature.
    const rekorEl = bundle.log_proofs[1] as AnchorElement
    const proof = rekorEl.proof as Record<string, unknown>
    const bodyBytes = b64decode(proof['entry_body_b64'] as string)
    const body = JSON.parse(utf8Decode.decode(bodyBytes)) as Record<string, string>
    const artifactBytes = b64decode(body['artifact_b64'] as string)
    expect(utf8Decode.decode(artifactBytes)).toBe(expected.anchor_claim_artifact_utf8)
    const sigOk = await ed.verifyAsync(
      base64urlDecode(body['signature_b64url'] as string),
      artifactBytes,
      base64urlDecode(body['public_key_b64url'] as string),
    )
    expect(sigOk).toBe(expected.anchoring_signature_verifies)

    // The anchoring key is FRESH: not the record's signing key.
    expect(body['public_key_b64url']).toBe(expected.anchoring_key_b64url)
    expect(body['public_key_b64url'] === record.creator_key).toBe(
      !expected.anchoring_key_differs_from_creator_key,
    )

    // The SET signing input reconstructs byte-for-byte.
    const setInput = sortedJson({
      entry_body_b64: proof['entry_body_b64'] as string,
      integrated_time_ms: proof['integrated_time_ms'] as number,
      log_index: proof['log_index'] as number,
    })
    expect(setInput).toBe(expected.set_signing_input_utf8)

    const verdict = await runCaseVerdict(c)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('rekor-claim-binding-mismatch: a genuinely-signed claim for another record is an invalid proof, not counted', async () => {
    const c = loadCase('rekor-claim-binding-mismatch')
    const expected = c.expected as unknown as {
      invalid_indices: number[]
      artifact_reconstructs_from_record_hash: boolean
      embedded_signature_verifies_over_its_own_artifact: boolean
      anchor_plurality: AnchorPlurality
      hard_reject: boolean
    }
    const bundle = c.input['bundle'] as AnchorBundle

    // The embedded signature IS valid over its own (mismatched) artifact.
    const rekorEl = bundle.log_proofs[1] as AnchorElement
    const proof = rekorEl.proof as Record<string, unknown>
    const body = JSON.parse(
      utf8Decode.decode(b64decode(proof['entry_body_b64'] as string)),
    ) as Record<string, string>
    const artifactBytes = b64decode(body['artifact_b64'] as string)
    const artifact = utf8Decode.decode(artifactBytes)
    expect(artifact === ANCHOR_CLAIM_PREFIX + bundle.record_hash).toBe(
      expected.artifact_reconstructs_from_record_hash,
    )
    const sigOk = await ed.verifyAsync(
      base64urlDecode(body['signature_b64url'] as string),
      artifactBytes,
      base64urlDecode(body['public_key_b64url'] as string),
    )
    expect(sigOk).toBe(expected.embedded_signature_verifies_over_its_own_artifact)

    // But the binding fails, so the element is invalid and not counted.
    const verdict = await runCaseVerdict(c)
    expect(verdict.invalid_indices).toEqual(expected.invalid_indices)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it("record-signature-digest-path-invalid: the record's own signature cannot ride the digest path", async () => {
    const c = loadCase('record-signature-digest-path-invalid')
    const record = c.input['record'] as AtribRecord
    const expected = c.expected as unknown as {
      record_hash: string
      signature_verifies_over_signing_input: boolean
      signature_verifies_over_full_canonical_record: boolean
      signing_input_differs_from_hashed_bytes: boolean
    }

    const sigBytes = base64urlDecode(record.signature)
    const pubkey = base64urlDecode(record.creator_key)

    // record_hash covers the COMPLETE record INCLUDING the signature (§1.2.3).
    const fullBytes = canonicalRecord(record)
    expect('sha256:' + hexEncode(sha256(fullBytes))).toBe(expected.record_hash)

    // The signature verifies over the signature-less form (§1.4.2)...
    const signingInput = canonicalSigningInput(record)
    expect(await ed.verifyAsync(sigBytes, signingInput, pubkey)).toBe(
      expected.signature_verifies_over_signing_input,
    )

    // ...and does NOT verify over the bytes behind record_hash. This is why a
    // hashedrekord-style upload (data.hash = record_hash, sig = record
    // signature) fails by construction, and why anchors carry a FRESH
    // anchoring signature over the reconstructible claim artifact instead.
    expect(await ed.verifyAsync(sigBytes, fullBytes, pubkey)).toBe(
      expected.signature_verifies_over_full_canonical_record,
    )
    expect(hexEncode(signingInput) !== hexEncode(fullBytes)).toBe(
      expected.signing_input_differs_from_hashed_bytes,
    )
  })

  it('ots-pending-then-upgraded: pending excluded from plurality; in-place upgrade meets it', async () => {
    const c = loadCase('ots-pending-then-upgraded')
    const expected = c.expected as unknown as {
      pending: { anchor_plurality: AnchorPlurality; hard_reject: boolean }
      upgraded: { anchor_plurality: AnchorPlurality; hard_reject: boolean }
    }

    const pendingVerdict = await runCaseVerdict(c, 'bundle_pending')
    expect(pendingVerdict.anchor_plurality).toEqual(expected.pending.anchor_plurality)
    expect(pendingVerdict.hard_reject).toBe(expected.pending.hard_reject)

    const upgradedVerdict = await runCaseVerdict(c, 'bundle_upgraded')
    expect(upgradedVerdict.anchor_plurality).toEqual(expected.upgraded.anchor_plurality)
    expect(upgradedVerdict.hard_reject).toBe(expected.upgraded.hard_reject)
  })

  it('same-operator-group: independence counts distinct operator groups, not elements', async () => {
    const c = loadCase('same-operator-group')
    const expected = c.expected as unknown as {
      default_grouping: { anchor_plurality: AnchorPlurality }
      declared_group: { anchor_plurality: AnchorPlurality }
    }

    const defaultVerdict = await runCaseVerdict(c, 'bundle', 'trust_default_grouping')
    expect(defaultVerdict.anchor_plurality).toEqual(expected.default_grouping.anchor_plurality)

    const groupedVerdict = await runCaseVerdict(c, 'bundle', 'trust_declared_group')
    expect(groupedVerdict.anchor_plurality).toEqual(expected.declared_group.anchor_plurality)
    expect(groupedVerdict.anchor_plurality.independent_count).toBe(1)
    expect(groupedVerdict.anchor_plurality.single_anchor).toBe(true)
  })

  it('threshold-not-met: §2.11.4 M=2 rejection unchanged; untrusted proofs surfaced not counted', async () => {
    const c = loadCase('threshold-not-met')
    const expected = c.expected as unknown as {
      trusted_verified_count: number
      cross_log_threshold_not_met: boolean
      untrusted_surfaced: string[]
      anchor_plurality: AnchorPlurality
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.trusted_verified_count).toBe(expected.trusted_verified_count)
    expect(verdict.cross_log_threshold_not_met).toBe(expected.cross_log_threshold_not_met)
    expect(verdict.untrusted_surfaced).toEqual(expected.untrusted_surfaced)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('equivocation-detected: §2.11.4 leaf-byte disagreement rejection unchanged, pair surfaced', async () => {
    const c = loadCase('equivocation-detected')
    const expected = c.expected as unknown as {
      cross_log_equivocation_detected: boolean
      disagreeing_pair: DisagreeingPair
      anchor_plurality: AnchorPlurality
      hard_reject: boolean
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.cross_log_equivocation_detected).toBe(expected.cross_log_equivocation_detected)
    expect(verdict.disagreeing_pair).toEqual(expected.disagreeing_pair)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    expect(verdict.hard_reject).toBe(expected.hard_reject)
  })

  it('censorship-suspected: not-found from a trusted log alongside a verified proof is flagged with the silent log', async () => {
    const c = loadCase('censorship-suspected')
    const expected = c.expected as unknown as {
      cross_log_censorship_suspected: boolean
      silent_log: string
      anchor_plurality: AnchorPlurality
    }
    const verdict = await runCaseVerdict(c)
    expect(verdict.cross_log_censorship_suspected).toBe(expected.cross_log_censorship_suspected)
    expect(verdict.silent_log).toBe(expected.silent_log)
    expect(verdict.anchor_plurality).toEqual(expected.anchor_plurality)
    // Flag, not reject: censorship suspicion alone is not a hard rejection.
    expect(verdict.hard_reject).toBe(false)
  })

  it('allow-single-anchor-config: producer posture resolves per the precedence rules, never throwing', () => {
    const c = loadCase('allow-single-anchor-config')
    const configs = c.input['configs'] as Array<{ name: string; config: AnchorConfig }>
    const expected = c.expected as unknown as {
      resolutions: PostureResolution[]
      never_throws_on_primary_path: boolean
      never_disables_signing: boolean
    }

    const resolutions = configs.map(({ name, config }) => resolveAnchorPosture(name, config))
    expect(resolutions).toEqual(expected.resolutions)
    expect(expected.never_throws_on_primary_path).toBe(true)
    expect(expected.never_disables_signing).toBe(true)
  })
})
