// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §1.11 conformance: delegation certificates (P045).
 *
 * Loads each case from spec/conformance/delegation-certificates/cases/
 * and asserts the expected invariants. The corpus is regenerated by
 * packages/log-dev/scripts/generate-conformance-delegation-certificates.ts;
 * this file is the @atrib/verify reference implementation of the §1.11
 * contract:
 *
 *   - certificate JCS canonical form, principal Ed25519 signature,
 *     cert_hash derivation, self-certificate + wrong-signer rejection
 *   - the §1.11.4 verifier walk (record -> run key -> certificate ->
 *     principal) with in_window / context_bound / cert_bound / scope
 *     facts as signals, never invalidation (§6.7.3 posture)
 *   - depth-0 identity: byte-for-byte equality with the §1.4 corpus
 *   - delegation_cert_hash lex-slotting between creator_key and
 *     event_type, with distinct signatures for presence vs absence
 *   - §1.9.2 signing rule 3 (principal-signed run-key revocation) and
 *     its rejection when the referenced certificate does not cover
 *     revoked_key
 *   - the D067 multi-producer posture: cert_bound stays null for run
 *     keys that joined a context whose genesis another producer signed
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import canonicalize from 'canonicalize'
import * as ed from '@noble/ed25519'
import { sha512 } from '@noble/hashes/sha2.js'
import {
  base64urlDecode,
  canonicalRecord,
  canonicalSigningInput,
  hexEncode,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'
import { buildRevocationRegistry, applyRevocation, type MinimalRecord } from '../src/revocations.js'
import type { VerificationState } from '../src/types.js'

// @noble/ed25519 v3 needs sha512 wired (idempotent; @atrib/mcp wires the same instance).
ed.hashes.sha512 = sha512
ed.hashes.sha512Async = (m) => Promise.resolve(sha512(m))

const CORPUS = join(__dirname, '../../../spec/conformance/delegation-certificates/cases')
const SIGNING_VECTORS_1_4 = join(__dirname, '../../../spec/conformance/1.4/signing-vectors.json')

// ── Corpus shapes ─────────────────────────────────────────────────────

interface CapabilityScope {
  tool_names?: string[]
  max_amount?: { currency: string; value: number }
  counterparties?: string[]
  event_types?: string[]
  expires_at?: number
}

interface DelegationCertificate {
  cert_type: string
  context_id?: string
  not_after: number
  not_before?: number
  principal_key: string
  run_pubkey: string
  scope?: CapabilityScope
  signature: string
}

type DelegatedRecord = AtribRecord & { delegation_cert_hash?: string }
type KeyRevocationRecord = AtribRecord & {
  revoked_key: string
  revocation_reason: string
  delegation_cert_hash?: string
}

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

interface DelegationOutcome {
  depth: 0 | 1
  principal_key: string | null
  cert_hash: string | null
  cert_valid: boolean | null
  in_window: boolean | null
  context_bound: boolean | null
  cert_bound: boolean | null
  scope_check: { in_scope: boolean; attenuation_ok: null; mismatches: string[] } | null
  revoked: boolean | null
  errors: string[]
  delegation_unresolved?: boolean
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

// ── Reference implementation of the §1.11 primitives ─────────────────

const utf8 = new TextEncoder()

/** JCS(cert with signature omitted), UTF-8 bytes — the certificate signing input. */
function certSigningInput(cert: DelegationCertificate): Uint8Array {
  const { signature: _, ...unsigned } = cert
  const json = canonicalize(unsigned)
  if (json === undefined) throw new Error('canonicalization produced undefined')
  return utf8.encode(json)
}

/** cert_hash = "sha256:" + hex(SHA-256(UTF-8(JCS(full signed cert)))). */
function certHash(cert: DelegationCertificate): string {
  const json = canonicalize(cert)
  if (json === undefined) throw new Error('canonicalization produced undefined')
  return 'sha256:' + hexEncode(sha256(utf8.encode(json)))
}

/** Ed25519 verification of the certificate under its declared principal_key. */
async function certSignatureVerifies(cert: DelegationCertificate): Promise<boolean> {
  try {
    const pub = base64urlDecode(cert.principal_key)
    if (pub.length !== 32) return false
    const sig = base64urlDecode(cert.signature)
    if (sig.length !== 64) return false
    return await ed.verifyAsync(sig, certSigningInput(cert), pub)
  } catch {
    return false
  }
}

/**
 * Certificate validity as delegation evidence: well-formed keys,
 * run_pubkey !== principal_key, principal signature verifies.
 * Returns the error list (empty = valid).
 */
async function certErrors(cert: DelegationCertificate): Promise<string[]> {
  const errors: string[] = []
  if (cert.run_pubkey === cert.principal_key) {
    errors.push('self_certificate')
    return errors
  }
  if (!(await certSignatureVerifies(cert))) {
    errors.push('principal_signature_invalid')
  }
  return errors
}

/** §6.7.1 envelope check against the certificate scope. Signals only. */
function checkScope(
  record: DelegatedRecord,
  scope: CapabilityScope,
): { in_scope: boolean; attenuation_ok: null; mismatches: string[] } {
  const mismatches: string[] = []
  if (scope.tool_names && record.tool_name !== undefined && !scope.tool_names.includes(record.tool_name)) {
    mismatches.push('tool_names')
  }
  if (scope.event_types && !scope.event_types.includes(record.event_type)) {
    mismatches.push('event_types')
  }
  return { in_scope: mismatches.length === 0, attenuation_ok: null, mismatches }
}

/**
 * The §1.11.4 verifier walk, offline and deterministic. `genesis` is the
 * context genesis record when available (it may be the record itself).
 * Every output is a fact/signal; nothing here alters record validity.
 */
async function evaluateDelegation(
  record: DelegatedRecord,
  genesis: DelegatedRecord | null,
  certs: DelegationCertificate[],
): Promise<DelegationOutcome> {
  const depth0: DelegationOutcome = {
    depth: 0,
    principal_key: null,
    cert_hash: null,
    cert_valid: null,
    in_window: null,
    context_bound: null,
    cert_bound: null,
    scope_check: null,
    revoked: null,
    errors: [],
  }
  // §1.11.4 step 2: delegation_unresolved only applies when the context
  // genesis was signed by R.creator_key (the field commits the genesis
  // signer's OWN run key; another producer's genesis commitment says
  // nothing about this record's signer).
  const genesisCommits =
    genesis !== null &&
    genesis.creator_key === record.creator_key &&
    typeof genesis.delegation_cert_hash === 'string'

  // Step 2: select certificates covering the record's signing key.
  const candidates = certs.filter((c) => c.run_pubkey === record.creator_key)
  if (candidates.length === 0) {
    if (genesisCommits) return { ...depth0, delegation_unresolved: true }
    return depth0
  }

  // A covering certificate exists; check its validity as evidence.
  const cert = candidates[0]
  if (cert === undefined) return depth0
  const errors = await certErrors(cert)
  if (errors.length > 0) {
    // Rejected as delegation evidence: fall back to plain attribution.
    return { ...depth0, cert_hash: certHash(cert), cert_valid: false, errors }
  }

  // Step 3: window, context binding, genesis cert binding.
  const hash = certHash(cert)
  const inWindow = (cert.not_before ?? 0) <= record.timestamp && record.timestamp <= cert.not_after
  const contextBound = cert.context_id === undefined ? null : cert.context_id === record.context_id
  const certBound =
    genesis !== null && genesis.creator_key === record.creator_key && genesisCommits
      ? genesis.delegation_cert_hash === hash
      : null

  // Step 5: scope check (signals only, §6.7.3 posture).
  const scopeCheck = cert.scope ? checkScope(record, cert.scope) : null

  return {
    depth: 1,
    principal_key: cert.principal_key,
    cert_hash: hash,
    cert_valid: true,
    in_window: inWindow,
    context_bound: contextBound,
    cert_bound: certBound,
    scope_check: scopeCheck,
    revoked: false, // walk cases carry no revocation log; §1.9 cases exercise it below
    errors: [],
  }
}

/**
 * §1.9.2 revoker authorization including the §1.11.5 rule 3: a
 * key_revocation MAY be signed by the principal key of a valid
 * delegation certificate covering revoked_key, referenced through the
 * record's delegation_cert_hash field.
 */
async function revokerAuthorized(
  rev: KeyRevocationRecord,
  certs: DelegationCertificate[],
): Promise<{ authorized: boolean; rule?: string; reason?: string }> {
  // Rule 1: signed by the key being retired.
  if (rev.creator_key === rev.revoked_key) return { authorized: true, rule: 'retired_key' }
  // Rule 3: principal via delegation certificate.
  if (typeof rev.delegation_cert_hash === 'string') {
    const cert = certs.find((c) => certHash(c) === rev.delegation_cert_hash)
    if (cert === undefined) {
      return { authorized: false, reason: 'certificate_not_resolved' }
    }
    if ((await certErrors(cert)).length > 0) {
      return { authorized: false, reason: 'certificate_invalid' }
    }
    if (cert.run_pubkey !== rev.revoked_key) {
      return { authorized: false, reason: 'certificate_does_not_cover_revoked_key' }
    }
    if (cert.principal_key !== rev.creator_key) {
      return { authorized: false, reason: 'signer_is_not_certificate_principal' }
    }
    return { authorized: true, rule: 'principal_via_delegation_certificate' }
  }
  return { authorized: false, reason: 'no_authorization_path' }
}

/** Field-order helper: index of a key in a JCS canonical string. */
function keyIndex(canonicalJson: string, key: string): number {
  return canonicalJson.indexOf(`"${key}":`)
}

// ── Tests ─────────────────────────────────────────────────────────────

describe('spec §1.11 conformance: delegation certificates', () => {
  it('cert-canonical-full: JCS form, principal signature, cert_hash', async () => {
    const c = loadCase('cert-canonical-full')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      canonical_signed_form_utf8: string
      cert_hash: string
      principal_signature_verifies: boolean
      cert_valid: boolean
      jcs_field_order: string[]
    }

    const signingInput = new TextDecoder().decode(certSigningInput(cert))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)

    const signedForm = canonicalize(cert)
    expect(signedForm).toBe(expected.canonical_signed_form_utf8)

    // Declared JCS field order is the actual order in the canonical bytes.
    const positions = expected.jcs_field_order.map((k) => keyIndex(expected.canonical_signed_form_utf8, k))
    for (const p of positions) expect(p).toBeGreaterThanOrEqual(0)
    expect([...positions].sort((a, b) => a - b)).toEqual(positions)

    expect(certHash(cert)).toBe(expected.cert_hash)
    expect(await certSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
    expect((await certErrors(cert)).length === 0).toBe(expected.cert_valid)
  })

  it('cert-canonical-minimal: absence-not-null, distinct hash from full form', async () => {
    const c = loadCase('cert-canonical-minimal')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      cert_hash: string
      principal_signature_verifies: boolean
      optional_fields_in_canonical_form: boolean
      differs_from_full_form_cert_hash: string
    }

    const signingInput = new TextDecoder().decode(certSigningInput(cert))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)
    const hasOptional =
      signingInput.includes('"context_id"') ||
      signingInput.includes('"not_before"') ||
      signingInput.includes('"scope"')
    expect(hasOptional).toBe(expected.optional_fields_in_canonical_form)

    expect(certHash(cert)).toBe(expected.cert_hash)
    expect(expected.cert_hash).not.toBe(expected.differs_from_full_form_cert_hash)
    expect(await certSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
  })

  it('cert-invalid-self: signature verifies, certificate rejected as evidence', async () => {
    const c = loadCase('cert-invalid-self')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      cert_hash: string
      principal_signature_verifies: boolean
      cert_valid: boolean
      errors: string[]
    }

    expect(certHash(cert)).toBe(expected.cert_hash)
    expect(await certSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
    const errors = await certErrors(cert)
    expect(errors.length === 0).toBe(expected.cert_valid)
    expect(errors).toEqual(expected.errors)
  })

  it('cert-invalid-wrong-signer: principal signature fails, certificate rejected', async () => {
    const c = loadCase('cert-invalid-wrong-signer')
    const cert = c.input.certificate as DelegationCertificate
    const expected = c.expected as {
      cert_hash: string
      principal_signature_verifies: boolean
      cert_valid: boolean
      errors: string[]
    }

    expect(certHash(cert)).toBe(expected.cert_hash)
    expect(await certSignatureVerifies(cert)).toBe(expected.principal_signature_verifies)
    const errors = await certErrors(cert)
    expect(errors.length === 0).toBe(expected.cert_valid)
    expect(errors).toEqual(expected.errors)
  })

  // Shared runner for the walk cases: record signature is checked with the
  // UNCHANGED §1.4.3 procedure, then the delegation outcome is compared
  // deep-equal against the corpus contract.
  async function assertWalkCase(name: string): Promise<void> {
    const c = loadCase(name)
    const record = c.input.record as DelegatedRecord
    const genesis = (c.input.genesis_record ?? null) as DelegatedRecord | null
    const certs = c.input.certificates as DelegationCertificate[]
    const expected = c.expected as {
      record_signature_valid: boolean
      record_hash: string
      delegation: DelegationOutcome
    }

    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_valid)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(record)))).toBe(expected.record_hash)

    const outcome = await evaluateDelegation(record, genesis, certs)
    expect(outcome).toEqual(expected.delegation)
  }

  it('walk-valid: depth-1 resolution with all facts positive', async () => {
    await assertWalkCase('walk-valid')
  })

  it('walk-expired: in_window false is a signal; record stays valid', async () => {
    await assertWalkCase('walk-expired')
    const c = loadCase('walk-expired')
    const record = c.input.record as DelegatedRecord
    const cert = (c.input.certificates as DelegationCertificate[])[0]
    expect(cert).toBeDefined()
    expect(record.timestamp).toBeGreaterThan(cert!.not_after)
  })

  it('walk-scope-mismatch: out-of-scope is a signal, not invalidation (§6.7.3)', async () => {
    await assertWalkCase('walk-scope-mismatch')
    const c = loadCase('walk-scope-mismatch')
    // The signal-not-block invariant: the corpus pins record validity true
    // alongside in_scope false.
    expect((c.expected as { signal_not_block: boolean }).signal_not_block).toBe(true)
    expect((c.expected as { record_signature_valid: boolean }).record_signature_valid).toBe(true)
    const delegation = (c.expected as { delegation: DelegationOutcome }).delegation
    expect(delegation.scope_check?.in_scope).toBe(false)
  })

  it('walk-wrong-principal-signature: invalid cert falls back to depth 0', async () => {
    await assertWalkCase('walk-wrong-principal-signature')
  })

  it('walk-run-key-mismatch: cert never selected; delegation_unresolved surfaces', async () => {
    await assertWalkCase('walk-run-key-mismatch')
    const c = loadCase('walk-run-key-mismatch')
    const record = c.input.record as DelegatedRecord
    const cert = (c.input.certificates as DelegationCertificate[])[0]
    expect(cert).toBeDefined()
    expect(cert!.run_pubkey).not.toBe(record.creator_key)
    expect(record.delegation_cert_hash).toBe(certHash(cert!))
  })

  it('depth0-identity: byte-identical to the §1.4 corpus, delegation depth 0', async () => {
    const c = loadCase('depth0-identity')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      canonical_signing_input: string
      signature_base64url: string
      record_hash_hex: string
      record_signature_valid: boolean
      byte_identical_to_1_4_vector: boolean
      delegation: DelegationOutcome
    }

    // Byte identity against the live §1.4 corpus file: the embedded record
    // and expectations must equal the source vector exactly.
    const vectors = JSON.parse(readFileSync(SIGNING_VECTORS_1_4, 'utf8')) as {
      vectors: {
        input: { record: Record<string, unknown> }
        expected: Record<string, unknown>
      }[]
    }
    const sourceIndex = c.input.source_vector_index as number
    const source = vectors.vectors[sourceIndex]
    expect(source).toBeDefined()
    // The §1.4 vector's input.record carries signature: "" (signing is the
    // exercise there); the signed form is input.record + expected signature.
    expect(record).toEqual({
      ...source!.input.record,
      signature: source!.expected.signature_base64url,
    })
    expect(expected.canonical_signing_input).toBe(source!.expected.canonical_signing_input)
    expect(expected.signature_base64url).toBe(source!.expected.signature_base64url)
    expect(expected.record_hash_hex).toBe(source!.expected.record_hash_hex)
    expect(expected.byte_identical_to_1_4_vector).toBe(true)

    // Verification is byte-for-byte today's §1.4.3 procedure.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(record))
    expect(signingInput).toBe(expected.canonical_signing_input)
    expect(record.signature).toBe(expected.signature_base64url)
    expect(hexEncode(sha256(canonicalRecord(record)))).toBe(expected.record_hash_hex)
    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_valid)

    // With no certificate, the walk returns depth 0: attribution to
    // creator_key exactly as today.
    const outcome = await evaluateDelegation(record, null, [])
    expect(outcome).toEqual(expected.delegation)
  })

  it('genesis-field-canonical-form: lex slot between creator_key and event_type; distinct signatures', async () => {
    const c = loadCase('genesis-field-canonical-form')
    const withField = c.input.record_with_field as DelegatedRecord
    const withoutField = c.input.record_without_field as DelegatedRecord
    const expected = c.expected as {
      with_field_canonical_signing_input_utf8: string
      without_field_canonical_signing_input_utf8: string
      field_slots_after: string
      field_slots_before: string
      with_field_record_hash: string
      without_field_record_hash: string
      signatures_distinct: boolean
      record_hashes_distinct: boolean
      delegation_cert_hash: string
    }

    const withInput = new TextDecoder().decode(canonicalSigningInput(withField))
    const withoutInput = new TextDecoder().decode(canonicalSigningInput(withoutField))
    expect(withInput).toBe(expected.with_field_canonical_signing_input_utf8)
    expect(withoutInput).toBe(expected.without_field_canonical_signing_input_utf8)

    // Lex slotting: creator_key < delegation_cert_hash < event_type.
    const afterIdx = keyIndex(withInput, expected.field_slots_after)
    const fieldIdx = keyIndex(withInput, 'delegation_cert_hash')
    const beforeIdx = keyIndex(withInput, expected.field_slots_before)
    expect(afterIdx).toBeGreaterThanOrEqual(0)
    expect(fieldIdx).toBeGreaterThan(afterIdx)
    expect(beforeIdx).toBeGreaterThan(fieldIdx)

    // Absence-not-null: the without-form omits the field entirely.
    expect(withoutInput.includes('delegation_cert_hash')).toBe(false)
    expect(withoutInput.includes('null')).toBe(false)

    // Presence/absence changes the canonical form: distinct signatures + hashes.
    expect(withField.signature === withoutField.signature).toBe(!expected.signatures_distinct)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(withField)))).toBe(expected.with_field_record_hash)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(withoutField)))).toBe(
      expected.without_field_record_hash,
    )
    expect(expected.with_field_record_hash === expected.without_field_record_hash).toBe(
      !expected.record_hashes_distinct,
    )

    // The committed hash is the certificate's hash, and both records verify.
    expect(withField.delegation_cert_hash).toBe(expected.delegation_cert_hash)
    expect(certHash(c.input.certificate as DelegationCertificate)).toBe(expected.delegation_cert_hash)
    expect(await verifyRecordSignature(withField)).toBe(true)
    expect(await verifyRecordSignature(withoutField)).toBe(true)
  })

  // Shared runner for the §1.9-extension revocation cases.
  async function assertRevocationCase(name: string): Promise<{
    caseFile: CaseFile
    auth: { authorized: boolean; rule?: string; reason?: string }
  }> {
    const c = loadCase(name)
    const entries = c.input.log_entries as { log_index: number; record: AtribRecord }[]
    const certs = c.input.certificates as DelegationCertificate[]
    const expected = c.expected as {
      revocation_signature_valid: boolean
      revoker_authorized: boolean
      verification_states: Record<string, string>
    }

    const revEntry = entries.find(
      (e) => e.record.event_type === 'https://atrib.dev/v1/types/key_revocation',
    )
    expect(revEntry).toBeDefined()
    const rev = revEntry!.record as KeyRevocationRecord

    // The revocation record's own signature (principal-signed; extra fields
    // covered by the signature since JCS canonicalizes the full body).
    expect(await verifyRecordSignature(rev)).toBe(expected.revocation_signature_valid)

    // §1.9.2 authorization including rule 3.
    const auth = await revokerAuthorized(rev, certs)
    expect(auth.authorized).toBe(expected.revoker_authorized)

    // Only authorized revocations enter the registry; then §1.9.3 applies.
    const authorized: MinimalRecord[] = []
    for (const e of entries) {
      const r = e.record as KeyRevocationRecord
      if (r.event_type !== 'https://atrib.dev/v1/types/key_revocation') continue
      if (!(await revokerAuthorized(r, certs)).authorized) continue
      authorized.push({ ...r, log_index: e.log_index })
    }
    const registry = buildRevocationRegistry(authorized)
    for (const e of entries) {
      const want = expected.verification_states[String(e.log_index)]
      if (want === undefined) continue
      const state = applyRevocation(
        {
          creator_key: e.record.creator_key,
          log_index: e.log_index,
          verification_state: 'signature_valid' as VerificationState,
        },
        registry,
      )
      expect(state, `${name} log_index ${e.log_index}`).toBe(want)
    }
    return { caseFile: c, auth }
  }

  it('revocation-run-key: principal-signed run-key revocation (§1.9.2 rule 3)', async () => {
    const { caseFile, auth } = await assertRevocationCase('revocation-run-key')
    const expected = caseFile.expected as {
      revocation_canonical_signing_input_utf8: string
      revoker_rule: string
      field_slots_after: string
      field_slots_before: string
      record_hashes: Record<string, string>
    }
    expect(auth.rule).toBe(expected.revoker_rule)

    const entries = caseFile.input.log_entries as { log_index: number; record: AtribRecord }[]
    const rev = entries.find(
      (e) => e.record.event_type === 'https://atrib.dev/v1/types/key_revocation',
    )!.record as KeyRevocationRecord

    // Canonical signing input pins the JCS order: creator_key <
    // delegation_cert_hash < event_type.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(rev))
    expect(signingInput).toBe(expected.revocation_canonical_signing_input_utf8)
    const afterIdx = keyIndex(signingInput, expected.field_slots_after)
    const fieldIdx = keyIndex(signingInput, 'delegation_cert_hash')
    const beforeIdx = keyIndex(signingInput, expected.field_slots_before)
    expect(afterIdx).toBeGreaterThanOrEqual(0)
    expect(fieldIdx).toBeGreaterThan(afterIdx)
    expect(beforeIdx).toBeGreaterThan(fieldIdx)

    // Record hashes reproduce.
    for (const e of entries) {
      expect('sha256:' + hexEncode(sha256(canonicalRecord(e.record)))).toBe(
        expected.record_hashes[String(e.log_index)],
      )
    }
  })

  it('revocation-cert-not-covering: unauthorized revoker rejected, states unaffected', async () => {
    const { caseFile, auth } = await assertRevocationCase('revocation-cert-not-covering')
    const expected = caseFile.expected as { rejection_reason: string }
    expect(auth.reason).toBe(expected.rejection_reason)
  })

  it('multi-producer-cert-bound-null: joining run key keeps cert_bound null (D067)', async () => {
    const c = loadCase('multi-producer-cert-bound-null')
    const record = c.input.record as DelegatedRecord
    const genesis = c.input.genesis_record as DelegatedRecord
    const certs = c.input.certificates as DelegationCertificate[]
    const expected = c.expected as {
      record_signature_valid: boolean
      record_hash: string
      genesis_creator_key: string
      genesis_signed_by_record_creator: boolean
      delegation: DelegationOutcome
    }

    // The context genesis was signed by a different producer key.
    expect(genesis.creator_key).toBe(expected.genesis_creator_key)
    expect(genesis.creator_key === record.creator_key).toBe(
      expected.genesis_signed_by_record_creator,
    )
    // The joining record chains to the other producer's genesis (§1.2.3.1).
    expect(record.chain_root).toBe('sha256:' + hexEncode(sha256(canonicalRecord(genesis))))

    expect(await verifyRecordSignature(record)).toBe(expected.record_signature_valid)
    expect('sha256:' + hexEncode(sha256(canonicalRecord(record)))).toBe(expected.record_hash)

    const outcome = await evaluateDelegation(record, genesis, certs)
    expect(outcome).toEqual(expected.delegation)
    expect(outcome.cert_bound).toBeNull()
    expect(outcome.context_bound).toBe(true)
  })
})
