// SPDX-License-Identifier: Apache-2.0

/**
 * session_checkpoint conformance (P044 ADR, spec §1.2.10).
 *
 * Loads each case from spec/conformance/session-checkpoint/cases/ and
 * asserts the expected invariants. The corpus itself is regenerated by
 * packages/log-dev/scripts/generate-conformance-session-checkpoint.ts;
 * this test consumes the COMMITTED vectors (never the generator) and
 * re-derives every root, proof, and canonical form with an independent
 * in-test RFC 6962 implementation plus the @atrib/mcp signing primitives.
 *
 * Families:
 *   schema-*                checkpoint object presence rules (required on
 *                           session_checkpoint, rejected elsewhere; the
 *                           §1.2.7 / §1.2.9 pattern)
 *   tree-*                  real RFC 6962 roots over ordered record-hash
 *                           leaves (§2.3.2 leaf rule, raw 32-byte preimages)
 *   consistency-*           append-only extension + equivocation pair
 *   retroactive-* and freshness-*  present-only-when-true flag, absence-not-null,
 *                           categorical freshness facts
 *   byte-uri-duality        0xFF vs 0x08 log-entry encodings over
 *                           byte-identical signed records
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import canonicalize from 'canonicalize'
import {
  canonicalRecord,
  canonicalSigningInput,
  hexDecode,
  hexEncode,
  serializeEntry,
  sha256,
  verifyRecord as verifyRecordSignature,
  type AtribRecord,
} from '@atrib/mcp'

const CORPUS = join(__dirname, '../../../spec/conformance/session-checkpoint/cases')

const SESSION_CHECKPOINT_URI = 'https://atrib.dev/v1/types/session_checkpoint'

interface SessionCheckpoint {
  first_index: number
  prior_checkpoint?: string
  retroactive?: boolean
  session_root: string
  tree_size: number
}

type SessionCheckpointRecord = AtribRecord & { checkpoint?: SessionCheckpoint }

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

// ---------------------------------------------------------------------------
// Independent RFC 6962 §2.1 implementation (consumes committed vectors only)
// ---------------------------------------------------------------------------

function concatBytes(...parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0))
  let offset = 0
  for (const p of parts) {
    out.set(p, offset)
    offset += p.length
  }
  return out
}

function leafHash(leaf: Uint8Array): Uint8Array {
  return sha256(concatBytes(Uint8Array.of(0x00), leaf))
}

function nodeHash(left: Uint8Array, right: Uint8Array): Uint8Array {
  return sha256(concatBytes(Uint8Array.of(0x01), left, right))
}

function largestPowerOfTwoLessThan(n: number): number {
  let k = 1
  while (k * 2 < n) k *= 2
  return k
}

function merkleTreeHash(leaves: Uint8Array[]): Uint8Array {
  if (leaves.length === 0) return sha256(new Uint8Array(0))
  if (leaves.length === 1) return leafHash(leaves[0]!)
  const k = largestPowerOfTwoLessThan(leaves.length)
  return nodeHash(merkleTreeHash(leaves.slice(0, k)), merkleTreeHash(leaves.slice(k)))
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false
  return true
}

/** RFC 6962 §2.1.4.2 consistency-proof verification. */
function verifyConsistency(
  m: number,
  n: number,
  firstRoot: Uint8Array,
  secondRoot: Uint8Array,
  proof: Uint8Array[],
): boolean {
  if (m === n) return proof.length === 0 && bytesEqual(firstRoot, secondRoot)
  if (m < 1 || m > n) return false
  let c = proof.slice()
  if ((m & (m - 1)) === 0) c = [firstRoot, ...c]
  if (c.length === 0) return false
  let fn = m - 1
  let sn = n - 1
  while ((fn & 1) === 1) {
    fn >>= 1
    sn >>= 1
  }
  let fr = c[0]!
  let sr = c[0]!
  for (let i = 1; i < c.length; i++) {
    if (sn === 0) return false
    if ((fn & 1) === 1 || fn === sn) {
      fr = nodeHash(c[i]!, fr)
      sr = nodeHash(c[i]!, sr)
      if ((fn & 1) === 0) {
        while (fn !== 0 && (fn & 1) === 0) {
          fn >>= 1
          sn >>= 1
        }
      }
    } else {
      sr = nodeHash(sr, c[i]!)
    }
    fn >>= 1
    sn >>= 1
  }
  return bytesEqual(fr, firstRoot) && bytesEqual(sr, secondRoot) && sn === 0
}

function leafBytesFromRef(ref: string): Uint8Array {
  return hexDecode(ref.slice('sha256:'.length))
}

function sessionRootHexFromRefs(refs: string[]): string {
  return hexEncode(merkleTreeHash(refs.map(leafBytesFromRef)))
}

// ---------------------------------------------------------------------------
// Reference §1.2.10 structural validator (validator-role rules)
// ---------------------------------------------------------------------------

const SHA256_REF = /^sha256:[0-9a-f]{64}$/

/**
 * Returns undefined when the record passes the §1.2.10 structural rules,
 * or the rejection reason otherwise. Mirrors the validator conformance
 * targets: checkpoint REQUIRED on session_checkpoint and REJECTED on any
 * other event_type; tree_size >= 1; 0 <= first_index < tree_size;
 * prior_checkpoint present iff first_index > 0; retroactive true-only.
 */
function validateSessionCheckpointStructural(record: SessionCheckpointRecord): string | undefined {
  const isCheckpointType = record.event_type === SESSION_CHECKPOINT_URI
  const cp = record.checkpoint
  if (isCheckpointType && cp === undefined) {
    return 'checkpoint missing on session_checkpoint record'
  }
  if (!isCheckpointType && cp !== undefined) {
    return 'checkpoint on non-session_checkpoint event_type'
  }
  if (cp === undefined) return undefined
  if (!SHA256_REF.test(cp.session_root)) return 'malformed session_root'
  if (!Number.isInteger(cp.tree_size) || cp.tree_size < 1) return 'tree_size < 1'
  if (!Number.isInteger(cp.first_index) || cp.first_index < 0) return 'malformed first_index'
  if (cp.first_index >= cp.tree_size) return 'first_index >= tree_size'
  if (cp.prior_checkpoint !== undefined && !SHA256_REF.test(cp.prior_checkpoint)) {
    return 'malformed prior_checkpoint'
  }
  if (cp.prior_checkpoint !== undefined && cp.first_index === 0) {
    return 'prior_checkpoint present with first_index == 0'
  }
  if (cp.prior_checkpoint === undefined && cp.first_index > 0) {
    return 'prior_checkpoint absent with first_index > 0'
  }
  if (cp.retroactive !== undefined && cp.retroactive !== true) {
    return 'retroactive: false emitted'
  }
  return undefined
}

/** Categorical freshness fact per §1.2.10 (verifier-role, signal not block). */
function freshnessFact(
  record: SessionCheckpointRecord,
  maxCoveredLeafTimestamp: number,
  boundMs: number,
): 'contemporaneous' | 'declared-retroactive' | 'stale-undeclared' {
  if (record.checkpoint?.retroactive === true) return 'declared-retroactive'
  if (record.timestamp - maxCoveredLeafTimestamp > boundMs) return 'stale-undeclared'
  return 'contemporaneous'
}

function recordHashHex(record: AtribRecord): string {
  return hexEncode(sha256(canonicalRecord(record)))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('session_checkpoint conformance (§1.2.10)', () => {
  it('schema-first-checkpoint: valid first checkpoint, JCS slot, root, freshness', async () => {
    const c = loadCase('schema-first-checkpoint')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      record_hash_hex: string
      session_root: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      verifier_freshness_fact: string
    }

    // Canonical signing input matches the spec-mandated JCS form.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(record))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)

    // JCS slot: `checkpoint` sorts after `chain_root` and before `content_id`.
    const chainRootIdx = signingInput.indexOf('"chain_root"')
    const checkpointIdx = signingInput.indexOf('"checkpoint"')
    const contentIdIdx = signingInput.indexOf('"content_id"')
    expect(chainRootIdx).toBeGreaterThanOrEqual(0)
    expect(checkpointIdx).toBeGreaterThan(chainRootIdx)
    expect(contentIdIdx).toBeGreaterThan(checkpointIdx)

    // record_hash and signature.
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)
    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)

    // First-checkpoint presence rules: no prior_checkpoint, first_index 0.
    expect(record.checkpoint!.first_index).toBe(0)
    expect('prior_checkpoint' in record.checkpoint!).toBe(false)
    expect('retroactive' in record.checkpoint!).toBe(false)

    // Real RFC 6962 root over the ordered record-hash leaves.
    expect(`sha256:${sessionRootHexFromRefs(leaves)}`).toBe(expected.session_root)
    expect(record.checkpoint!.session_root).toBe(expected.session_root)

    // Leaves ARE the covered records' canonical hashes.
    const leafRecords = c.input.leaf_records as AtribRecord[]
    leafRecords.forEach((leafRecord, i) => {
      expect(`sha256:${recordHashHex(leafRecord)}`).toBe(leaves[i])
    })

    // args_hash commits the flat leaf list per D099: sha256(JCS({leaves})).
    const jcs = canonicalize({ leaves })
    expect(jcs).toBeDefined()
    expect(record.args_hash).toBe(`sha256:${hexEncode(sha256(new TextEncoder().encode(jcs!)))}`)

    // Structural validation accepts; freshness is contemporaneous.
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
    expect(expected.validator_should_accept).toBe(true)
    const maxLeafTs = c.input.max_covered_leaf_timestamp as number
    expect(freshnessFact(record, maxLeafTs, 24 * 60 * 60 * 1000)).toBe(
      expected.verifier_freshness_fact,
    )
  })

  it.each([
    ['schema-missing-checkpoint-rejected'],
    ['schema-checkpoint-on-wrong-event-type-rejected'],
    ['schema-first-index-bounds-rejected'],
    ['schema-prior-present-at-first-index-zero-rejected'],
    ['schema-prior-absent-at-positive-first-index-rejected'],
    ['tree-empty-rejected'],
    ['retroactive-false-rejected'],
  ])('%s: signature valid, structural validation rejects with the pinned reason', async (name) => {
    const c = loadCase(name)
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      record_hash_hex: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      rejection_reason: string
    }

    // Signature itself verifies; rejection is at the policy layer.
    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)

    // Structural validation MUST reject with the pinned reason.
    expect(expected.validator_should_accept).toBe(false)
    expect(validateSessionCheckpointStructural(record)).toBe(expected.rejection_reason)
  })

  it('tree-1-leaf: root over a single leaf equals sha256(0x00 || leaf_bytes)', async () => {
    const c = loadCase('tree-1-leaf')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const expected = c.expected as {
      session_root_hex: string
      leaf_hash_equals_root: boolean
      verifier_signature_ok: boolean
    }

    expect(leaves).toHaveLength(1)
    expect(sessionRootHexFromRefs(leaves)).toBe(expected.session_root_hex)
    expect(record.checkpoint!.session_root).toBe(`sha256:${expected.session_root_hex}`)
    expect(record.checkpoint!.tree_size).toBe(1)

    // MTH([x]) = leaf_hash(x): the single-leaf root IS the leaf hash.
    const single = hexEncode(leafHash(leafBytesFromRef(leaves[0]!)))
    expect(single === expected.session_root_hex).toBe(expected.leaf_hash_equals_root)

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
  })

  it('tree-2-leaves: two-leaf root; hex-string leaves MUST NOT reproduce it', async () => {
    const c = loadCase('tree-2-leaves')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const expected = c.expected as {
      session_root_hex: string
      hex_string_leaf_root_hex: string
      hex_string_leaf_root_must_not_match: boolean
    }

    expect(leaves).toHaveLength(2)
    expect(sessionRootHexFromRefs(leaves)).toBe(expected.session_root_hex)
    expect(record.checkpoint!.session_root).toBe(`sha256:${expected.session_root_hex}`)

    // Raw-32-byte-leaf trap: a tree over the UTF-8 bytes of the prefixed
    // hex strings produces a DIFFERENT root. Leaves are raw hash bytes.
    const utf8 = new TextEncoder()
    const trapRoot = hexEncode(merkleTreeHash(leaves.map((ref) => utf8.encode(ref))))
    expect(trapRoot).toBe(expected.hex_string_leaf_root_hex)
    expect(trapRoot !== expected.session_root_hex).toBe(
      expected.hex_string_leaf_root_must_not_match,
    )
  })

  it('tree-5-leaves: odd unbalanced root; prior checkpoint is a leaf, never itself', async () => {
    const c = loadCase('tree-5-leaves')
    const record = c.input.record as SessionCheckpointRecord
    const leaves = c.input.leaves as string[]
    const priorRecord = c.input.prior_checkpoint_record as SessionCheckpointRecord
    const expected = c.expected as {
      session_root_hex: string
      prior_checkpoint_is_leaf_at_index: number
      verifier_signature_ok: boolean
    }

    expect(leaves).toHaveLength(5)
    expect(sessionRootHexFromRefs(leaves)).toBe(expected.session_root_hex)
    expect(record.checkpoint!.session_root).toBe(`sha256:${expected.session_root_hex}`)
    expect(record.checkpoint!.tree_size).toBe(5)

    // The prior checkpoint appears as a leaf in the NEXT tree (self-exclusion:
    // a checkpoint's own hash depends on session_root, so it can never be
    // a leaf of its own tree).
    const priorHash = `sha256:${recordHashHex(priorRecord)}`
    expect(leaves[expected.prior_checkpoint_is_leaf_at_index]).toBe(priorHash)
    expect(leaves).not.toContain(`sha256:${recordHashHex(record)}`)

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
  })

  it('tree-empty-rejected: RFC 6962 empty-tree root sentinel is pinned', () => {
    const c = loadCase('tree-empty-rejected')
    const expected = c.expected as { rfc6962_empty_tree_root_hex: string }
    // MTH([]) = SHA-256("") per RFC 6962; atrib prohibits committing to it.
    expect(hexEncode(sha256(new Uint8Array(0)))).toBe(expected.rfc6962_empty_tree_root_hex)
    expect(hexEncode(merkleTreeHash([]))).toBe(expected.rfc6962_empty_tree_root_hex)
  })

  it('consistency-valid-extension: append-only K1 → K2 with a verifying §2.1.4 proof', async () => {
    const c = loadCase('consistency-valid-extension')
    const k1 = c.input.first_checkpoint as SessionCheckpointRecord
    const k2 = c.input.second_checkpoint as SessionCheckpointRecord
    const firstLeaves = c.input.first_leaves as string[]
    const secondLeaves = c.input.second_leaves as string[]
    const proofHex = c.input.consistency_proof_hex as string[]
    const expected = c.expected as {
      first_record_hash: string
      prior_checkpoint_matches: boolean
      first_index_equals_prior_tree_size: boolean
      consistency_proof_verifies: boolean
      append_only: boolean
    }

    // Both records are genuinely signed and structurally valid.
    expect(await verifyRecordSignature(k1)).toBe(true)
    expect(await verifyRecordSignature(k2)).toBe(true)
    expect(validateSessionCheckpointStructural(k1)).toBeUndefined()
    expect(validateSessionCheckpointStructural(k2)).toBeUndefined()

    // Linkage: prior_checkpoint = record hash of K1; first_index = K1.tree_size.
    expect(`sha256:${recordHashHex(k1)}`).toBe(expected.first_record_hash)
    expect(k2.checkpoint!.prior_checkpoint === expected.first_record_hash).toBe(
      expected.prior_checkpoint_matches,
    )
    expect(k2.checkpoint!.first_index === k1.checkpoint!.tree_size).toBe(
      expected.first_index_equals_prior_tree_size,
    )

    // Append-only: the leaf prefix 0..K1.tree_size-1 is identical.
    expect(secondLeaves.slice(0, k1.checkpoint!.tree_size)).toEqual(firstLeaves)
    expect(expected.append_only).toBe(true)

    // Roots recompute from the committed leaf lists.
    expect(`sha256:${sessionRootHexFromRefs(firstLeaves)}`).toBe(k1.checkpoint!.session_root)
    expect(`sha256:${sessionRootHexFromRefs(secondLeaves)}`).toBe(k2.checkpoint!.session_root)

    // The committed RFC 6962 §2.1.4 consistency proof verifies from
    // (K1.session_root, 2) to (K2.session_root, 5).
    const proof = proofHex.map(hexDecode)
    const ok = verifyConsistency(
      k1.checkpoint!.tree_size,
      k2.checkpoint!.tree_size,
      leafBytesFromRef(k1.checkpoint!.session_root),
      leafBytesFromRef(k2.checkpoint!.session_root),
      proof,
    )
    expect(ok).toBe(expected.consistency_proof_verifies)

    // Tamper check: a truncated proof MUST NOT verify.
    expect(
      verifyConsistency(
        k1.checkpoint!.tree_size,
        k2.checkpoint!.tree_size,
        leafBytesFromRef(k1.checkpoint!.session_root),
        leafBytesFromRef(k2.checkpoint!.session_root),
        proof.slice(0, proof.length - 1),
      ),
    ).toBe(false)
  })

  it('consistency-equivocation-pair: same prior, divergent roots → equivocation fact', async () => {
    const c = loadCase('consistency-equivocation-pair')
    const a = c.input.first_variant as SessionCheckpointRecord
    const b = c.input.second_variant as SessionCheckpointRecord
    const aLeaves = c.input.first_variant_leaves as string[]
    const bLeaves = c.input.second_variant_leaves as string[]
    const expected = c.expected as {
      both_signatures_verify: boolean
      same_creator_key: boolean
      same_prior_checkpoint: boolean
      roots_diverge: boolean
      equivocation: boolean
    }

    // Both signatures are genuine: the pair itself is the evidence.
    expect((await verifyRecordSignature(a)) && (await verifyRecordSignature(b))).toBe(
      expected.both_signatures_verify,
    )
    expect(a.creator_key === b.creator_key).toBe(expected.same_creator_key)
    expect(
      a.checkpoint!.prior_checkpoint === b.checkpoint!.prior_checkpoint &&
        a.checkpoint!.prior_checkpoint === (c.input.shared_prior_checkpoint as string),
    ).toBe(expected.same_prior_checkpoint)

    // Each root recomputes from its own committed leaf list, yet they diverge.
    expect(`sha256:${sessionRootHexFromRefs(aLeaves)}`).toBe(a.checkpoint!.session_root)
    expect(`sha256:${sessionRootHexFromRefs(bLeaves)}`).toBe(b.checkpoint!.session_root)
    expect(a.checkpoint!.session_root !== b.checkpoint!.session_root).toBe(expected.roots_diverge)

    // Categorical equivocation fact: same creator_key, same prior_checkpoint,
    // same covered range, inconsistent roots.
    const equivocation =
      a.creator_key === b.creator_key &&
      a.checkpoint!.prior_checkpoint === b.checkpoint!.prior_checkpoint &&
      a.checkpoint!.tree_size === b.checkpoint!.tree_size &&
      a.checkpoint!.session_root !== b.checkpoint!.session_root
    expect(equivocation).toBe(expected.equivocation)
  })

  it('retroactive-declared: backfill checkpoint carries retroactive: true', async () => {
    const c = loadCase('retroactive-declared')
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      record_hash_hex: string
      retroactive_present: boolean
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      verifier_freshness_fact: string
    }

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)
    expect(record.checkpoint!.retroactive === true).toBe(expected.retroactive_present)
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
    expect(expected.validator_should_accept).toBe(true)

    const maxLeafTs = c.input.max_covered_leaf_timestamp as number
    const bound = c.input.verifier_staleness_bound_ms as number
    expect(freshnessFact(record, maxLeafTs, bound)).toBe(expected.verifier_freshness_fact)
  })

  it('retroactive-absence-not-null: absence and presence produce different signed bytes', async () => {
    const c = loadCase('retroactive-absence-not-null')
    const plain = c.input.record_without_flag as SessionCheckpointRecord
    const flagged = c.input.record_with_flag as SessionCheckpointRecord
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      retroactive_in_canonical_form: boolean
      record_hash_hex_without_flag: string
      record_hash_hex_with_flag: string
      record_hashes_differ: boolean
      validator_should_accept_both: boolean
    }

    // The non-retroactive canonical form contains no "retroactive" key.
    const signingInput = new TextDecoder().decode(canonicalSigningInput(plain))
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)
    expect(signingInput.includes('retroactive')).toBe(expected.retroactive_in_canonical_form)

    // Same payload except retroactive: true → different hash and signature.
    expect(recordHashHex(plain)).toBe(expected.record_hash_hex_without_flag)
    expect(recordHashHex(flagged)).toBe(expected.record_hash_hex_with_flag)
    expect(recordHashHex(plain) !== recordHashHex(flagged)).toBe(expected.record_hashes_differ)
    expect(plain.signature).not.toBe(flagged.signature)

    // Both variants are valid: absence and true are the only legal states.
    expect(await verifyRecordSignature(plain)).toBe(true)
    expect(await verifyRecordSignature(flagged)).toBe(true)
    expect(validateSessionCheckpointStructural(plain)).toBeUndefined()
    expect(validateSessionCheckpointStructural(flagged)).toBeUndefined()
    expect(expected.validator_should_accept_both).toBe(true)
  })

  it('freshness-stale-undeclared: stale checkpoint without the flag gets the fact, not a block', async () => {
    const c = loadCase('freshness-stale-undeclared')
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      verifier_freshness_fact: string
    }

    expect(await verifyRecordSignature(record)).toBe(expected.verifier_signature_ok)

    // Signal, not block: structurally valid, validators accept.
    expect(validateSessionCheckpointStructural(record)).toBeUndefined()
    expect(expected.validator_should_accept).toBe(true)

    const maxLeafTs = c.input.max_covered_leaf_timestamp as number
    const bound = c.input.verifier_staleness_bound_ms as number
    expect(freshnessFact(record, maxLeafTs, bound)).toBe(expected.verifier_freshness_fact)
  })

  it('byte-uri-duality: identical signed bytes under 0xFF and 0x08 log entries', async () => {
    const c = loadCase('byte-uri-duality')
    const record = c.input.record as SessionCheckpointRecord
    const expected = c.expected as {
      record_hash_hex: string
      entry_pre_promotion_hex: string
      entry_post_promotion_hex: string
      pre_promotion_event_type_byte: number
      post_promotion_event_type_byte: number
      entries_identical_except_byte_89: boolean
    }

    // The signed record verifies; its event_type is the URI, so the signed
    // bytes carry no log-entry byte at all.
    expect(await verifyRecordSignature(record)).toBe(true)
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)

    // Pre-promotion: the log operator encodes the (not-yet-normative) URI
    // under the 0xFF extension slot per §2.3.1.
    const entryPre = serializeEntry({
      record_hash_hex: recordHashHex(record),
      creator_key_b64url: record.creator_key,
      context_id: record.context_id,
      timestamp: record.timestamp,
      event_type: record.event_type,
    })
    expect(hexEncode(entryPre)).toBe(expected.entry_pre_promotion_hex)
    expect(entryPre[89]).toBe(expected.pre_promotion_event_type_byte)

    // Post-promotion: same 90-byte entry with byte 89 flipped to 0x08.
    const entryPost = hexDecode(expected.entry_post_promotion_hex)
    expect(entryPost).toHaveLength(90)
    expect(entryPost[89]).toBe(expected.post_promotion_event_type_byte)
    let identicalExceptLast = true
    for (let i = 0; i < 89; i++) {
      if (entryPre[i] !== entryPost[i]) identicalExceptLast = false
    }
    expect(identicalExceptLast && entryPre[89] !== entryPost[89]).toBe(
      expected.entries_identical_except_byte_89,
    )

    // The record itself is byte-identical across the promotion: the entry
    // encodings both commit to the SAME record_hash over the SAME canonical
    // bytes (bytes 1-32 of each entry).
    expect(hexEncode(entryPre.slice(1, 33))).toBe(expected.record_hash_hex)
    expect(hexEncode(entryPost.slice(1, 33))).toBe(expected.record_hash_hex)
  })
})
