// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §2.6.1 conformance: submission API — @atrib/sdk client-side harness.
 *
 * Loads every case from spec/conformance/2.6.1/ (manifest.json + cases/) and
 * asserts the client-side parity surface of the SDK against it:
 *
 *   - Steps 2–5 via `validateSubmission` (the shared §2.6.1 validator that
 *     both log servers and clients use; Step 1 is intentionally out of its
 *     scope, see packages/mcp/src/validation.ts).
 *   - Step 1 (Ed25519 signature) via `verifyRecord` (§1.4.3): the
 *     bad-signature case passes structural validation but fails verification.
 *   - Step 0 (non-JSON body): the raw-string body must fail JSON parsing
 *     before any §2.6.1 step could run.
 *   - Step 6 (idempotent resubmission, sequences/) is SKIPPED here with a
 *     justification: it exercises server log state (same log_index on
 *     resubmit, log_size 1 after both steps), which a client-side harness
 *     has no log instance to observe. The corpus README explicitly allows a
 *     per-implementation skip list with a documented reason; the server-side
 *     consumer at packages/log-dev/test/conformance.test.ts owns Step 6.
 *
 * Clock: the corpus stores fully-signed records frozen at
 * manifest.reference_time_ms. The system clock MUST be mocked to that
 * instant — otherwise reject-future-timestamp (Step 4) silently inverts
 * once real time passes the fixture timestamp (a "future" timestamp becomes
 * a past one and validation would wrongly accept it). `vi.setSystemTime`
 * mocks `Date.now()`, which is the only clock source in both
 * `validateSubmission` (10-min window) and `verifyRecord` (5-min window).
 *
 * The corpus is a fixture generated by
 * packages/log-dev/scripts/generate-conformance-corpus.ts; never edit it.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { vi } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  base64urlDecode,
  recordHashHex,
  signRecord,
  validateSubmission,
  verifyRecord,
  type AtribRecord,
} from '../src/index.js'

const CORPUS = join(__dirname, '../../../spec/conformance/2.6.1')

interface ManifestCase {
  file: string
  name: string
  spec_section: string
  validation_step: number | null
  expected_status: number
}

interface Manifest {
  reference_time_ms: number
  signing: {
    seed_b64url: string
    creator_key_b64url: string
    context_id: string
    content_id: string
  }
  cases: ManifestCase[]
  sequences: { file: string; name: string; validation_step: number }[]
  record_hash_index: Record<string, string>
}

interface CaseFile {
  name: string
  spec_section: string
  validation_step: number | null
  description: string
  request: {
    method: string
    path: string
    headers: Record<string, string>
    body: AtribRecord | string
    body_is_raw_string?: boolean
  }
  expected: {
    status: number
    error_contains?: string
    response_shape?: Record<string, string>
  }
}

const manifest = JSON.parse(readFileSync(join(CORPUS, 'manifest.json'), 'utf8')) as Manifest

function loadCase(file: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, file), 'utf8')) as CaseFile
}

const acceptCases = manifest.cases.filter((c) => c.validation_step === null)
const rejectCases = manifest.cases.filter((c) => c.validation_step !== null)

describe('spec §2.6.1 conformance (@atrib/sdk)', () => {
  beforeAll(() => {
    vi.useFakeTimers()
    vi.setSystemTime(manifest.reference_time_ms)
  })

  afterAll(() => {
    vi.useRealTimers()
  })

  it('clock is frozen to manifest.reference_time_ms', () => {
    // Sanity gate: every Step 4 outcome below depends on this. If this
    // fails, the reject-future-timestamp assertions are meaningless.
    expect(Date.now()).toBe(manifest.reference_time_ms)
  })

  describe('accept cases (validation_step null → 200)', () => {
    // The corpus pins four accept cases (tool_call, transaction,
    // observation, extension event_type); assert the manifest still
    // enumerates them all so a corpus regeneration can't silently shrink
    // this suite's coverage.
    it('manifest enumerates the accept cases', () => {
      expect(acceptCases.map((c) => c.name).sort()).toEqual([
        'accept-extension-event-type',
        'accept-observation',
        'accept-tool-call',
        'accept-transaction',
      ])
    })

    for (const entry of acceptCases) {
      it(`${entry.name}: validateSubmission ok, §1.4.3 verification passes, record_hash pinned`, async () => {
        const kase = loadCase(entry.file)
        expect(kase.request.body_is_raw_string ?? false).toBe(false)
        const record = kase.request.body as AtribRecord

        // Steps 2–5: structural validation accepts (exact-shape assertion —
        // an ok result carries neither status nor error).
        expect(validateSubmission(record)).toEqual({ ok: true })

        // Step 1: the Ed25519 signature verifies (§1.4.3, all 8 steps —
        // step 7's 5-minute window holds because the clock is frozen at
        // the fixture timestamp).
        expect(await verifyRecord(record)).toBe(true)

        // The manifest pins the record_hash for every accept case:
        // SHA-256(JCS(complete record INCLUDING signature)).
        expect(recordHashHex(record)).toBe(manifest.record_hash_index[entry.name])

        // The fixture was signed with the manifest's deterministic
        // signing inputs.
        expect(record.creator_key).toBe(manifest.signing.creator_key_b64url)
        expect(record.context_id).toBe(manifest.signing.context_id)

        // Ed25519 is deterministic: re-signing the body with the corpus
        // seed must reproduce the fixture signature bit-for-bit.
        const seed = base64urlDecode(manifest.signing.seed_b64url)
        expect(seed).toHaveLength(32)
        const resigned = await signRecord({ ...record }, seed)
        expect(resigned.signature).toBe(record.signature)

        // A conformant log answers 200 with a §2.6.2 proof bundle.
        expect(entry.expected_status).toBe(200)
        expect(kase.expected.status).toBe(200)
      })
    }
  })

  describe('reject cases (validation_step 0–5 → 400)', () => {
    it('manifest enumerates the reject cases', () => {
      expect(rejectCases.map((c) => c.validation_step).sort()).toEqual([0, 1, 2, 3, 4, 5])
    })

    for (const entry of rejectCases) {
      const step = entry.validation_step as number

      if (step === 0) {
        it(`${entry.name} (Step 0): raw-string body fails JSON parsing before any §2.6.1 step`, () => {
          const kase = loadCase(entry.file)
          expect(kase.request.body_is_raw_string).toBe(true)
          expect(typeof kase.request.body).toBe('string')
          expect(() => JSON.parse(kase.request.body as string)).toThrow()
          expect(kase.expected.status).toBe(400)
        })
        continue
      }

      if (step === 1) {
        it(`${entry.name} (Step 1): structural validation passes but Ed25519 verification fails`, async () => {
          const kase = loadCase(entry.file)
          const record = kase.request.body as AtribRecord

          // Step 1 lives in the verifier, not validateSubmission: the body
          // is structurally well-formed, so Steps 2–5 all pass...
          expect(validateSubmission(record)).toEqual({ ok: true })

          // ...and the log's 400 comes from §1.4.3: the signature does not
          // verify against creator_key.
          expect(await verifyRecord(record)).toBe(false)

          expect(kase.expected.status).toBe(400)
        })
        continue
      }

      // Steps 2–5: validateSubmission itself must reject with 400.
      it(`${entry.name} (Step ${step}): validateSubmission rejects with 400`, async () => {
        const kase = loadCase(entry.file)
        const record = kase.request.body as AtribRecord

        // Fixture-shape sanity per pinned step: confirm the case actually
        // exercises the step the manifest attributes it to.
        switch (step) {
          case 2:
            expect(record.spec_version).not.toBe('atrib/1.0')
            break
          case 3:
            // Bare token, no scheme → not a syntactically-valid absolute URI.
            expect(record.event_type).not.toMatch(/^[a-z][a-z0-9+.-]*:/i)
            break
          case 4:
            // Beyond the 10-minute clock-skew window at the frozen clock.
            expect(record.timestamp - manifest.reference_time_ms).toBeGreaterThan(10 * 60 * 1000)
            break
          case 5:
            expect(record.context_id).not.toMatch(/^[0-9a-f]{32}$/)
            break
        }

        const result = validateSubmission(record)
        expect(result.ok).toBe(false)
        expect(result.status).toBe(400)
        expect(result.status).toBe(kase.expected.status)
        expect(typeof result.error).toBe('string')
        if (kase.expected.error_contains !== undefined) {
          expect(result.error).toContain(kase.expected.error_contains)
        }

        // Client parity: §1.4.3 steps 5–8 mirror §2.6.1 Steps 2–5 (with a
        // tighter 5-minute window at step 7), so record verification also
        // fails for each of these bodies.
        expect(await verifyRecord(record)).toBe(false)
      })
    }
  })

  describe('sequences (validation_step 6)', () => {
    // Step 6 (idempotent resubmission) is server log state: submitting the
    // same signed record twice must return the SAME log_index and leave
    // log_size at 1. This harness validates client-side parity surfaces
    // (validateSubmission / verifyRecord) and has no log instance whose
    // post-state it could observe, so the sequence is skipped per the
    // corpus README's per-implementation skip-list allowance. The
    // server-side reference consumer (packages/log-dev/test/conformance.test.ts)
    // covers it against a real log.
    it.skip('idempotent-resubmission: server-state Step 6 — covered by the log-side consumer', () => {
      // Intentionally unreachable; see the justification above.
    })

    it('the skipped sequence is still the only sequence the manifest pins', () => {
      // Guard the skip list: if the corpus grows a new sequence, this test
      // fails and forces a decision instead of a silent gap.
      expect(manifest.sequences.map((s) => s.name)).toEqual(['idempotent-resubmission'])
      expect(manifest.sequences[0].validation_step).toBe(6)
    })
  })
})
