// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §1.2.3.1 conformance: multi-producer chain composition (D067) —
 * @atrib/sdk surface.
 *
 * Loads every case listed in spec/conformance/1.2.3/multi-producer/
 * manifest.json and feeds its input into `resolveChainRoot` (re-exported
 * from @atrib/mcp through the consolidated SDK), asserting the resolved
 * chain_root matches the corpus expectation. The precedence cascade under
 * test is normative: inbound > auto-chain > env-tail > mirror-tail >
 * genesis, with malformed env values falling through and env-var names
 * namespaced per context_id. The corpus itself is a fixture regenerated by
 * packages/log-dev/scripts/generate-conformance-1.2.3-multi-producer.ts;
 * never edit it.
 *
 * Each case supplies its own `env` object which is passed as the env stub
 * (never process.env), so no environment state leaks between cases. JSON
 * nulls in case inputs map to `undefined` arguments.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { genesisChainRoot, resolveChainRoot } from '../src/index.js'

const CORPUS = join(__dirname, '../../../spec/conformance/1.2.3/multi-producer')

interface Manifest {
  spec_section: string
  cases: Array<{ file: string; name: string }>
}

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: {
    context_id: string
    inbound_record_hash_hex: string | null
    auto_chain_tail_hex: string | null
    env: Record<string, string>
    mirror_tail_hex: string | null
  }
  expected: {
    chain_root: string
    precedence_layer: 'inbound' | 'auto-chain' | 'env-tail' | 'mirror-tail' | 'genesis'
  }
}

const manifest = JSON.parse(
  readFileSync(join(CORPUS, 'manifest.json'), 'utf8'),
) as Manifest

function loadCase(file: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, file), 'utf8')) as CaseFile
}

describe('spec §1.2.3.1 multi-producer conformance (@atrib/sdk)', () => {
  it('manifest enumerates the full ten-case corpus', () => {
    expect(manifest.spec_section).toBe('1.2.3')
    expect(manifest.cases).toHaveLength(10)
  })

  for (const entry of manifest.cases) {
    it(`${entry.name}: resolveChainRoot matches expected chain_root`, () => {
      const c = loadCase(entry.file)

      // The case file's self-declared name matches the manifest entry.
      expect(c.name).toBe(entry.name)

      const resolved = resolveChainRoot({
        contextId: c.input.context_id,
        // JSON nulls become undefined: absence, not an empty-string signal.
        inboundRecordHashHex: c.input.inbound_record_hash_hex ?? undefined,
        autoChainTailHex: c.input.auto_chain_tail_hex ?? undefined,
        mirrorTailHex: c.input.mirror_tail_hex ?? undefined,
        // The case env object is the entire environment for resolution;
        // process.env is never consulted so cases cannot leak state.
        env: c.input.env as NodeJS.ProcessEnv,
      })

      expect(resolved).toBe(c.expected.chain_root)

      // Cross-check the declared precedence layer where it is structurally
      // derivable: a genesis-layer expectation must equal the synthetic
      // genesis chain_root for the case's context_id (§1.2.3), and any
      // non-genesis layer must not.
      if (c.expected.precedence_layer === 'genesis') {
        expect(c.expected.chain_root).toBe(genesisChainRoot(c.input.context_id))
      } else {
        expect(c.expected.chain_root).not.toBe(genesisChainRoot(c.input.context_id))
      }
    })
  }

  it('genesis-fallback: final fallback equals genesisChainRoot(context_id)', () => {
    const c = loadCase('cases/genesis-fallback.json')

    // No upstream chain context of any kind: the resolver MUST synthesize
    // the genesis anchor "sha256:" + hex(SHA-256(UTF-8(context_id))).
    const resolved = resolveChainRoot({
      contextId: c.input.context_id,
      env: c.input.env as NodeJS.ProcessEnv,
    })

    expect(resolved).toBe(genesisChainRoot(c.input.context_id))
    expect(resolved).toBe(c.expected.chain_root)
    expect(c.expected.precedence_layer).toBe('genesis')
  })
})
