// SPDX-License-Identifier: Apache-2.0

/**
 * Spec §1.2.6 conformance: provenance_token (D044) — @atrib/sdk surface.
 *
 * Loads each case from spec/conformance/1.2.6/cases/ and asserts the
 * expected invariants against the consolidated SDK exports (the record
 * layer re-exported from @atrib/mcp plus the SDK hash helpers
 * `recordHashHex` / `recordHashRef` / `deriveProvenanceToken`). The corpus
 * itself is a fixture regenerated by
 * packages/log-dev/scripts/generate-conformance-1.2.6.ts; never edit it.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  canonicalSigningInput,
  deriveProvenanceToken,
  genesisChainRoot,
  hexDecode,
  recordHashHex,
  recordHashRef,
  signRecord,
  verifyRecord,
  type AtribRecord,
} from '../src/index.js'

const CORPUS = join(__dirname, '../../../spec/conformance/1.2.6/cases')

interface CaseFile {
  name: string
  spec_section: string
  description: string
  input: Record<string, unknown>
  expected: Record<string, unknown>
}

function loadCase(name: string): CaseFile {
  return JSON.parse(readFileSync(join(CORPUS, `${name}.json`), 'utf8')) as CaseFile
}

function signingInputUtf8(record: AtribRecord): string {
  return new TextDecoder().decode(canonicalSigningInput(record))
}

describe('spec §1.2.6 conformance (@atrib/sdk)', () => {
  it('genesis-with-provenance: canonical form, record_hash, and signature all round-trip', async () => {
    const c = loadCase('genesis-with-provenance')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      record_hash_hex: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
    }

    // JCS field-order invariant: provenance_token slots between event_type
    // (via informed_by position) and spec_version in the canonical form.
    expect(signingInputUtf8(record)).toBe(expected.canonical_signing_input_utf8)

    // record_hash = SHA-256(JCS(complete record INCLUDING signature)).
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)

    // Signature verifies with the field present.
    expect(await verifyRecord(record)).toBe(expected.verifier_signature_ok)

    // Ed25519 is deterministic: re-signing the record body with the corpus
    // seed must reproduce the exact signature the fixture carries.
    const seed = hexDecode(c.input.signer_seed_hex as string)
    const resigned = await signRecord({ ...record }, seed)
    expect(resigned.signature).toBe(record.signature)

    // Validators MUST accept a genesis record carrying provenance_token.
    expect(expected.validator_should_accept).toBe(true)
  })

  it('upstream-derivation: token = base64url(sha256(JCS(upstream))[:16])', async () => {
    const c = loadCase('upstream-derivation')
    const upstream = c.input.upstream_record as AtribRecord
    const downstream = c.input.downstream_record as AtribRecord
    const expected = c.expected as {
      derived_provenance_token: string
      upstream_full_record_hash: string
      downstream_signature_verifies: boolean
      validator_should_accept: boolean
    }

    // The SDK helper reproduces the §1.2.6 derivation from the complete
    // signed upstream record.
    expect(deriveProvenanceToken(upstream)).toBe(expected.derived_provenance_token)

    // 22-char base64url, per §1.2.6 (16 bytes, no padding).
    expect(deriveProvenanceToken(upstream)).toHaveLength(22)

    // The downstream genesis record carries exactly the derived token.
    expect(downstream.provenance_token).toBe(expected.derived_provenance_token)

    // Full upstream hash reference matches (sha256:<64-hex> form).
    expect(recordHashRef(upstream)).toBe(expected.upstream_full_record_hash)

    // Downstream signature verifies independently.
    expect(await verifyRecord(downstream)).toBe(expected.downstream_signature_verifies)

    // Deterministic re-sign with the downstream seed reproduces the fixture
    // signature bit-for-bit.
    const seed = hexDecode(c.input.downstream_signer_seed_hex as string)
    const resigned = await signRecord({ ...downstream }, seed)
    expect(resigned.signature).toBe(downstream.signature)

    expect(expected.validator_should_accept).toBe(true)
  })

  it('non-genesis-with-provenance: signature valid but genesis-only invariant violated', async () => {
    const c = loadCase('non-genesis-with-provenance')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      genesis_chain_root_for_context: string
      record_chain_root: string
      record_hash_hex: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
      verifier_should_flag: boolean
      rejection_reason: string
    }

    // The signature itself is valid — rejection is at the policy layer,
    // not the crypto layer (§1.4.3 verification passes).
    expect(await verifyRecord(record)).toBe(expected.verifier_signature_ok)
    expect(expected.verifier_signature_ok).toBe(true)

    // The expected genesis chain_root for this context_id is computable
    // from the SDK primitive.
    expect(genesisChainRoot(record.context_id)).toBe(expected.genesis_chain_root_for_context)

    // Structural condition for §1.2.6 rejection: provenance_token present
    // while chain_root is NOT genesisChainRoot(context_id).
    expect(record.provenance_token).toBeDefined()
    expect(record.chain_root).toBe(expected.record_chain_root)
    expect(record.chain_root).not.toBe(genesisChainRoot(record.context_id))

    // record_hash matches the fixture.
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)

    // Validators MUST reject and verifiers MUST flag this record.
    expect(expected.validator_should_accept).toBe(false)
    expect(expected.verifier_should_flag).toBe(true)
  })

  it('omits-when-absent: canonical form omits the field; "" or null changes bytes and breaks signature', async () => {
    const c = loadCase('omits-when-absent')
    const record = c.input.record as AtribRecord
    const expected = c.expected as {
      canonical_signing_input_utf8: string
      provenance_token_in_canonical_form: boolean
      record_hash_hex: string
      validator_should_accept: boolean
      verifier_signature_ok: boolean
    }

    // Canonical signing input matches and contains no provenance_token key.
    const signingInput = signingInputUtf8(record)
    expect(signingInput).toBe(expected.canonical_signing_input_utf8)
    expect(signingInput.includes('provenance_token')).toBe(
      expected.provenance_token_in_canonical_form,
    )
    expect(expected.provenance_token_in_canonical_form).toBe(false)

    // record_hash matches and the signature verifies as-is.
    expect(recordHashHex(record)).toBe(expected.record_hash_hex)
    expect(await verifyRecord(record)).toBe(expected.verifier_signature_ok)

    // Absence-not-null: adding provenance_token as empty string produces
    // DIFFERENT canonical bytes, so the original signature no longer
    // verifies over the mutated record.
    const withEmpty: AtribRecord = { ...record, provenance_token: '' }
    expect(signingInputUtf8(withEmpty)).not.toBe(expected.canonical_signing_input_utf8)
    expect(signingInputUtf8(withEmpty).includes('provenance_token')).toBe(true)
    expect(await verifyRecord(withEmpty)).toBe(false)

    // Same for an explicit null (JCS serializes null, it does not drop it).
    const withNull = {
      ...record,
      provenance_token: null,
    } as unknown as AtribRecord
    expect(signingInputUtf8(withNull)).not.toBe(expected.canonical_signing_input_utf8)
    expect(signingInputUtf8(withNull).includes('provenance_token')).toBe(true)
    expect(await verifyRecord(withNull)).toBe(false)

    // Deterministic re-sign of the omitting record reproduces the fixture
    // signature, pinning that the signer also omits (not nulls) the field.
    const seed = hexDecode(c.input.signer_seed_hex as string)
    const resigned = await signRecord({ ...record }, seed)
    expect(resigned.signature).toBe(record.signature)
  })
})
