#!/usr/bin/env python3
"""One-time backfill: rewrite bare §X.Y and Dxxx references across atrib's
non-code prose to inline markdown links, with paths chosen by file location.

Skipped:
  * CHANGELOG.md files (regenerated by `pnpm changeset version` via the custom
    formatter at .changeset/changelog-atrib.cjs once authors stop introducing
    bare refs in changeset .md bodies).
  * Fenced code blocks and inline code spans within any file.
  * Already-linked references ([§...](url)).
  * External RFC refs (preceded by `RFC NNNN`).

Path strategy:
  * If target is the SAME file (atrib-spec.md self-ref to a §, DECISIONS.md
    self-ref to a Dxxx), use `#anchor`.
  * If target is in a different repo file, use a relative path computed from
    file location to repo root.

Modes:
  --dry-run        Print unified diffs but do not write (default)
  --apply          Write changes back
  --files PAT...   Restrict to files matching glob patterns (relative to repo)
  --no-changelog   Skip CHANGELOG.md (default — they regenerate)
  --include-changelog  Include CHANGELOG.md in the pass (one-time backfill)

The not_found set (RFC refs, speculative future refs, stale/typo refs) stays
bare and is surfaced in the summary so a human can triage.
"""
import argparse
import difflib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_FILE = "atrib-spec.md"
DECISIONS_FILE = "DECISIONS.md"
SKIP_DIRS = {"node_modules", "dist", "build", ".git", ".next", ".turbo",
             "wasm", "pkg", "target", "coverage"}


def slugify(text: str) -> str:
    s = text.strip()
    # Strip markdown link syntax: [display](url) -> display (the visible text).
    s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)
    s = s.lower()
    s = re.sub(r"`", "", s)
    s = re.sub(r"\*", "", s)
    s = re.sub(r"[\[\]()]", "", s)
    s = re.sub(r"[^a-z0-9\-_ ]", "", s)
    s = re.sub(r"\s+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-")


def collect_headings(path: Path):
    out = []
    in_fence = False
    for line in path.read_text(encoding="utf-8").split("\n"):
        s = line.lstrip()
        if s.startswith("```") or s.startswith("~~~"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = re.match(r"^(#{1,6})\s+(.+?)\s*$", s)
        if m:
            out.append(m.group(2))
    return out


def build_section_anchors():
    out = {}
    for heading in collect_headings(ROOT / SPEC_FILE):
        stripped = re.sub(r"^§\s?", "", heading)
        m = re.match(r"^(\d+(?:\.\d+)*)\s+", stripped)
        if not m:
            continue
        out[m.group(1)] = slugify(heading)
    return out


def build_adr_anchors():
    out = {}
    for heading in collect_headings(ROOT / DECISIONS_FILE):
        m = re.match(r"^(D\d{3})\b", heading)
        if m:
            out[m.group(1).upper()] = slugify(heading)
    return out


def build_link_mask(line: str):
    mask = [0] * len(line)
    i = 0
    n = len(line)
    while i < n:
        if line[i] == "[":
            depth = 1
            j = i + 1
            while j < n and depth > 0:
                if line[j] == "[":
                    depth += 1
                elif line[j] == "]":
                    depth -= 1
                if depth == 0:
                    break
                j += 1
            if depth != 0 or j + 1 >= n or line[j + 1] != "(":
                i += 1
                continue
            k = j + 2
            pdepth = 1
            while k < n and pdepth > 0:
                if line[k] == "(":
                    pdepth += 1
                elif line[k] == ")":
                    pdepth -= 1
                if pdepth == 0:
                    break
                k += 1
            if pdepth != 0:
                i += 1
                continue
            for m in range(i, k + 1):
                mask[m] = 1
            i = k + 1
        else:
            i += 1
    return mask


def build_inline_code_mask(line: str):
    mask = [0] * len(line)
    i = 0
    while i < len(line):
        if line[i] == "`":
            close = line.find("`", i + 1)
            if close == -1:
                break
            for m in range(i, close + 1):
                mask[m] = 1
            i = close + 1
        else:
            i += 1
    return mask


REF_RE = re.compile(r"§\s?\d+(?:\.\d+)*|\bD\d{3}\b")


def relative_prefix(file_rel: Path):
    """Return the prefix to reach repo root from `file_rel`'s parent."""
    depth = len(file_rel.parts) - 1
    if depth == 0:
        return ""
    return "/".join([".."] * depth) + "/"


def autolink_line(line: str, sections, adrs, file_rel: Path):
    link_mask = build_link_mask(line)
    code_mask = build_inline_code_mask(line)
    mask = [a or b for a, b in zip(link_mask, code_mask)]
    file_str = str(file_rel)
    is_spec = file_str == SPEC_FILE
    is_decisions = file_str == DECISIONS_FILE
    prefix = relative_prefix(file_rel)
    out = []
    last = 0
    found_unmapped = []
    for m in REF_RE.finditer(line):
        start, end = m.start(), m.end()
        token = m.group(0)
        out.append(line[last:start])
        last = end
        if any(mask[i] for i in range(start, end)):
            out.append(token)
            continue
        if token.startswith("§"):
            before = line[max(0, start - 12):start]
            if re.search(r"RFC\s+\d{3,5}\s+$", before):
                out.append(token)
                continue
            num = re.sub(r"§\s?", "", token).strip()
            slug = sections.get(num)
            if not slug:
                found_unmapped.append(token)
                out.append(token)
                continue
            if is_spec:
                href = f"#{slug}"
            else:
                href = f"{prefix}{SPEC_FILE}#{slug}"
            out.append(f"[§{num}]({href})")
        else:
            slug = adrs.get(token.upper())
            if not slug:
                found_unmapped.append(token)
                out.append(token)
                continue
            if is_decisions:
                href = f"#{slug}"
            else:
                href = f"{prefix}{DECISIONS_FILE}#{slug}"
            out.append(f"[{token}]({href})")
    out.append(line[last:])
    return "".join(out), found_unmapped


def autolink_text(text: str, sections, adrs, file_rel: Path):
    lines_out = []
    in_fence = False
    unmapped = []
    for line in text.split("\n"):
        trimmed = line.lstrip()
        if trimmed.startswith("```") or trimmed.startswith("~~~"):
            in_fence = not in_fence
            lines_out.append(line)
            continue
        if in_fence:
            lines_out.append(line)
            continue
        m = re.match(r"^(\s*#{1,6}\s+)(.*)$", line)
        if m:
            new_line, line_unmapped = autolink_heading(
                line, m.group(1), m.group(2), sections, adrs, file_rel,
            )
            lines_out.append(new_line)
            unmapped.extend(line_unmapped)
            continue
        new_line, line_unmapped = autolink_line(line, sections, adrs, file_rel)
        lines_out.append(new_line)
        unmapped.extend(line_unmapped)
    return "\n".join(lines_out), unmapped


def autolink_heading(line: str, prefix: str, title: str, sections, adrs, file_rel: Path):
    """Autolink a heading. Skip the first ref if it appears at the start of the
    title (it is the heading's own anchor source, e.g. '## D001: Foo' or
    '## §1 Bar'); link other refs deeper in the title (e.g. cross-refs).
    """
    first_match = REF_RE.match(title)
    if first_match:
        skip_end = first_match.end()
        # Allow up to one separator char (`:`, `.`, ` `) before considering the
        # ref "non-leading"; if there's substantial prose before the first ref,
        # treat it as a normal cross-reference and link it.
        if first_match.start() == 0:
            head_kept = title[:skip_end]
            tail_to_link = title[skip_end:]
            new_tail, unmapped = autolink_line(tail_to_link, sections, adrs, file_rel)
            return prefix + head_kept + new_tail, unmapped
    new_title, unmapped = autolink_line(title, sections, adrs, file_rel)
    return prefix + new_title, unmapped


def gather_files(root: Path, patterns, include_changelog: bool):
    out = []
    for p in root.rglob("*.md"):
        rel = p.relative_to(root)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if any(part.startswith(".") and part != ".changeset" for part in rel.parts):
            continue
        if not include_changelog and rel.name == "CHANGELOG.md":
            continue
        if patterns:
            if not any(rel.match(pat) for pat in patterns):
                continue
        out.append(p)
    return sorted(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true",
                        help="Write changes back (default is dry-run)")
    parser.add_argument("--files", nargs="*", default=[],
                        help="Glob patterns relative to repo root")
    parser.add_argument("--include-changelog", action="store_true",
                        help="Include CHANGELOG.md files (one-time backfill)")
    parser.add_argument("--show-diff", action="store_true",
                        help="Print unified diff for each modified file")
    args = parser.parse_args()

    sections = build_section_anchors()
    adrs = build_adr_anchors()
    print(f"Loaded {len(sections)} section anchors and {len(adrs)} ADR anchors")

    files = gather_files(ROOT, args.files, args.include_changelog)
    print(f"Scanning {len(files)} markdown files...\n")

    total_replaced = 0
    files_changed = 0
    all_unmapped = []
    for f in files:
        rel = f.relative_to(ROOT)
        original = f.read_text(encoding="utf-8")
        rewritten, unmapped = autolink_text(original, sections, adrs, rel)
        if rewritten == original:
            continue
        # Approximate replacement count by counting new [§ and [D introductions.
        new_links = (rewritten.count("[§") - original.count("[§")) + \
                    (rewritten.count("[D") - original.count("[D"))
        total_replaced += new_links
        files_changed += 1
        if unmapped:
            all_unmapped.extend((str(rel), u) for u in unmapped)
        action = "WOULD WRITE" if not args.apply else "WROTE"
        print(f"{action}  {rel}  +{new_links} link(s)")
        if args.show_diff:
            diff = difflib.unified_diff(
                original.split("\n"),
                rewritten.split("\n"),
                fromfile=f"a/{rel}",
                tofile=f"b/{rel}",
                lineterm="",
                n=2,
            )
            for ln in diff:
                print(ln)
            print()
        if args.apply:
            f.write_text(rewritten, encoding="utf-8")

    print(f"\nSummary: {total_replaced} link(s) added across {files_changed} file(s)")
    if all_unmapped:
        print(f"\nUnmapped references ({len(all_unmapped)}):")
        seen = set()
        for path, ref in all_unmapped:
            key = (path, ref)
            if key in seen:
                continue
            seen.add(key)
            print(f"  {path}: {ref}")
    if not args.apply:
        print("\n(dry-run; pass --apply to write)")


if __name__ == "__main__":
    main()
