// SPDX-License-Identifier: Apache-2.0

/**
 * §3.4.1.1 conformance: graph-node's compact intra-session edge derivation
 * must produce the exact edge set documented in spec/conformance/3.4.1/cases.
 *
 * The corpus is regenerated by
 * `pnpm --filter @atrib/log-dev exec tsx scripts/generate-conformance-3.4.1.ts`.
 * Re-run when §3.4.1.1 / §3.2.4 derivation rules change. This test is the
 * load-bearing regression boundary preventing silent compaction drift.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { canonicalRecord, sha256, hexEncode } from '@atrib/mcp'
import type { AtribRecord } from '@atrib/mcp'
import { buildGraph } from '../src/graph-builder.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const CASES_DIR = resolve(HERE, '..', '..', '..', 'spec', 'conformance', '3.4.1', 'cases')

interface ExpectedEdge {
  type: 'CHAIN_PRECEDES' | 'SESSION_PRECEDES' | 'SESSION_PARALLEL'
  source_record_index: number
  target_record_index: number
  directed: boolean
}

interface CaseFile {
  name: string
  description: string
  input: { records: AtribRecord[]; compact: boolean }
  expected: { edges: ExpectedEdge[]; edge_count_by_type: Record<string, number> }
}

function loadCases(): CaseFile[] {
  return readdirSync(CASES_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(CASES_DIR, f), 'utf8')) as CaseFile)
}

function nodeIdFor(record: AtribRecord): string {
  return `sha256:${hexEncode(sha256(canonicalRecord(record)))}`
}

describe('§3.4.1.1 conformance: intra-session edge compaction', () => {
  const cases = loadCases()

  for (const c of cases) {
    it(`${c.name}, ${c.expected.edges.length} expected edges`, async () => {
      const graph = await buildGraph(c.input.records, [], {
        compactIntraSessionEdges: c.input.compact,
      })

      // Filter to only the three structural edge types this corpus enumerates.
      // The graph builder may produce other edge types (CONVERGES_ON, CROSS_SESSION,
      // INFORMED_BY, PROVENANCE_OF, ANNOTATES, REVISES), we don't constrain those
      // here; §3.4.1.1 only governs SESSION_PRECEDES + SESSION_PARALLEL emission
      // (CHAIN_PRECEDES is included for cross-checking that the chain backbone
      // emerges as expected and isn't disrupted by compaction).
      const STRUCTURAL = new Set(['CHAIN_PRECEDES', 'SESSION_PRECEDES', 'SESSION_PARALLEL'])
      const actualStructural = graph.edges.filter((e) => STRUCTURAL.has(e.type))

      expect(actualStructural).toHaveLength(c.expected.edges.length)

      // Resolve expected edges to actual node IDs by computing each input
      // record's hash and comparing against actual edge endpoints. Build a
      // lookup so the comparison is order-independent.
      const recordIds = c.input.records.map(nodeIdFor)
      const expectedSet = new Set(
        c.expected.edges.map(
          (e) =>
            `${e.type}|${e.directed}|${recordIds[e.source_record_index]!}|${recordIds[e.target_record_index]!}`,
        ),
      )
      // For undirected SESSION_PARALLEL the spec doesn't constrain orientation,
      // so allow either orientation in the actual edge.
      const actualSet = new Set<string>()
      for (const e of actualStructural) {
        if (!e.directed) {
          // Add both orientations so the lookup matches either.
          actualSet.add(`${e.type}|${e.directed}|${e.source}|${e.target}`)
          actualSet.add(`${e.type}|${e.directed}|${e.target}|${e.source}`)
        } else {
          actualSet.add(`${e.type}|${e.directed}|${e.source}|${e.target}`)
        }
      }

      for (const expected of expectedSet) {
        expect(actualSet, `missing expected edge ${expected}`).toContain(expected)
      }
    })
  }

  it('manifest enumerates all case files (no orphans)', () => {
    const manifestPath = resolve(CASES_DIR, '..', 'manifest.json')
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
    const caseFiles = readdirSync(CASES_DIR).filter((f) => f.endsWith('.json')).sort()
    const manifestNames = manifest.cases.map((c: { file: string }) => c.file.replace(/^cases\//, '')).sort()
    expect(manifestNames).toEqual(caseFiles)
  })
})
