// SPDX-License-Identifier: Apache-2.0

/**
 * §3.4.5 / §3.4.6 / §3.4.7 conformance: graph-node's trace, chain, and
 * creator-graph endpoints must produce the response sets documented in
 * spec/conformance/3.4.5,6,7/cases.
 *
 * Corpora regenerated by
 * `pnpm --filter @atrib/log-dev exec tsx scripts/generate-conformance-3.4.5-7.ts`.
 * Re-run when §3.4.5 / §3.4.6 / §3.4.7 walk semantics change. This is the
 * load-bearing regression boundary preventing structure-vs-claims layer drift.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join } from 'node:path'
import { bindGraphServer } from '../src/server.js'
import { canonicalRecord, hexEncode, sha256 } from '@atrib/mcp'
import type { AtribRecord } from '@atrib/mcp'

const HERE = dirname(fileURLToPath(import.meta.url))
const CORPUS_ROOT = resolve(HERE, '..', '..', '..', 'spec', 'conformance')

interface BaseCase {
  name: string
  description: string
}

interface TraceCase extends BaseCase {
  input: {
    records: AtribRecord[]
    start_record_index: number
    depth: number
    include_annotations: boolean
    include_revisions: boolean
  }
  expected: {
    record_indexes_in_response: number[]
    truncated_by_depth: boolean
    truncated_by_count: boolean
  }
}

interface ChainCase extends BaseCase {
  input: { records: AtribRecord[]; start_record_index: number; depth: number }
  expected: { record_indexes_in_response: number[]; truncated_by_depth: boolean }
}

interface CreatorGraphCase extends BaseCase {
  input: { records: AtribRecord[]; include_intra_session: boolean }
  expected: {
    record_count: number
    edge_types_excluded: string[]
    edge_types_present_at_least_one: string[]
    intra_session_edges_filtered: boolean
  }
}

function loadCases<T>(section: string): T[] {
  const dir = join(CORPUS_ROOT, section, 'cases')
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')) as T)
}

function hashHex(record: AtribRecord): string {
  return hexEncode(sha256(canonicalRecord(record)))
}

let url: string
let close: () => Promise<void>

beforeAll(async () => {
  const handle = await bindGraphServer(0)
  url = handle.url
  close = handle.close
})

afterAll(async () => { await close() })

async function ingestAll(records: AtribRecord[]): Promise<void> {
  for (const r of records) {
    const res = await fetch(`${url}/v1/ingest`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(r),
    })
    if (!res.ok) {
      throw new Error(`ingest failed: ${res.status} ${await res.text()}`)
    }
  }
}

// Each test ingests its own fixture into the same shared server instance.
// The store accumulates records across tests; that's fine because every case
// uses unique context_ids / content_ids derived from its own seed prefixes
// (the generator picks distinct content_ids per case to avoid collision).

describe('§3.4.5 conformance: provenance trace', () => {
  const cases = loadCases<TraceCase>('3.4.5')

  for (const c of cases) {
    it(`${c.name}, ${c.expected.record_indexes_in_response.length} expected records`, async () => {
      await ingestAll(c.input.records)
      const startHash = hashHex(c.input.records[c.input.start_record_index]!)
      const params = new URLSearchParams()
      params.set('depth', String(c.input.depth))
      if (!c.input.include_annotations) params.set('include_annotations', 'false')
      if (!c.input.include_revisions) params.set('include_revisions', 'false')

      const res = await fetch(`${url}/v1/trace/${startHash}?${params.toString()}`)
      expect(res.ok, `trace returned ${res.status}`).toBe(true)
      const body = await res.json()

      expect(body.record_count).toBe(c.expected.record_indexes_in_response.length)
      expect(body.truncated_by_depth).toBe(c.expected.truncated_by_depth)
      expect(body.truncated_by_count).toBe(c.expected.truncated_by_count)

      const expectedHashSet = new Set(
        c.expected.record_indexes_in_response.map((i) => `sha256:${hashHex(c.input.records[i]!)}`),
      )
      const actualHashSet = new Set(body.graph.nodes.map((n: { id: string }) => n.id))
      // The trace response set MUST contain exactly the expected hashes (for
      // the records in the test corpus). The graph builder may also surface
      // dangling/synthetic nodes for unresolved references; we filter to only
      // node IDs that match input records, not synthetic ones.
      for (const expected of expectedHashSet) {
        expect(actualHashSet, `missing expected node ${expected}`).toContain(expected)
      }
      // Verify exclusions: any input record NOT in expected indexes MUST NOT
      // appear in the response. This is the structure-vs-claims invariant
      // load-bearing assertion for §3.4.5.
      for (let i = 0; i < c.input.records.length; i++) {
        if (c.expected.record_indexes_in_response.includes(i)) continue
        const excludedHash = `sha256:${hashHex(c.input.records[i]!)}`
        expect(actualHashSet, `record at index ${i} should NOT be in trace response`).not.toContain(excludedHash)
      }
    })
  }
})

describe('§3.4.6 conformance: causal chain', () => {
  const cases = loadCases<ChainCase>('3.4.6')

  for (const c of cases) {
    it(`${c.name}, ${c.expected.record_indexes_in_response.length} expected records`, async () => {
      await ingestAll(c.input.records)
      const startHash = hashHex(c.input.records[c.input.start_record_index]!)

      const res = await fetch(`${url}/v1/chain/${startHash}?depth=${c.input.depth}`)
      expect(res.ok, `chain returned ${res.status}`).toBe(true)
      const body = await res.json()

      expect(body.record_count).toBe(c.expected.record_indexes_in_response.length)
      expect(body.truncated_by_depth).toBe(c.expected.truncated_by_depth)

      const expectedHashSet = new Set(
        c.expected.record_indexes_in_response.map((i) => `sha256:${hashHex(c.input.records[i]!)}`),
      )
      const actualHashSet = new Set(body.graph.nodes.map((n: { id: string }) => n.id))
      for (const expected of expectedHashSet) {
        expect(actualHashSet, `missing expected node ${expected}`).toContain(expected)
      }
      for (let i = 0; i < c.input.records.length; i++) {
        if (c.expected.record_indexes_in_response.includes(i)) continue
        const excludedHash = `sha256:${hashHex(c.input.records[i]!)}`
        expect(actualHashSet, `record at index ${i} should NOT be in chain response`).not.toContain(excludedHash)
      }
    })
  }
})

describe('§3.4.7 conformance: creator activity-map', () => {
  const cases = loadCases<CreatorGraphCase>('3.4.7')

  for (const c of cases) {
    it(`${c.name}`, async () => {
      await ingestAll(c.input.records)
      // All records are signed by the same key (ALICE_SEED in the generator);
      // pick the creator_key off the first record.
      const creatorKey = c.input.records[0]!.creator_key
      const params = new URLSearchParams()
      if (c.input.include_intra_session) params.set('include_intra_session', 'true')
      // Also pin the time window to the records' timestamps so accumulated
      // records from earlier tests don't pollute the response.
      const ts = c.input.records.map((r) => r.timestamp).sort((a, b) => a - b)
      params.set('since', String(ts[0]!))
      params.set('until', String(ts[ts.length - 1]!))

      const res = await fetch(`${url}/v1/creators/${encodeURIComponent(creatorKey)}/graph?${params.toString()}`)
      expect(res.ok, `creator-graph returned ${res.status}`).toBe(true)
      const body = await res.json()

      expect(body.record_count).toBe(c.expected.record_count)
      expect(body.intra_session_edges_filtered).toBe(c.expected.intra_session_edges_filtered)

      const presentTypes = new Set(body.graph.edges.map((e: { type: string }) => e.type))
      for (const t of c.expected.edge_types_excluded) {
        expect(presentTypes, `edge type ${t} should be excluded`).not.toContain(t)
      }
      for (const t of c.expected.edge_types_present_at_least_one) {
        expect(presentTypes, `edge type ${t} should be present at least once`).toContain(t)
      }
    })
  }
})

describe('manifests', () => {
  for (const section of ['3.4.5', '3.4.6', '3.4.7']) {
    it(`§${section} manifest enumerates all case files (no orphans)`, () => {
      const manifestPath = join(CORPUS_ROOT, section, 'manifest.json')
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
      const dir = join(CORPUS_ROOT, section, 'cases')
      const caseFiles = readdirSync(dir).filter((f) => f.endsWith('.json')).sort()
      const manifestNames = manifest.cases.map((c: { file: string }) => c.file.replace(/^cases\//, '')).sort()
      expect(manifestNames).toEqual(caseFiles)
    })
  }
})
