# SPDX-License-Identifier: Apache-2.0
"""atrib — verifiable agent actions, Python client SDK.

The first non-TypeScript implementation of the atrib record layer
(spec §1) and SDK contract (spec §5). Byte-identical to the TypeScript
implementation: identical inputs produce identical JCS canonical forms,
signatures, record hashes, and propagation tokens, verified against the
shared conformance corpora under ``spec/conformance/``.
"""

from .canon import (
    canonical_cross_attestation_input,
    canonical_record,
    canonical_signing_input,
    jcs,
)
from .anchors import (
    ANCHOR_CLAIM_PREFIX,
    ANCHOR_TYPES,
    BUILT_IN_DEFAULT_ANCHOR_SET,
    AnchorDescriptor,
    AnchorPostureResolution,
    AnchorSetConfig,
    anchor_claim_artifact,
    resolve_anchor_posture,
    resolve_effective_anchors,
)
from .attribution import (
    ATTRIBUTION_EXTENSION_KEY,
    ATTRIBUTION_LOG_SUBMISSION_STATUSES,
    AttributionReceiptBlock,
    AttributionReceiptConsistency,
    AttributionReceiptVerification,
    check_attribution_receipt_consistency,
    parse_attribution_receipt_block,
    verify_attribution_receipt,
)
from .chain import chain_root, genesis_chain_root, resolve_chain_root
from .client import AnchorSpec, AtribClient, AttestRef, AttestResult, RecallOutcome
from .evidence import (
    ATRIB_PROFILE_BASE,
    ATRIB_PROFILE_REGISTRY,
    EVIDENCE_CONSTRAINT_STATUSES,
    EVIDENCE_REF_KINDS,
    EVIDENCE_TIERS,
    FROZEN_LEGACY_PROTOCOLS,
    LEGACY_PROTOCOL_TO_PROFILE,
    EnvelopeReproducibility,
    EnvelopeValidation,
    EvidenceConstraint,
    EvidenceEnvelope,
    EvidencePayload,
    EvidencePayloadRef,
    EvidenceResult,
    EvidenceVerifier,
    ProfileClassification,
    assess_reproducibility,
    build_evidence_envelope,
    classify_profile,
    evidence_envelope_key,
    evidence_tier_rank,
    from_legacy_evidence_block,
    is_relay_identity_swap,
    is_valid_envelope,
    jcs_sha256,
    map_legacy_evidence_block,
    order_envelope_instances,
    raw_sha256,
    render_envelope_opaque,
    validate_envelope,
)
from .content_id import compute_content_id, normalize_server_url
from .encoding import base64url_decode, base64url_encode, hex_decode, hex_encode
from .hashes import (
    derive_provenance_token,
    record_hash_bytes,
    record_hash_hex,
    record_hash_ref,
    sha256,
)
from .keys import ResolvedKey, resolve_key
from .mirror import (
    MirrorLine,
    append_mirror_line,
    default_mirror_read_path,
    default_mirror_write_path,
    mirror_corpus_tail_hash_hex,
    mirror_tail_hash_hex,
    parse_mirror_line,
    read_mirror,
    read_mirror_corpus_tail,
    read_mirror_tail,
)
from .records import (
    SYNTHETIC_SERVER_URL,
    build_and_sign_emit_record,
    content_hash,
    leaf_of_event_type_uri,
)
from .signing import (
    get_public_key,
    sign_record,
    sign_transaction_attestation,
    sign_transaction_record,
    verify_record,
)
from .submission import DEFAULT_LOG_ENDPOINT, SubmissionQueue, normalize_log_endpoint
from .token import DecodedToken, decode_token, encode_token
from .types import (
    EVENT_TYPE_ANNOTATION_URI,
    EVENT_TYPE_DIRECTORY_ANCHOR_URI,
    EVENT_TYPE_OBSERVATION_URI,
    EVENT_TYPE_REVISION_URI,
    EVENT_TYPE_TOOL_CALL_URI,
    EVENT_TYPE_TRANSACTION_URI,
    SPEC_VERSION,
    AtribRecord,
    SignerEntry,
    event_type_uri_to_byte,
    is_normative_event_type_uri,
    is_valid_event_type_uri,
    normalize_event_type,
)
from .validation import ValidationResult, validate_submission

__version__ = "0.1.1"

__all__ = [
    "ANCHOR_CLAIM_PREFIX",
    "ANCHOR_TYPES",
    "ATRIB_PROFILE_BASE",
    "ATRIB_PROFILE_REGISTRY",
    "ATTRIBUTION_EXTENSION_KEY",
    "ATTRIBUTION_LOG_SUBMISSION_STATUSES",
    "AnchorDescriptor",
    "AnchorPostureResolution",
    "AnchorSetConfig",
    "AnchorSpec",
    "AttributionReceiptBlock",
    "AttributionReceiptConsistency",
    "AttributionReceiptVerification",
    "BUILT_IN_DEFAULT_ANCHOR_SET",
    "anchor_claim_artifact",
    "check_attribution_receipt_consistency",
    "parse_attribution_receipt_block",
    "resolve_anchor_posture",
    "resolve_effective_anchors",
    "verify_attribution_receipt",
    "AtribClient",
    "AtribRecord",
    "AttestRef",
    "AttestResult",
    "DecodedToken",
    "DEFAULT_LOG_ENDPOINT",
    "EVIDENCE_CONSTRAINT_STATUSES",
    "EVIDENCE_REF_KINDS",
    "EVIDENCE_TIERS",
    "FROZEN_LEGACY_PROTOCOLS",
    "LEGACY_PROTOCOL_TO_PROFILE",
    "EnvelopeReproducibility",
    "EnvelopeValidation",
    "EvidenceConstraint",
    "EvidenceEnvelope",
    "EvidencePayload",
    "EvidencePayloadRef",
    "EvidenceResult",
    "EvidenceVerifier",
    "ProfileClassification",
    "assess_reproducibility",
    "build_evidence_envelope",
    "classify_profile",
    "evidence_envelope_key",
    "evidence_tier_rank",
    "from_legacy_evidence_block",
    "is_relay_identity_swap",
    "is_valid_envelope",
    "jcs_sha256",
    "map_legacy_evidence_block",
    "order_envelope_instances",
    "raw_sha256",
    "render_envelope_opaque",
    "validate_envelope",
    "EVENT_TYPE_ANNOTATION_URI",
    "EVENT_TYPE_DIRECTORY_ANCHOR_URI",
    "EVENT_TYPE_OBSERVATION_URI",
    "EVENT_TYPE_REVISION_URI",
    "EVENT_TYPE_TOOL_CALL_URI",
    "EVENT_TYPE_TRANSACTION_URI",
    "MirrorLine",
    "RecallOutcome",
    "ResolvedKey",
    "SPEC_VERSION",
    "SignerEntry",
    "SubmissionQueue",
    "SYNTHETIC_SERVER_URL",
    "ValidationResult",
    "append_mirror_line",
    "base64url_decode",
    "base64url_encode",
    "build_and_sign_emit_record",
    "canonical_cross_attestation_input",
    "canonical_record",
    "canonical_signing_input",
    "chain_root",
    "compute_content_id",
    "content_hash",
    "decode_token",
    "default_mirror_read_path",
    "default_mirror_write_path",
    "derive_provenance_token",
    "encode_token",
    "event_type_uri_to_byte",
    "genesis_chain_root",
    "get_public_key",
    "hex_decode",
    "hex_encode",
    "is_normative_event_type_uri",
    "is_valid_event_type_uri",
    "jcs",
    "leaf_of_event_type_uri",
    "mirror_corpus_tail_hash_hex",
    "mirror_tail_hash_hex",
    "normalize_event_type",
    "normalize_log_endpoint",
    "normalize_server_url",
    "parse_mirror_line",
    "read_mirror",
    "read_mirror_corpus_tail",
    "read_mirror_tail",
    "record_hash_bytes",
    "record_hash_hex",
    "record_hash_ref",
    "resolve_chain_root",
    "resolve_key",
    "sha256",
    "sign_record",
    "sign_transaction_attestation",
    "sign_transaction_record",
    "validate_submission",
    "verify_record",
]
