/**
 * Spec §2.6.1 conformance tests, drives @atrib/log-dev with the canonical
 * shared test corpus at `spec/conformance/2.6.1/`.
 *
 * The corpus is the contract that any atrib log implementation must honor:
 * @atrib/log-dev runs it here in TypeScript, the future services/log/
 * Tessera-backed Go service will run the same corpus once it ships. The
 * corpus is regenerated by `pnpm tsx scripts/generate-conformance-corpus.ts`
 * and committed under `spec/conformance/2.6.1/` so it's reviewable in PRs.
 *
 * Why mock the clock: the corpus stores fully-signed records with frozen
 * timestamps so the bytes are stable across runs. Validation step 4 (timestamp
 * not more than 10 minutes in the future) only produces stable results when
 * the consumer pretends the wall clock matches the manifest's
 * reference_time_ms. We use vi.setSystemTime() for this, it's a test-only
 * concern, not a production code change.
 *
 * Cases the dev log skips: @atrib/log-dev does not implement §2.6.1 Step 1
 * (Ed25519 signature verification, see server.ts file header for the
 * circular-dep rationale). The single Step 1 case in the corpus
 * (`reject-bad-signature`) is in DEV_LOG_SKIPS below. The future Go service
 * is expected to honor it; the corpus is the canonical truth.
 */

import { describe, it, expect, beforeEach, afterEach, beforeAll } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { startDevLog, type DevLog } from '../src/index.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const CORPUS_ROOT = resolve(HERE, '../../../spec/conformance/2.6.1')

interface CaseFile {
  name: string
  spec_section: string
  validation_step: number | null
  description: string
  request: {
    method: 'POST'
    path: string
    headers: Record<string, string>
    body: unknown
    body_is_raw_string?: boolean
  }
  expected: {
    status: number
    error_contains?: string
    response_shape?: Record<string, string>
  }
  notes?: string
}

interface SequenceFile {
  name: string
  spec_section: string
  validation_step: number | null
  description: string
  steps: Array<{
    request: CaseFile['request']
    expected: CaseFile['expected'] & {
      capture_log_index_as?: string
      log_index_matches?: string
    }
  }>
  post: { log_size: number }
}

interface Manifest {
  spec_version: string
  reference_time_ms: number
  cases: Array<{ file: string; name: string }>
  sequences: Array<{ file: string; name: string }>
}

/**
 * Cases the dev log can't honor and the test consumer must skip with a
 * console warning. Empty for the future Go service. Each entry MUST cite
 * the reason, never silently disable a case without recording why.
 */
const DEV_LOG_SKIPS: Record<string, string> = {
  'reject-bad-signature':
    '@atrib/log-dev skips §2.6.1 Step 1 (Ed25519 verify) to avoid a circular workspace dep on @atrib/verify',
}

function loadJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf-8')) as T
}

function loadManifest(): Manifest {
  return loadJson<Manifest>(join(CORPUS_ROOT, 'manifest.json'))
}

function loadAllCases(): CaseFile[] {
  const dir = join(CORPUS_ROOT, 'cases')
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort() // deterministic test order
    .map((f) => loadJson<CaseFile>(join(dir, f)))
}

function loadAllSequences(): SequenceFile[] {
  const dir = join(CORPUS_ROOT, 'sequences')
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => loadJson<SequenceFile>(join(dir, f)))
}

async function sendCaseRequest(log: DevLog, request: CaseFile['request']): Promise<Response> {
  const body = request.body_is_raw_string ? (request.body as string) : JSON.stringify(request.body)
  return fetch(`${log.url}${request.path}`, {
    method: request.method,
    headers: request.headers,
    body,
  })
}

describe('spec §2.6.1 conformance corpus', () => {
  const manifest = loadManifest()
  const cases = loadAllCases()
  const sequences = loadAllSequences()

  beforeAll(() => {
    // Sanity check: the corpus is non-empty and the manifest's case list
    // matches the on-disk files. Catches "added a case file but forgot to
    // regenerate the manifest" mistakes.
    expect(cases.length).toBeGreaterThan(0)
    expect(manifest.cases.length).toBe(cases.length)
    expect(manifest.sequences.length).toBe(sequences.length)
  })

  describe('cases', () => {
    let log: DevLog

    beforeEach(async () => {
      // Freeze the clock to the corpus reference time so any Step 4
      // (future-timestamp) case produces stable validation outcomes.
      const { vi } = await import('vitest')
      vi.useFakeTimers()
      vi.setSystemTime(new Date(manifest.reference_time_ms))

      log = await startDevLog({ port: 0 })
    })

    afterEach(async () => {
      await log.close()
      const { vi } = await import('vitest')
      vi.useRealTimers()
    })

    for (const c of cases) {
      const skipReason = DEV_LOG_SKIPS[c.name]
      const testName = `${c.name} (§${c.spec_section}${c.validation_step !== null ? ` Step ${c.validation_step}` : ''})`

      if (skipReason) {
        it.skip(`${testName}, SKIPPED: ${skipReason}`, () => {})
        continue
      }

      it(testName, async () => {
        const response = await sendCaseRequest(log, c.request)
        expect(
          response.status,
          `expected ${c.expected.status}, got ${response.status}: ${c.description}`,
        ).toBe(c.expected.status)

        if (c.expected.error_contains) {
          const body = (await response.json()) as { error?: string }
          expect(body.error ?? '').toContain(c.expected.error_contains)
        }

        if (c.expected.response_shape) {
          const body = (await response.json()) as Record<string, unknown>
          for (const [field, expectedType] of Object.entries(c.expected.response_shape)) {
            if (expectedType === 'array') {
              expect(Array.isArray(body[field]), `${field} should be array`).toBe(true)
            } else {
              expect(typeof body[field], `${field} should be ${expectedType}`).toBe(expectedType)
            }
          }
        }
      })
    }
  })

  describe('sequences', () => {
    let log: DevLog

    beforeEach(async () => {
      const { vi } = await import('vitest')
      vi.useFakeTimers()
      vi.setSystemTime(new Date(manifest.reference_time_ms))

      log = await startDevLog({ port: 0 })
    })

    afterEach(async () => {
      await log.close()
      const { vi } = await import('vitest')
      vi.useRealTimers()
    })

    for (const s of sequences) {
      const testName = `${s.name} (§${s.spec_section}${s.validation_step !== null ? ` Step ${s.validation_step}` : ''})`

      it(testName, async () => {
        const captured: Record<string, number> = {}

        for (const step of s.steps) {
          const response = await sendCaseRequest(log, step.request)
          expect(response.status).toBe(step.expected.status)

          if (response.status === 200) {
            const body = (await response.json()) as { log_index: number }
            if (step.expected.capture_log_index_as) {
              captured[step.expected.capture_log_index_as] = body.log_index
            }
            if (step.expected.log_index_matches) {
              const expected = captured[step.expected.log_index_matches]
              expect(
                expected,
                `no captured log_index named "${step.expected.log_index_matches}"`,
              ).toBeDefined()
              expect(body.log_index).toBe(expected)
            }
          }
        }

        expect(log.size).toBe(s.post.log_size)
      })
    }
  })
})
